### ISSUE TITLE
the last layer frequently output '-nan'

### ISSUE THREAD

**Issue by xueyingxue001** [intel/mkl-dnn#106]
Hi
	I have a question when use mkl api by c++.
	Description:
		I create a class like this:
			class _c{
				_c(){
					create network;
					init weights;
				}
				void run(){
					run network;
				}
			}
		Main code like this:
			_c c1();
			_c c2();
			_c c3();
			c1.run();
			c2.run();
			c3.run();
		However, the last layer frequently output '-nan'.
		PS: It can work without c2, c3. 
	
	My network as below:
		input -> conv -> maxpool -> fc -> softmax
		input:
			float *input = new float[32*32];
		conv:
			output channel: 32
			input channel: 1
			input heigh: 32
			input width: 32
			kernel heigh: 5
			kernel width: 5
			pad heigh: 1
			pad width: 1
			stride heigh: 1
			stride width: 1
		pool:
			kernel heigh: conv->getOutputHeight()
			kernel width: conv->getOutputWidth()
			pad heigh: 0
			pad width: 0
			stride heigh: 1
			stride width: 1
		fc:
			output channel: 2
			no relu
		softmax:
			softmax_axis: 1
	
	Help, please.
	Thank you very much.

**Comment by xmsjshou** [comment]
Hi @xueyingxue001 have you solved the problem?
I meet the same issue...

**Comment by nhkrishna** [comment]
Hi @xueyingxue001, @xmsjshou  

I'm also facing the similar kind of issue for the segmentation networks. Can anyone please elaborate how to resolve this  issue ?

Thanks

**Comment by xmsjshou** [comment]
My problem were some calculation errors dealing with float variables.
Please check your calculation and operations with float vars.

**Comment by nhkrishna** [comment]
Hi @xmsjshou 

I am not doing any operation with float values. I have two float buffers which are used just used as input and output to softmax layers. Here i attached the files to reproduce the issue
Input binary file- [sfmax_src.bin.txt](https://github.com/intel/mkl-dnn/files/2318024/sfmax_src.bin.txt)
Standalone Code - [softmaxClassifier.cpp.txt](https://github.com/intel/mkl-dnn/files/2318028/softmaxClassifier.cpp.txt)
outputfile - [softmaxOutput:47.txt](https://github.com/intel/mkl-dnn/files/2318033/softmaxOutput.47.txt)

Can you please check this ?

Thanks

**Comment by emfomenk** [comment]
Hi @nhkrishna,

Could you please share the details of Intel MKL-DNN you use: the exact version (hash), compiler and whether you build Intel MKL-DNN w/ or w/o Intel MKL binary?

**Comment by emfomenk** [comment]
Hi @nhkrishna,

Seems like a bug.
Could you please apply [the following fix](https://gist.github.com/emfomenk/0386c529c5df21ae308b00d16454c48e) and confirm it resolves your issue.

// It worked for me...

**Comment by nhkrishna** [comment]
Hi @emfomenk 

I am using MKLDNN V0.13. I will try with latest version with your fix and get back to you. 

-Hari

**Comment by emfomenk** [comment]
Thanks, looking forward to hearing from you!

**Comment by nhkrishna** [comment]
thanks @emfomenk ,  with your fix only resolved my issue.

**Comment by emfomenk** [comment]
Great, thanks @nhkrishna!

We will soon promote the fix to the master.
