### ISSUE TITLE
Does convolution backward descriptor really need a forward hint as parameter?

### ISSUE THREAD

**Issue by 4pao** [intel/mkl-dnn#132]
The need of hint is quite cumbersome and in fact this parameter seems never be active in convolution implementations. Besides, primitive_desc had no way to wrapper a nullptr_t.

So, is it possible just to remove it from interface (or add a new interface without a hint)?

**Comment by emfomenk** [comment]
Hi @4pao,

forward_hint is a standard way (interface) for all mkl-dnn backward primitives to verify they are compatible with the executed forward ones. At the moment this is crucial for batch-normalization, lrn, and pooling since different implementation may use different workspace layout (hence making impl-a be incompatible with impl-b). Even though backward convolutions do not depend on forward ones at the moment we cannot guarantee that would be always the case. In particular, for winograd implementation it is possible to reuse on backward pass some of the arrays computed on forward pass. That means we should be aware of what happened on that forward pass, and the only way to know is forward_hint...

**Comment by 4pao** [comment]
Hi  @emfomenk , thanks for the explanation.

There is a case that use convolution backward data to implement deconvolution layer. If hint is mandatory, I have to create a dummy forward primitive descriptor which make the implementation not that clean. So please consider the possibility that allow a empty hint.

**Comment by emfomenk** [comment]
Yeah... make sense, you are right.
Will think what we can do with that then.

**Comment by rsdubtso** [comment]
In my completely uneducated opinion a separate primitive would make more sense. It could use same implementation internally. Use of backward computations this way is bending the semantics quite a bit.

**Comment by emfomenk** [comment]
Absolutely agree that a separate primitive is required here.
But still there is something to think about, since de-convolution implementation would rely on the backward direct convolution (hence having the problem of asking the hint).

**Comment by kruus** [comment]
Having 2 primitive creators, static assert in the hintless one could remind that a non-null hint is required.  Some compilers can also warn about explicitly passing a nullptr hint (attribute `nonnull`).

Regardless of whether a second primitive creator is adopted, hints can still be given as `nullptr` right now to avoid the tedium of creating fwd descriptor just for hint. *But*, for robustness, I suppose checks on proper hint / private data workspace should be added to the various `init()` functions. "Is a required workspace non-null?", "Is a required workspace right size?", "Does workspace magic match for bkwd/fwd impls?", etc.

Thanks for the thread - I've been ignoring hint issues in last few days as I iterate over conv impls in benchdnn and now I can document why I can get away with lazy `nullptr` hints for now.

Resolving this issue should also include handling of hints for the primitive iterators.  One possibility is that the iterator should *gracefully, but possibly slowly* deal with absent/nullptr by *exceptionally* allowing workspaces to be auto-created and attempt to propagate to the next impl.  This sucks for speed, so should only be allowed for the iterator, but I'm guessing iteration over impls is would mainly for benchmarking or other non-critical use. Once a *best* implementation has been determined, there would be no additional workspace creation fee to be paid.

**Comment by vpirogov** [comment]
Recently added [deconvolution](http://intel.github.io/mkl-dnn/group__cpp__api__deconvolution.html) primitive addresses this issue.
