### ISSUE TITLE
ReLU have -0 result

### ISSUE THREAD

**Issue by tensor-tang** [intel/mkl-dnn#139]
First of all, I found that mkldnn use Leaky ReLU not exactly ReLU.
The explanation about Leay ReLU from google is:
> Leaky ReLUs are one attempt to fix the “dying ReLU” problem. Instead of the function being zero when x < 0, a leaky ReLU will instead have a small negative slope (of 0.01, or so).

Which means Leaky ReLU is:
```
f(x) = x,                     (x >= 0)
f(x) = x * negative_slope,    (x < 0)
```
However ReLU is `f(x)=max(0,x)`, they are not exactly the same, even if `negative_slope=0.0f`.

Because when  `x < 0`, `x * negative_slope` = `-0.0f` not `0.0f`.

You can only choose `negative_slope=-0.0f` to bypass it. But:
1.  it's very weird, right?
2.  when backward and inplace memory, should use `negative_slope=0.0f` back to avoid `-0.0f`.
3.  mkldnn use `return s > 0 ? s : static_cast<T>(s * alpha);` as [reference ](https://github.com/01org/mkl-dnn/blob/master/src/cpu/ref_eltwise.cpp#L33) code. It is not exactly the Leaky ReLU from **google**. Still can get `-0.0f` when `x == 0`. (BTW, I did not check the jit code about `x==0`, maybe it's the same as well).

Anyway, not matter what `negative_slope`, it seems not perfect to use Leaky ReLU as ReLU, right?
I thought the sign of value or gradient is every important in Machine Learning, who knows the layers will deal with the sign, even it's zero.

And the backward will get the same issue, -0.0f gradient.

Then I suggest it's better to implement absolutely ReLU method or implement Clipped ReLU, and make it replace Relu with clipping zero.
BTW the Clipped ReLU is very useful in NLP filed.

**Comment by vpirogov** [comment]
I would close this as there's no requirements at this point related to consistency of the activation functions behavior with respect to -0.0. Feel free to reopen if there are indications that existing MKL-DNN functionality leads to issues.
