### ISSUE TITLE
Does MKL-DNN also support LSTM as well?

### ISSUE THREAD

**Issue by HAIDJ** [intel/mkl-dnn#154]
Hi all,

I confirmed that MKL-DNN library provides significant performance improvement on various CNN algorithms. but I wonder if MKL-DNN also provides high performance on LSTM (or RNN). 

Actually, when I look at the [layer folder](https://github.com/intel/caffe/tree/master/src/caffe/layers) within intel-caffe, it seems that the mkldnn source code for LSTM does not exist.

In this situation, is there anything I'm missing about the LSTM implementation? 
If you are planning to implement an optimal version for LSTM in the future, please let me know. 

Thank you.

**Comment by tprimak** [comment]
Hi @HAIDJ !

Thank you for your interest in LSTM support in MKL-DNN. Yes, we have a plan to support LSTM.
Actually, we just started work in this direction. We'll let you know as soon as this functionality will be available.

**Comment by BenjaminJurke** [comment]
That would also be of extreme interest to me. Imagine LSTMs for advanced condition monitoring on embedded platforms!

**Comment by RadjaHachilif** [comment]
Hello,
I am also interested in LSTM support in MKL-DNN and I wanted to ask if you you could provide an implementation for LSTM or it is still work in progress ?

**Comment by igorsafo** [comment]
Hello @RadjaHachilif ,
MKL-DNN already has RNN,LSTM and GRU support. An example for LSTM cell can be found here: https://github.com/intel/mkl-dnn/blob/master/examples/simple_rnn.cpp#L255
