### ISSUE TITLE
Forgotten v0.12 postops support in ref_convolution

### ISSUE THREAD

**Issue by kruus** [intel/mkl-dnn#179]
### Description
ref and gemm convolution outputs differ when post-ops are used

Code [ref_convolution.cpp](https://github.com/01org/mkl-dnn/blob/master/src/cpu/ref_convolution.cpp) has forgotten to use `attr()->post_ops`, whereas `gemm_convolution.[hc]cpp` seems to support post_ops.

### Environment
Compare outputs with same inputs. I used benchdnn with --mode=AC "All+Correctness" on a [Fork](https://github.com/necla-ml/gen-dnn) to iterate over all available mkl-dnn impls

### Steps to reproduce
Compare gemm and reference convolution outputs with postops

### Actual behavior
They differ

### Expected behavior
Should be the same

**Comment by sotoflom** [comment]
Hi Kruus,

I'm wondering how you add or specify postops to ref_convolution? Currently, postops aren't supported in ref_convolution and any attempts to do so would fail during primitive creation.

**Comment by kruus** [comment]
I believe it’s basically a matter of filling in attribute fields (see mkldnn.h) and switching to the new ...create_v2  functions. Benchdnn has an example of how to do it in C++. In principle ref_convolution code can then grab the post_ops description when the convolution executes. Primitive creation succeeds. Just some execute functions don’t yet support this recent API addition.

**Comment by emfomenk** [comment]
Hi Erik,

To be honest we didn't plan to support post-ops for reference implementations at all.
The reason for that is:
- ref implementations are really slow
- for the _typical_ case reference implementations would not be picked up because we have more or less sufficient coverage with our jit/gemm implementations
- post-ops were mostly invented as performance optimization (e.g. instead of having `dst = dst + conv(src, wei)` one can not perform directly `dst += conv(src, wei)`

The problem is that not all the optimized implementations can support all possible post-ops. Which means in such cases would fallback to reference implementations. Which in turns means the user can forget about performance.
Hence we decided to not implement post-ops in ref, so that a user gets an error (`mkldnn_unimplemented`) instead of calling very slow implementation, which will make him decompose the primitive + post-op into a series of separate calls (which hopefully would be faster).

Do you think this is reasonable?

As @sotoflom noticed it is really strange you were able to catch the situation when primitive just ignores post-ops. This is either an existent or already fixed bug.

**Comment by kruus** [comment]
I think it is a reasonable strategy. Hopefully a list of allowed optimizations will be maintained.
So I'm fine if it is fixed by beefing up the various `init()` functions.  This is certainly more maintainable than bloating the ref impls all over the place for optimizations.

> As @sotoflom noticed it is really strange you were able to catch the situation when primitive just ignores post-ops. This is either an existent or already fixed bug.

I do not understand why it is strange, because catching wrong usage of post-ops should occur in `ref_convolution::init()`, and on trunk there is still no such check.  **You** might not see it because you are only running `mkldnn_primitive_desc_create_v2`, which is returned an OK impl (the first), and then ignoring the iterator.

Now, if you run the **iterator** over all impls, some may support post-ops, others might not.  So I think it must be the responsibility of `init()` to check attributes, and tell the iterator *"No!"*.  Trunk (and my) code doesn't seem to do so. 

Also, attributes can in principle be (wrongly?) attached to any primitive, so other primitives that don't support attributes should probably do so *might* also need to do so in their `init()` functions

---- 

I construct an attribute-aware iterator as (snip-snip)
```
    conv_iter_v2_t(const prb_t* p, mkldnn_convolution_desc_t cd,
        mkldnn_engine_t engine,
        const_mkldnn_primitive_desc_t hint_forward_primitive_desc=nullptr)
        : iter_(nullptr), iter_status_(mkldnn_success), n_(0U)
          , op_desc(cd, p->merge)
    {
        this->iter_status_ = op_desc.status();
        if (iter_status_ == mkldnn_success ){
            auto mkldnn_attr = create_mkldnn_attr(p->attr, p->oc, p->scales);
            iter_status_ = mkldnn_primitive_desc_iterator_create_v2(&iter_,
                    &cd, mkldnn_attr, engine, NULL);
            mkldnn_primitive_attr_destroy(mkldnn_attr);
        }
    }
```
Eventually, I will hit ref_convolution (because `init()` doesn't say *"No!"*) and I get wrong results, with no sign of badness.

**Comment by emfomenk** [comment]
>  So I think it must be the responsibility of init() to check attributes, and tell the iterator "No!". Trunk (and my) code doesn't seem to do so.

But that's exactly what happens. E.g. ref convolution [fwd](https://github.com/intel/mkl-dnn/blob/master/src/cpu/ref_convolution.hpp#L67), [bwd_d](https://github.com/intel/mkl-dnn/blob/master/src/cpu/ref_convolution.hpp#L136), [bwd_w](https://github.com/intel/mkl-dnn/blob/master/src/cpu/ref_convolution.hpp#L196). Those check should return `unimplemented` whenever ref convolution is asked to compute something with post-ops.

Looks like I missed something...

**Comment by kruus** [comment]
Yup. Likely all the ref_*.hpp init funcs should implement a check for *all-empty* attributes, as a default policy.

**Comment by emfomenk** [comment]
Yeah, my point is that that is exactly what happens now.
So I am still confused why you faced with the issue (even using `primitive_desc_iterator`). Once iterator tries to pick reference implementation the later should say it is not applicable because it has checks that attributes are empty.

**Comment by kruus** [comment]
Omg! **I was blind, but now I see!** `&& this->attr()->has_default_values()`, added by Manuel a long time ago, but missed during my upstream merges and *many* visual checks. Only *ref_sum* allows special attributes magic. Thanks for patiently setting me straight.

**Comment by emfomenk** [comment]
**You are very welcomed** :)
