### ISSUE TITLE
Can I backport Xbyak::Cpu::setCacheHierarchy into my original source with BSD-license?

### ISSUE THREAD

**Issue by herumi** [intel/mkl-dnn#186]
I have a question.
I found [a patch for xbyak_util.h](https://github.com/intel/mkl-dnn/commit/3543ea09a128d987f50cea3fc1cd9a79120027e1#diff-52cc181c6380b59bf9dcf004dd4b3f95).

Can I modify it a little and backport into [xbyak](https://github.com/herumi/xbyak/) under BSD-3 Clause?
Is it necessary to describe Apache License by Intel?

**Comment by rsdubtso** [comment]
Our plan was to upstream this change all along, but it fell through the cracks. Please give me a couple of day to sort this out.

**Comment by herumi** [comment]
Thank you for your quick reply.
I'll wait for your PR.

**Comment by mgouicem** [comment]
Hi @herumi, I just made the PR https://github.com/herumi/xbyak/pull/60

**Comment by herumi** [comment]
Thank you for your PR. I have merged it.
