### ISSUE TITLE
Build fails "../src/libmkldnn.so.0.12.0: undefined reference to `cblas_gemm_s8u8s32'"

### ISSUE THREAD

**Issue by parvizp** [intel/mkl-dnn#187]
### Description
I'm not able to build master (commit https://github.com/intel/mkl-dnn/commit/283c4a8c24b4e1dea05fbc7941594a7375babad1) on Ubuntu 14.04.

### Environment
Ubuntu 14.04 (Linux ubuntusystest 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

### Steps to reproduce
```$ git clone https://github.com/intel/mkl-dnn.git```
```$ cd mkl-dnn```
```$ cd scripts && ./prepare_mkl.sh && cd ..```
```$ mkdir -p build && cd build && cmake .. && make```

Dies with:

```Downloaded and unpacked Intel(R) MKL small libraries to /home/parviz/Git/mkl-dnn/external
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- Detecting Intel(R) MKL: trying mklml_intel
-- Intel(R) MKL: include /home/parviz/Git/mkl-dnn/external/mklml_lnx_2018.0.1.20171227/include
-- Intel(R) MKL: lib /home/parviz/Git/mkl-dnn/external/mklml_lnx_2017.0.3.20170424/lib/libmklml_intel.so
-- Intel(R) MKL: OpenMP lib /home/parviz/Git/mkl-dnn/external/mklml_lnx_2017.0.3.20170424/lib/libiomp5.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- VTune profiling environment is unset
-- Configuring done
-- Generating done
-- Build files have been written to: /home/parviz/Git/mkl-dnn/build
[ 37%] Built target mkldnn
[ 38%] Linking C executable simple-net-c
../src/libmkldnn.so.0.12.0: undefined reference to `cblas_gemm_s8u8s32'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/simple-net-c] Error 1
make[1]: *** [examples/CMakeFiles/simple-net-c.dir/all] Error 2
make: *** [all] Error 2```

**Comment by rsdubtso** [comment]
Hi. Thanks for the report. How did you set up the MKL environment? Seems like CMAKE detects headers from one mklml version (2018.0.1) while libraries and openmp from another (2017.0.3).  Can you please remove all the stuff from the mkl-dnn/external and run cmake again?

**Comment by parvizp** [comment]
Oh your right, that had an old version. Doing a fresh clone fixed that problem.
Thanks!
