### ISSUE TITLE
Do you have a option like WITH_TEST=OFF?

### ISSUE THREAD

**Issue by luotao1** [intel/mkl-dnn#190]
When I use `ExternalProject_Add` to build and install MKLDNN library, I find that all test codes of MKLDNN will be compiled at the same time. In order to decrease the third-party compiler time, do you have a option like `WITH_TEST=OFF`? Thus, I can not build the test codes.

Thanks very much!

**Comment by emfomenk** [comment]
No, we haven't considered that case.
Your PR is welcome :)
... or I will take a look on that soon.

**Comment by emfomenk** [comment]
You can now use `-DWITH_TEST=OFF -DWITH_EXAMPLE=OFF` to turn tests and examples off.

**Comment by luotao1** [comment]
Thanks very much!
