### ISSUE TITLE
question about ur_w in u8 conv kernel

### ISSUE THREAD

**Issue by tensor-tang** [intel/mkl-dnn#194]
From the code I can see the `ur_w` is initial here 
https://github.com/intel/mkl-dnn/blob/master/src/cpu/jit_avx512_core_u8s8s32x_conv_kernel.cpp#L494-L502

But in [Line 524](https://github.com/intel/mkl-dnn/blob/master/src/cpu/jit_avx512_core_u8s8s32x_conv_kernel.cpp#L524), this `ur_w` is overwrite.

Which one is your purpose? Is the former one useless?

Thanks very much~

**Comment by igorsafo** [comment]
Hi,

Good catch! The first one is useless.
Will promote the fix soon.

**Comment by tensor-tang** [comment]
Thanks~

**Comment by vpirogov** [comment]
Fixed in 894331ae2740561601aacaf18ae9d065803c7a8e
