### ISSUE TITLE
Conflict c++ concepts declaration and mkldnn

### ISSUE THREAD

**Issue by renevs** [intel/mkl-dnn#196]
### Description
Conflict c++ concepts declaration and mkldnn

When I execute the intel example "simple_net.cpp" including a specific concepts C++ declaration, before the code, as below, I receive the message "status: 3 message: could not submit primitives to a stream".
I've investigated the problem and I realized that the line:
_net_weights.push_back( reorder(user_weights_memory, conv1_weights_memory));_ , only in this situation, call the private constructor: 
_handle(const handle &&) {}_ , from _handle_ class in mkldnn.hpp. 

I think, in this specific case, It should be:
handle(const handle &&other):_data(other._data) {}

//***********************************************************************************
// Code that causes error - start
//***********************************************************************************
template <typename Src, typename Dst>
concept bool VectorSource()
{
  return true;
}
template <typename T = double >
class MeuTVector
{
    template < VectorSource<MeuTVector> X>
    MeuTVector operator=(X const& x) const
    {
      assert( count(*this) == count(x) );
      assign_to(*this, x);
      return *this;
    }
};
//********************************************************************
// Code that causes error - end
//*******************************************************************
// simple_net.cpp code starts here...

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave 
differently on depending on the compiler and build environment. Include 
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`)
Architecture:                x86_64
CPU operational mode: 32-bit, 64-bit
CPU(s):                     4
On-line CPU(s) list:        0-3
Thread(s) per core        2
Cores(s) per socket:      2
Sockets(s):                 1
NUMA Nodes:              1
supplier ID:           GenuineIntel
CPU Family:             6
Model:                     78
Model name:                 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
Step:                       3
Virtualization:              VT-x
NUMA node0 CPU(s):          0-3
Flags:                      fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti retpoline intel_pt rsb_ctxsw spec_ctrl tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp

* OS version (`uname -a`)
Linux 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`gcc --version`)
g++ (GCC) 7.2.0

* MKLROOT value (`echo MKLROOT=$MKLROOT`)
/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl

* CMake version (`cmake --version`)
GNU Make 4.1

* CMake output log
18:41:28: Starting: "/usr/bin/make" 
g++ -c -pipe -std=c++17 -mavx2 -mfma -mfpmath=sse -msse2 -fconcepts -frounding-math -fsignaling-nans -fext-numeric-literals -m64 -I/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/include -g -Wall -W -fPIC -DIME_WITH_MKL -DMKL_ILP64 -DQT_QML_DEBUG -I../mkl-dnn-teste -I. -I/home/rene/dev -I../../../../usp -I/home/rene/apps/Qt/5.10.0/gcc_64/mkspecs/linux-g++ -o simple_net.o ../mkl-dnn-teste/simple_net.cpp
../mkl-dnn-teste/simple_net.cpp: Na função ‘int main(int, char**)’:
../mkl-dnn-teste/simple_net.cpp:850:14: aviso: unused parameter ‘argc’ [-Wunused-parameter]
 int main(int argc, char **argv) {
              ^~~~
../mkl-dnn-teste/simple_net.cpp:850:27: aviso: unused parameter ‘argv’ [-Wunused-parameter]
 int main(int argc, char **argv) {
                           ^~~~
g++  -o mkl-dnn-teste simple_net.o   -lquadmath -lmpfr -lgmp -l:gtest/libgtest.a -Wl,--start-group /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_intel_ilp64.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_intel_thread.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a -Wl,--end-group -liomp5 -lpthread -lm -ldl -lmkldnn -L/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/../compiler/lib/intel64 

### Steps to reproduce
1) Include the code above in simple_net.cpp
2) run the code.
or only execute the attached source.
[simple_net.cpp.txt](https://github.com/intel/mkl-dnn/files/1804725/simple_net.cpp.txt)

### Actual behavior
"status: 3 message: could not submit primitives to a stream"

### Expected behavior
show the message: Use time XXX

**Comment by emfomenk** [comment]
Thanks for the bug and investigation!

The behavior of g++ is very strange.
I put a small standalone [reproducer](https://gist.github.com/emfomenk/c6d21cc85e9904d44f2a49bf98b0c02f).

Seems like it allows accessing the private move constructor even though it should not.
Anyway we should just `delete` move ctor & assignment operator from handle class.
I will push the fix soon.

Thanks again!
