### ISSUE TITLE
Low performance of BatchNorm with NCHW as input layout

### ISSUE THREAD

**Issue by airofjune** [intel/mkl-dnn#197]
1
When using default NCHW as input layout, and recreate primitive for each iteration, BatchNorm OP's peformance seems to be poor, that is, up to 250ms to pass a single BN forward OP when running ResNet50 on BDW.  
Is this normal?

2
Besides, when constructing backward OP for BatchNorm, is there any restriction for memory structure
of input(data) and grad_output? The documentation offers no clues.

**Comment by vpirogov** [comment]
Current implementation of batchnorm has optimized path for blocked formats as in most situations it follows convolution and will naturally receive a blocked layout as input. For plain layouts like NCHW the library dispatches reference implementation that is not particularly optimized. There are situations that optimized implementation for NCHW is necessary and we have optimizations for this format planned.

For the the second question I'm summoning @emfomenk or @igorsafo to this thread.

**Comment by emfomenk** [comment]
Hi @airofjune,

> Besides, when constructing backward OP for BatchNorm, is there any restriction for memory structure
of input(data) and grad_output? The documentation offers no clues.

There is no restrictions from API perspective (*maybe there should be though...*).
However, from performance perspective it is highly recommended to have the same data layouts for `src/dst` and `diff_src/diff_dst`. That's also true for the other non-convolution primitives: eltwise, pooling, lrn, etc... Same layouts allow traversing memory in the same fashion (usually linearly) -- that improves performance. Also we typically don't have optimized versions for cases with mismatched layouts.

**Comment by airofjune** [comment]
Thanks vpirogov and emfomenk  for the information!

**Comment by emfomenk** [comment]
Closed by 3de46c50.
