### ISSUE TITLE
support for filter dilation? 

### ISSUE THREAD

**Issue by tonywang1990** [intel/mkl-dnn#204]
### Description
Is there currently support for filter dilation in convolution? If not, is there any plan to add this?

**Comment by emfomenk** [comment]
Hi, 

Yeah, we do have dilation support.
E.g. see [here](https://intel.github.io/mkl-dnn/group__c__api__convolution.html#gacda0f1915c933457f2396fe9d221bc6b).
Please note, that `dilates = {0, 0, .., 0}`means regular convolution (some frameworks use `1` for that).

**Comment by tonywang1990** [comment]
Thanks, what kind of dilation is it? Is it atrous convolution?

**Comment by emfomenk** [comment]
According to this [site](https://towardsdatascience.com/types-of-convolutions-in-deep-learning-717013397f4d) -- yes, it is atrous convolution.
Personally I have heard this term for the first time :)

**Comment by tonywang1990** [comment]
What about transposed convolution (deconvolution), is it supported?

**Comment by emfomenk** [comment]
Deconvolution itself is supported (we just recently introduce it via 6290597).
It doesn't support dilation though.
