### ISSUE TITLE
Is there any performance difference between submitting all primitives at once into the stream and submitting each primitive individually into the stream ? 

### ISSUE THREAD

**Issue by nhkrishna** [intel/mkl-dnn#210]
I've created Alexnet network using two approaches. 

1. For each layer,  i've created its corresponding primitive and submitted into the stream for execution. (i.e., after creating convolution primitive, it is submitted into stream and then ReLU primitive is submitted into the stream and so on)

2. For each layer,  i've created its corresponding primitive and push back to the vector(`std::vector<mkldnn::primitive> net`). In this way primitives of all layers are pushed into the vector(`net`). Finally this vector is submitted at once to the stream for execution.  

Can i expect any performance improvement in second approach?

**Comment by vpirogov** [comment]
There's no difference in performance between these approaches currently. The stream was introduced to accomodate asynchronous execution necessary for programming some devices.

**Comment by nhkrishna** [comment]
thanks for the information @vpirogov
