### ISSUE TITLE
API to set num_of_threads?

### ISSUE THREAD

**Issue by tonywang1990** [intel/mkl-dnn#211]
### Description
How do I set the number of threads in the code?

**Comment by vpirogov** [comment]
Intel MKL-DNN relies on OpenMP for threading. You can use omp_set_num_threads function ([iomp5](https://software.intel.com/en-us/mkl-linux-developer-guide-changing-the-number-of-openmp-threads-at-run-time), [gomp](https://gcc.gnu.org/onlinedocs/libgomp/omp_005fset_005fnum_005fthreads.html)) that is a part of OpenMP standard to change the number of threads MKL-DNN will use.

**Comment by tonywang1990** [comment]
Is there a way to set local threads in openmp like mkl_set_num_of_threads_local() in https://software.intel.com/en-us/mkl-developer-reference-fortran-mkl-set-num-threads-local?

**Comment by emfomenk** [comment]
MKL-DNN doesn't have any special threading control functions. But you can still probably use `omp_set_num_threads()` in nested configuration as discussed [here](https://stackoverflow.com/questions/33632071/number-of-threads-within-an-omp-section).

If MKL-DNN primitives are called from different non-openmp threads (e.g. high level parallelization happens with pthreads) there is no way to control _local_ threading in MKL-DNN right now.
