### ISSUE TITLE
Is there any Conda or Pip package for MKL-DNN

### ISSUE THREAD

**Issue by gautamkmr** [intel/mkl-dnn#212]
### Description
Is there any available Conda or PIP package for MKL-DNN like how we have for MKL.

**Comment by vpirogov** [comment]
There's a [conda package](https://anaconda.org/intel/mkl-dnn) available. I'm not aware of a pip package.

**Comment by cpuhrsch** [comment]
@vpirogov - Now with the release of v0.14 we could benefit from an update to that package, since it's easier for developers to install. Could this be pushed at this point?

**Comment by vpirogov** [comment]
Thanks for pointing out that the package got stale! Let me see what I can do there.

**Comment by vpirogov** [comment]
[Conda package for v0.14](https://anaconda.org/intel/mkl-dnn/files) is published.
