### ISSUE TITLE
examples/simple_net_int8.cpp not working

### ISSUE THREAD

**Issue by CDLuminate** [intel/mkl-dnn#214]
Installed the MKL-DNN debian package, and encountered an error when trying to compile an example:

```
~/p/m/m/examples ❯❯❯ apt list libmkldnn-dev
Listing... Done
libmkldnn-dev/now 0.13~20180406-ga5f6077-1 amd64 [installed,local]
~/p/m/m/examples ❯❯❯ g++ simple_net_int8.cpp -lmkldnn
~/p/m/m/examples ❯❯❯ ./a.out 
status: 5
message: could not create a convolution forward primitive descriptor
```

The other examples are fine.

**Comment by emfomenk** [comment]
Hi @CDLuminate,

What is the hardware?

Int8 requires the CPU with `avx512-bw` support, e.g. Skylake server.
For other systems there is a fallback code based on Intel MKL (or Intel MKL-ML binary blob), but if you build Intel MKL-DNN as a standalone library then this fallback is unavailable.

*We should probably adjust the example to report more meaningful error message in case of hardware incompatibility...*

**Comment by CDLuminate** [comment]
@emfomenk My CPU is 7440HQ, which has no AVX512-bw as far as I know. The library was built standalone without MKL or MKL-ML,so I guess the fallback is unavailable.
So this is a issue about a more meaningful error report.
