### ISSUE TITLE
MKL DNN Direct

### ISSUE THREAD

**Issue by dharmisha** [intel/mkl-dnn#219]
does MKL-DNN invoke GEMM as defined in BLAS level 3? Does it perform convolution using SGEMM?

**Comment by vpirogov** [comment]
Intel MKL-DNN uses direct algorithm or Winograd algorithm to compute most of the convolutions. There are certain scenarios (for example when the number of output channels is not a multiple of SIMD width) where the library will use explicit GEMM-based algorithm. In these cases MKL-DNN has two options depending on how the library was built
1. Use internal [ JIT GEMM](https://github.com/intel/mkl-dnn/blob/master/src/cpu/jit_avx512_common_gemm_f32.cpp) implementation.
2. Use SGEMM function from Intel MKL through BLAS level 3 API. This will happen only if you built MKL-DNN with Intel MKL or [a binary blob](https://github.com/intel/mkl-dnn/releases/download/v0.13/mklml_lnx_2018.0.2.20180127.tgz) provided in this repository.

**Comment by vpirogov** [comment]
Here's a pro tip. You can see what algorithm (or algorithms) were used in your application if you run it with `MKLDNN_VERBOSE=1`. See [verbose mode documentation for the details](http://intel.github.io/mkl-dnn/perf_profile.html).
