### ISSUE TITLE
memory managment

### ISSUE THREAD

**Issue by tonywang1990** [intel/mkl-dnn#221]
Do I need to explicitly free the memory created by calling memory() ?

**Comment by emfomenk** [comment]
Hi,

If you use **C++ API** and create memory just by memory primitive_descriptor, than MKL-DNN will allocate the memory and you should not worry about its deallocation -- MKL-DNN will take care of it. If you create memory via `memory(memory_primitive_desc, void *handle)`, then it is your responsibility to clean-up the handle.
**C API** doesn't do allocation/deallocation, so you have to use manage the raw memory your self, and set it via `mkldnn_memory_set_data_handle()`.
