### ISSUE TITLE
mkldnn support user-defined or custom operation primitive?

### ISSUE THREAD

**Issue by kobe2000** [intel/mkl-dnn#225]
Hi,
  Now I can split the stream into pieces, and do some operation among them, I wonder if there's more elegant way to do so.
  Second question is: is there scale/shift operation primitive that can have different alpha(scale)/beta(shift) values per channel.
  Thanks

**Comment by emfomenk** [comment]
Hi,

> Now I can split the stream into pieces, and do some operation among them, I wonder if there's more elegant way to do so.

This is perfectly fine way to do so. Currently streams are mostly just stubs, no matter what you use `lazy` or `eager` stream. You can even create/run one stream per primitive. That should be also perfectly fine.

> Second question is: is there scale/shift operation primitive that can have different alpha(scale)/beta(shift) values per channel.

There is no dedicated primitive for that. But you can use batch normalization in inference mode to simulate that. So either use batch normalization with scale and shift parameters (hence `mean = 0, varience = 1, eps = 0`) or do not use scale and shift, but choose appropriate `mean` and `variance`.

**Comment by kobe2000** [comment]
It is clear now, Thank you!
