### ISSUE TITLE
convolution_relu VS convolution+Eltwise(ReLU) VS convolution with post_op(Eltwise/ReLU)

### ISSUE THREAD

**Issue by kobe2000** [intel/mkl-dnn#226]
Hi,
  If I want to use mkldnn to do a convolution with ReLU following, there are three ways as the title. My question is what are differences among them, which is the best.
  Thanks

**Comment by vpirogov** [comment]
The best way to implement convolution with ReLU is using the `post_ops` API. This allows to fuse ReLU computation with convolution effectively making ReLU computation free. The first method, `convolution_relu` is essentially the same and was replaced by new `post_ops` API, so it's now deprecated.

**Comment by kobe2000** [comment]
Now I see, thank you!
