### ISSUE TITLE
example with transposed convolutions

### ISSUE THREAD

**Issue by andreistirb** [intel/mkl-dnn#228]
Hello, 

I want to develop a network that uses transposed convolutions but it seems that it does not work. 
Firstly, I don't understand why there are two padding parameters (padding_l, padding_r) that are of two dimensions.
I tried to follow the example from simple_net.cpp, like a convolution, but it does not work the same, I guess. 

I have these dimensions:
   ```
 memory::dims transposed_conv1_src_tz = { batch, 256, 4, 4 }; //format {batch_size, channels, height, width}
    memory::dims transposed_conv1_weights_tz = { 128, 256, 5, 5 }; //format {output_channels, input_channels, height, width}
    memory::dims transposed_conv1_bias_tz = { 128 }; //format {channels}
    memory::dims transposed_conv1_dst_tz = { batch, 128, 8, 8 }; //format {batch_size, channels, height, width}
    memory::dims transposed_conv_strides = { 2, 2 };
    memory::dims transposed_conv_padding_left = { 1, 2 };
    memory::dims transposed_conv_padding_right = { 2, 1};
```

I am creating instances of memory objects for src, dst, weights and bias like this: 
```
auto user_src_memory
            = memory({ { { input_dim }, memory::data_type::f32,
                               memory::format::nchw },
                            engine },
                    input);
```

the deconv_forward desc: 
```
auto transposed_conv_desc = deconvolution_forward::desc(
			prop_kind::forward_inference, 
			deconvolution_direct, 
			user_src_memory.get_primitive_desc().desc(),
			user_weights_memory.get_primitive_desc().desc(),
			user_bias_memory.get_primitive_desc().desc(),
			user_dst_memory.get_primitive_desc().desc(),
			transposed_conv_strides,
			transposed_conv_padding_left,
			transposed_conv_padding_right,
			padding_kind::zero);
```

the primitive descriptor that takes arguments transposed_conv_desc and engine, push_back inside the network the deconv operation but the results are only garbage values like 6.46806e+30 -1.94593e+32...

Am I doing something wrong? Can you post an example of a working transposed convolution?

**Comment by irinasok** [comment]
Hello,
Deconvolution primitive is very similar to convolution and has exactly the same model of usage. The only difference is that input and output are handled in the backward fashion compared with a standard convolution. Both, convolution and deconvolution decsriptor have mkldnn_dims_t padding_l[2] and  mkldnn_dims_t padding_r[2] fields which set left padding for height/width and right padding for height/width. So for 2D case it's:

- padding[0][0] -- is a top padding (aka 'left' padding for the height)
- padding[0][1] -- is a left padding (aka 'left' padding for the width)
- padding[1][0] -- is a bottom padding (aka 'right' padding for the height)
- padding[1][1] -- is a right padding (aka 'right' padding for the width)

Regarding your example, it looks fine to me, I tried to reproduce garbage in result you mentioned but it passed fine. Maybe I miss something, here is the code I run:
`  
  
    auto cpu_engine = engine(engine::cpu, 0);

    /* Create a vector primitive to hold the network. */
    std::vector<primitive> net;

    const int batch = 1;

    memory::dims transposed_conv1_src_tz = { batch, 256, 4, 4 };
    memory::dims transposed_conv1_weights_tz = { 128, 256, 5, 5 };
    memory::dims transposed_conv1_bias_tz = { 128 };
    memory::dims transposed_conv1_dst_tz = { batch, 128, 8, 8 };
    memory::dims transposed_conv_strides = { 2, 2 };
    memory::dims transposed_conv_padding_left = { 1, 2 };
    memory::dims transposed_conv_padding_right = { 2, 1 };

    /* Allocate input and output buffers for user data */
    std::vector<float> user_src(batch * 256 * 4 * 4);
    std::vector<float> user_dst(batch * 128 * 8 * 8);

    /* initializing non-zero values for src */
    for (size_t i = 0; i < user_src.size(); ++i)
        user_src[i] = sinf((float)i);

    /* Allocate and fill buffers for weights and bias */
    std::vector<float> transposed_conv1_weights(std::accumulate(
            transposed_conv1_weights_tz.begin(), transposed_conv1_weights_tz.end(), 1,
            std::multiplies<uint32_t>()));

    std::vector<float> transposed_conv1_bias(std::accumulate(transposed_conv1_bias_tz.begin(),
            transposed_conv1_bias_tz.end(), 1, std::multiplies<uint32_t>()));

    /* initializing non-zero values for weight */
    for (size_t i = 0; i < transposed_conv1_weights.size(); ++i)
        transposed_conv1_weights[i] = sinf((float)i);

    /* initializing non-zero values for bias */
    for (size_t i = 0; i < transposed_conv1_bias.size(); ++i)
        transposed_conv1_bias[i] = sinf((float)i);

    /* create memory for user data */
    auto user_src_memory
            = memory({ { { transposed_conv1_src_tz }, memory::data_type::f32,
                               memory::format::nchw },
                             cpu_engine },
                    user_src.data());
    auto user_weights_memory
            = memory({ { { transposed_conv1_weights_tz }, memory::data_type::f32,
                               memory::format::oihw },
                             cpu_engine },
                    transposed_conv1_weights.data());
    auto user_bias_memory = memory(
            { { { transposed_conv1_bias_tz }, memory::data_type::f32, memory::format::x },
                    cpu_engine },
            transposed_conv1_bias.data());

    auto user_dst_memory
            = memory({ { { transposed_conv1_dst_tz }, memory::data_type::f32,
                               memory::format::nchw },
                             cpu_engine },
                    user_dst.data());

    /* create a deconvolution */
    auto transposed_conv_desc = deconvolution_forward::desc(
            prop_kind::forward_inference,
            deconvolution_direct,
            user_src_memory.get_primitive_desc().desc(),
            user_weights_memory.get_primitive_desc().desc(),
            user_bias_memory.get_primitive_desc().desc(),
            user_dst_memory.get_primitive_desc().desc(),
            transposed_conv_strides,
            transposed_conv_padding_left,
            transposed_conv_padding_right,
            padding_kind::zero);

    auto transposed_conv_prim_desc
            = deconvolution_forward::primitive_desc(transposed_conv_desc, cpu_engine);

    /* create deconvolution primitive and add it to net */
    net.push_back(deconvolution_forward(transposed_conv_prim_desc, user_src_memory,
            user_weights_memory, user_bias_memory,
            user_dst_memory));

    stream(stream::kind::eager).submit(net_weights).wait();
    for (int j = 0; j < times; ++j) {
        stream(stream::kind::eager).submit(net).wait();
    }

`

**Comment by vpirogov** [comment]
Closing as the question was addressed. @andreistirb, feel free to reopen if you have any further questions.
