### ISSUE TITLE
Demo simple-net-cpp failed when creating user_weights_memory in convolution.

### ISSUE THREAD

**Issue by VictorYXL** [intel/mkl-dnn#244]
When running the demo simple-net-cpp, the following block will failed with the message "could not initialize a memory descriptor"
auto user_weights_memory
            = memory({ { { conv1_weights_tz }, memory::data_type::f32,
                               memory::format::oihw },
                             cpu_engine },
                    conv1_weights.data());

-----------------------------------------------------------------------------

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave 
differently on depending on the compiler and build environment. Include 
the following information to help reproduce the issue:
* CPU: Intel(R) Core(TM) i7-4790 3.60GHz
* OS: Windows 10 Enterprise
* Compiler: Visual Studio 2017 (v141)
* MKLROOT: mkl-dnn-0.11
* MKL_ENABLE_INSTRUCTIONS: AVX2
* CMake: cmake version 3.9.2
* CMake output log
cmake -G "Visual Studio 15 2017 Win64" ..
-- The C compiler identification is MSVC 19.14.26429.4
-- The CXX compiler identification is MSVC 19.14.26429.4
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- Detecting Intel(R) MKL: trying mklml_intel
-- Detecting Intel(R) MKL: trying mklml
-- Intel(R) MKL: include D:/BenchmarkTool/libs/mkl-dnn-test/external/mklml_win_2018.0.2.20180127/include
-- Intel(R) MKL: lib D:/BenchmarkTool/libs/mkl-dnn-test/external/mklml_win_2018.0.2.20180127/lib/mklml.lib
-- Intel(R) MKL: OpenMP lib D:/BenchmarkTool/libs/mkl-dnn-test/external/mklml_win_2018.0.2.20180127/lib/libiomp5md.lib
-- Intel(R) MKL: dll D:/BenchmarkTool/libs/mkl-dnn-test/external/mklml_win_2018.0.2.20180127/lib/mklml.dll
-- Intel(R) MKL: OpenMP dll D:/BenchmarkTool/libs/mkl-dnn-test/external/mklml_win_2018.0.2.20180127/lib/libiomp5md.dll
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- VTune profiling environment is unset
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: D:/BenchmarkTool/libs/mkl-dnn-test/build

### Steps to reproduce
Create sln file by cmake
Visual Studio 15 2017 Win64
Open the sln file with Visual Studio 2017
Build the whole solution and run the simple-net-cpp demo in debug mode

### Actual behavior
Failed in line 67.
 auto user_weights_memory
            = memory({ { { conv1_weights_tz }, memory::data_type::f32,
                               memory::format::oihw },
                             cpu_engine },
                    conv1_weights.data());
Debug in and failed in mkldnn_memory_desc_init with message "could not initialize a memory descriptor"

### Expected behavior
Create the user_weights_memory and run the convolution layer smoothly.
The demo can run well on older commit, such as 
commit b1dd83c085a12ef8dae0ed4e352e743f433eef55 
Author: Gouicem, Mourad <mourad.gouicem@intel.com>
Date:   Mon Mar 19 15:49:55 2018 -0700

    example: rnn: fixing an index issue in the attention scoring

**Comment by densamoilov** [comment]
Hi @VictorYXL 

We can't reproduce the issue on our side. To reproduce it we use the latest version of mkl-dnn (0.14) and Visual Studio 2017. The build environment was configured based on information you provided. 
Do you still see the behavior you described with mkl-dnn-0.14?

**Comment by emfomenk** [comment]
Will close due to lack of activity.
Please feel free to reopen.

**Comment by mir-of** [comment]
I had encountered the same problem, then I found that it was due to multiple openmp library in my LD_LIBRARY_PATH. So I just have done `export MKLDNNROOT=/path/to/mkldnn/installed` , `export LD_LIBRARY_PATH=${MKLDNNROOT}/lib`  solved my problem.
