### ISSUE TITLE
Does MKLDNN has TBB support

### ISSUE THREAD

**Issue by mingfeima** [intel/mkl-dnn#249]
Can MKLDNN be compiled with [TBB](https://www.threadingbuildingblocks.org/) instead of OpenMP?

**Comment by emfomenk** [comment]
Hi @mingfeima,

Currently Intel MKL-DNN cannot be built with TBB. But we are looking into supporting it. No ETA though.

Could you explain why you need TBB and what the use case is? Is it inference only or both inference and training?

**Comment by mingfeima** [comment]
@emfomenk TBB is recently introduced into PyTorch as facebook developers consider

- TBB is a more modern interface and has better interaction with C++11
- mkl-blas with TBB has better performance than OpenMP, they quote [this](https://software.intel.com/en-us/articles/using-intel-mkl-and-intel-tbb-in-the-same-application)
- TBB has msvc support while OpenMP4.0 doesn't so TBB is better for Windows support

however, this is causing great performance drop for CPU, see issue [#7903](https://github.com/pytorch/pytorch/issues/7903), as a result of resource competition.

Is it possible for TBB and OpenMP to operate peacefully under one process?

**Comment by emfomenk** [comment]
Alas OpenMP RT is not aware of TBB run in parallel. 

If OpenMP parallel regions are executed not in parallel with TBB threads (i.e. if you have linear model, and Intel MKL-DNN primitives use OpenMP, while all non-MKL-DNN primitives use TBB) -- you should be fine.

There are some techniques how you can make those two runtimes co-exist. In particular it is highly recommended to set `KMP_BLOCKTIME` environment variable to a small value (0, 1, or ~20). See this [doc](https://www.threadingbuildingblocks.org/docs/help/reference/appendices/known_issues/interoperability.html).

**Comment by mingfeima** [comment]
@emfomenk thanks so much on the update, i will try that out.

**Comment by vpirogov** [comment]
There were bits of useful information posted in Pytorch thread. Copying these here for interested people to find.

The question of OpenMP and TBB threading composability is discussed in details in [Scipy proceedings](https://github.com/anton-malakhov/scipy_proceedings/blob/2018-composability/papers/anton_malakhov/composability.rst). The core of recommendation for peaceful coexistence between runtimes suggested in the article is the following:
```
export KMP_BLOCKTIME=1
export KMP_COMPOSABILITY=mode=exclusive
```

**Comment by suhang1994** [comment]
@emfomenk 
https://software.intel.com/en-us/articles/using-intel-mkl-and-intel-tbb-in-the-same-application

why can they compile mkl with tbb
