### ISSUE TITLE
support nc dataformat for lrn

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#251]
Hi,

Incase of mnist which has fc->lrn->fc we are unable to pass the fc output memory primitive of data format nc to lrn , since the lrn does not have nc implementation it is failing during the setup.

It would be helpful if you could add the nc support for lrn. As of now we have implemented a workaround checking if the format is nc then creating a new primitive with nchw and executing the lrn layer in nchw format.

Thanks

**Comment by shelleygoel** [comment]
It seems a really specific use case. Is it possible for you to create the fc primitive with output format 'nchw'?  then you wouldn't need to create new primitive with nchw,
