### ISSUE TITLE
Is standard c++(-std=c++ or /STD:c++11) only needed to run mkldnn  on both windows and linux? Or higher versions 14,17 also supported?

### ISSUE THREAD

**Issue by tensor-go** [intel/mkl-dnn#253]
Hi,

I'm trying to run  simple_net.cpp example on Windows from command line using visual studio 15. I'm   not using any /STD:c++11 compiler flag. But Visual studio default takes c++14 as  c standard, example working fine. Means does mkldnn supports c++11 and it's higher versions?

**Comment by emfomenk** [comment]
Hi @tensor-go,

The minimum required version of C++ standard is C++11. So it is perfectly fine if you use C++14 or above.

**Comment by tensor-go** [comment]
Thanks @emfomenk
