### ISSUE TITLE
Feature request: Element-wise multiplication

### ISSUE THREAD

**Issue by okdshin** [intel/mkl-dnn#255]
Now I try to implement [DenseNet](https://arxiv.org/abs/1608.06993) by using MKLDNN. DenseNet requires element-wise multiplication. MKL has it, but I would like to use only MKLDNN for its optimization.

**Comment by vpirogov** [comment]
@okdshin, thanks for clarifications. Intel MKL-DNN is design as a performance library and we don't have an ambition to run full topologies. For the task of running topologies imported from the frameworks (including using ONNX format) we are developing tools like[ OpenVINO Toolkit](https://software.intel.com/en-us/openvino-toolkit) and [Intel nGraph](https://github.com/NervanaSystems/ngraph).

On the Intel MKL-DNN side we are still on the fence about implementing Numpy-like tensor algebra, as currently it's not a performance bottleneck in the wide range of usage scenarios.

**Comment by okdshin** [comment]
@vpirogov, I see. I understood current MKL-DNN side's condition. I would like to use Numpy-like tensor algebra on MKL-DNN. Thanks you.

**Comment by usamec** [comment]
I would also like to implement things like gated linear units. This also required elementwise multiplication. 
What is recommended to do here? Only do convolutions via MKLDNN and then do simple elementwise operation outside using custom code?

**Comment by vpirogov** [comment]
@usamec, I'm not familiar with gated linear units. Could you please point me to how eltwise is used there?

In general operations like elementwise multiplication are expensive and should be fused with compute-bound operations like convolution or matrix-matrix multiplication in the implementation of the model. An example of this may be batch normalization, where Intel MKL-DNN provides scale and shift support. In ONNX these are implemented as separate mul and add, making whole operation at least 3x slower than necessary.

**Comment by usamec** [comment]
@vpirogov they are used for example here: https://arxiv.org/pdf/1612.08083.pdf
Or here: https://openreview.net/forum?id=SkVhlh09tX

**Comment by vpirogov** [comment]
Thanks. It seems like there's no way to avoid eltwise multiplicaiton in this model. At this point the only option is to implement this operation outside of Intel MKL-DNN. We will definitely be open to a contributions along these lines.

**Comment by WilliamTambellini** [comment]
Hello, I also confirm the need on my side for element wise multiplication. Implementing outside mkldnn would probably be a little hacky and/or source of bugs and/or source of slowdown.  
I suppose that  jit_uni_eltwise.cpp, ref_eltwise.cpp
are just about unary expression whereas we would need here a binary element wise a*b (jit_bi_eltwise.h/cpp ?).

To move forward step by step, if possible, could anyone form the mkldnn team just list the different changes that would be needed for that op to be added to mkldnn ?
Kind

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

We are currently working on binary multiplication and addition operation. We also think to add the broadcast support. We need to double check few things with the frameworks team and then we will be able to share the *final* API for this op. Hopefully this is a matter of 2-3 days.
I hope the initial version of the working primitive will be available in two-three weeks from now.

**Comment by WilliamTambellini** [comment]
ok @emfomenk,  thank you.

**Comment by blueberry** [comment]
@emfomenk Any update regarding the work on eltwise multiplication you mentioned?

**Comment by blueberry** [comment]
Thanks @vpirogov Does that include the broadcasting support that you've mentioned or just the Hadamard product?

**Comment by vpirogov** [comment]
The functionality is implemented in 2e27c61d8b2c5dd01339f86ecbb7ca8332a7c0a5. Documentation is promoted to [Github pages](http://intel.github.io/mkl-dnn/dev_guide_binary.html).
