### ISSUE TITLE
Cmake's MSVC target doesn't define USE_MKL or expose an option

### ISSUE THREAD

**Issue by TechnikEmpire** [intel/mkl-dnn#258]
Here's the place for your question, suggestion, a feature request or brief
description of the problem. If you are submitting a defect report please fill
the sections below. For everything else feel free to remove everything below
the line.

-----------------------------------------------------------------------------

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave 
differently on depending on the compiler and build environment. Include 
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`)
* OS version (`uname -a`)
* Compiler version (`gcc --version`)
* MKLROOT value (`echo MKLROOT=$MKLROOT`)
* CMake version (`cmake --version`)
* CMake output log

### Steps to reproduce
Use cmake to generate visual studio projects.

### Actual behavior
`USE_MKL` is not defined.

### Expected behavior
`USE_MKL` should be defined or at least there should be an option.

**Comment by emfomenk** [comment]
Hi @TechnikEmpire,

Could you please elaborate on the issue?
Cmake should check whether Intel MKL is available and if so it defines `USE_MKL` by itself. See [this line](https://github.com/intel/mkl-dnn/blob/master/cmake/MKL.cmake#L170).

Do you set `MKLROOT` when you call cmake?
Also if you download small Intel MKL-ML into `external/` directory cmake should be able to find the library as well.

**Comment by TechnikEmpire** [comment]
@mfomenk defines it where exactly, just in case I'm missing something. Sorry in advance if I've raised a false alarm, but for me it was not defined despite cmake finding MKL. I had to see it as a preprocessor variable manually but again I could have goofed something up here so let me know where I should have found that definition.

**Comment by emfomenk** [comment]
It seems that I miss something... so sorry for the repetition.

According to MKL.cmake if cmake finds MKL then it adds `-DUSE_MKL` to the compilation flags ([see this link](https://github.com/intel/mkl-dnn/blob/master/cmake/MKL.cmake#L170)). In theory you should be able to find this definition in the compile output of MSVS or just on the screen if you cmd / msbuild.
Could you please dump the output of CMake and the output of how build goes?

**Comment by TechnikEmpire** [comment]
I'm using cmake to generate visual studio 2017 project files. There's no USE_MKL defined in the preprocessor section of the project files. That was my point but I'll check to see if it gets added into the command line somewhere else.

**Comment by emfomenk** [comment]
Any updates?

**Comment by TechnikEmpire** [comment]
@emfomenk After we merge 260 I'll reset and look at this again.

**Comment by emfomenk** [comment]
@TechnikEmpire,

Any news on this issue?

**Comment by emfomenk** [comment]
Will close due to lack of activity.
Please feel free to reopen.

**Comment by TechnikEmpire** [comment]
@emfomenk Sorry for the long delay. This probably was never an issue, and I can confirm as of master (88c4882) that this is not an issue. When configured correctly from CMake, USE_MKL and friends are set properly.

**Comment by emfomenk** [comment]
Great!
Thanks for letting me know :)
