### ISSUE TITLE
Indices for Maxpool layer

### ISSUE THREAD

**Issue by nhkrishna** [intel/mkl-dnn#259]
hi,

I'm trying to verify index values of max pooling . I used `int32_t` data type for index buffer. I have observed index buffer workspace supports  https://github.com/intel/mkl-dnn/blob/a29d8487a63afca3d5b8c5bbdbb473cf8ccc6e51/src/cpu/ref_pooling.cpp#L69  
But, It's giving unexpected output for index buffer.  Here i attached the stand alone max pool layer code , input, output and expected output. Correct me if something wrong in this snippet. 
[ExpectedOutput.txt](https://github.com/intel/mkl-dnn/files/2098759/ExpectedOutput.txt)
 [maxpool_indices.txt](https://github.com/intel/mkl-dnn/files/2098728/maxpool_indices.txt)
[input.txt](https://github.com/intel/mkl-dnn/files/2098737/input.txt)
[output.txt](https://github.com/intel/mkl-dnn/files/2098738/output.txt)

thanks,
hari

**Comment by emfomenk** [comment]
Hi @nhkrishna,

According to 
https://github.com/intel/mkl-dnn/blob/a29d8487a63afca3d5b8c5bbdbb473cf8ccc6e51/src/cpu/cpu_pooling_pd.hpp#L35

The index data type is either `int8_t` or `int32_t` depending on how big the kernel size is. In general if kernel_size is less than 256 then `int8_t` is used (exactly your case where the kernel_size is 4).
Please also note that we do not specify in what form the indices are kept. It is up to implementation. However so far all the implementation keep max indices as local offset within the window (in row major-format), i.e.
``` c++
max_idx = (max_global_pos_h - window_global_start_pos_h) * kernel_w
        + (max_global_pos_w - window_global_start_pos_w)
```

**Comment by nhkrishna** [comment]
thanks for your reply @emfomenk . 

Now i'm able to get the correct max indices (local offset with in the window). My use case is to create **unpooling**(populate orginal size buffer with retaining only max values in their indices and all remaining all values as zero's) using  indices and maxpooling buffers. Does MKLDNN supports **unpooling** operation ?

**Comment by emfomenk** [comment]
Hi @nhkrishna,

You can use pooling backward to implement unpooling (up-sampling).
```
    (dst, workspace) <-- pooling_fwd(src, prop_kind=forward_training)
    src_max_or_zero <-- pooling_bwd(dst, workspace)
```

With Intel MKL-DNN that is the only valid way (that I can image) that you can use. Because as I mentioned earlier Intel MKL-DNN doesn't give any guarantee how workspace (indices) are stored in memory. Layout might be the same as dst and might not be, the data type might be `uint8_t` and might be `int32_t`, indices might be local or global, etc... So there is no reliable way to do that w/o backward pooling.

**Comment by cfRod** [comment]
> Hi @nhkrishna,
> 
> You can use pooling backward to implement unpooling (up-sampling).
> 
> ```
>     (dst, workspace) <-- pooling_fwd(src, prop_kind=forward_training)
>     src_max_or_zero <-- pooling_bwd(dst, workspace)
> ```
> 
> With Intel MKL-DNN that is the only valid way (that I can image) that you can use. Because as I mentioned earlier Intel MKL-DNN doesn't give any guarantee how workspace (indices) are stored in memory. Layout might be the same as dst and might not be, the data type might be `uint8_t` and might be `int32_t`, indices might be local or global, etc... So there is no reliable way to do that w/o backward pooling.

@igorsafo is this functionality implemented at TensorFlow level for e.g to support unpooling/max_pooling_with_indices?
