### ISSUE TITLE
Max pooling error

### ISSUE THREAD

**Issue by adelecourot** [intel/mkl-dnn#261]
Hello, I am new to mkldnn, and I have some trouble with maxpooling: I get the error message "could not create a forward pooling primitive descriptor". I really don't understand why.
Does anyone have an idea about how to fix this?
-----------------------------------------------------------------------------

### Environment
* CPU make and model:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2401.000
BogoMIPS:              4788.55
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23

* OS version
Linux adele 2.6.32-696.20.1.el6.centos.plus.x86_64 #1 SMP Sun Jan 28 07:56:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)

### Steps to reproduce
```
#include <chrono>
#include <iostream>
#include <numeric>
#include <string>

#include "mkldnn.hpp"
void _pooling(int nci, int csz, int csy, int csx,
		std::vector<float> * user_src, std::vector<float> * user_dst){
	/* Performs a 3d max pooling on user-src and stores it in user_dst.
	 * Kernel size: (2, 2, 2)
	 * Strides: (2, 2, 2)
	 */
	const int batch = 1;

	mkldnn::memory::dims pool_kernel = { 2, 2, 2 };
	mkldnn::memory::dims pool_strides = { 2, 2, 2 };
	mkldnn::memory::dims pool_src_tz = { batch, nci, csz, csy, csx };
	mkldnn::memory::dims pool_dst_tz = { batch, nci, csz/2, csy/2, csx/2};

	auto cpu_engine = mkldnn::engine(mkldnn::engine::cpu, 0);
	auto pool_padding = { 0, 0, 0 };

	std::vector<mkldnn::primitive> net;

	/*create memory for user data */
	auto user_src_memory = mkldnn::memory({ { { pool_src_tz }, mkldnn::memory::data_type::f32,
		mkldnn::memory::format::ncdhw }, cpu_engine }, (*user_src).data());
	auto user_dst_memory = mkldnn::memory({ { { pool_dst_tz }, mkldnn::memory::data_type::f32,
				mkldnn:: memory::format::ncdhw }, cpu_engine }, (*user_dst).data());

	/* create memory descriptors*/
	auto pool_dst_md = mkldnn::memory::desc(
	            { pool_dst_tz }, mkldnn::memory::data_type::f32, mkldnn::memory::format::any);
	auto pool_src_md = mkldnn::memory::desc(
		            { pool_src_tz }, mkldnn::memory::data_type::f32, mkldnn::memory::format::any);
	std::cout<< "Md"<< std::endl;

	/*create pooling */
	auto pool_desc = mkldnn::pooling_forward::desc(mkldnn::prop_kind::forward_inference,
			mkldnn::pooling_max, pool_src_md,
			pool_dst_md, pool_strides, pool_kernel, pool_padding,
			pool_padding, mkldnn::padding_kind::zero);
	std::cout<< "Desc"<< std::endl;
	try{
		auto pool_pd = mkldnn::pooling_forward::primitive_desc(pool_desc, cpu_engine);
		std::cout<< "Pd"<< std::endl;

		/*reorder data if necessary*/
		auto pool_src_memory = user_src_memory;
		if (mkldnn::memory::primitive_desc(pool_pd.src_primitive_desc())
				!= user_src_memory.get_primitive_desc()) {
			pool_src_memory = mkldnn::memory(pool_pd.src_primitive_desc());
			net.push_back(mkldnn::reorder(user_src_memory, pool_src_memory));
		}
		auto pool_dst_memory = user_dst_memory;
		if (mkldnn::memory::primitive_desc(pool_pd.dst_primitive_desc())
				!= user_dst_memory.get_primitive_desc()) {
			pool_dst_memory = mkldnn::memory(pool_pd.dst_primitive_desc());
			net.push_back(mkldnn::reorder(user_dst_memory, pool_dst_memory));
		}

		/* create pooling primitive an add it to net */
		net.push_back(
				mkldnn::pooling_forward(pool_pd, pool_src_memory, pool_dst_memory));
	} catch (mkldnn::error &e){
        std::cerr << "status: " << e.status << std::endl;
        std::cerr << "message: " << e.message << std::endl;
	}
        mkldnn::stream(mkldnn::stream::kind::eager).submit(net).wait();
}

int main(int argc, char **argv) {
	/* Allocate input and output buffers for user data */
	int nci = 1;
	int csz = 20;
	int csy = 10;

	std::vector<float> user_src(nci * csz * csy * csy, 1.0f);
	std::vector<float> user_dst(nci * csz/2 * csy/2 * csy/2, -32.0f);

	auto begin = std::chrono::duration_cast<std::chrono::milliseconds>(
			std::chrono::steady_clock::now().time_since_epoch()).count();
	
	std::cout<< "Pooling"<<std::endl;

	_pooling(nci, csz, csy, csy, &user_src, &user_dst);

	auto end = std::chrono::duration_cast<std::chrono::milliseconds>(
					   std::chrono::steady_clock::now().time_since_epoch())
					   .count();
	std::cout << "Use time " << (end - begin) << "\n";

	/* Visualization*/
	for(int ic=0; ic<nci; ic++){
		for (int i=0; i<csz/2; i++){
			for(int j=0; j<csy/2; j++){
				for(int h=0; h<csy/2; h++){
					std::cout<< user_dst[h + j*csy/2 + i*csy*csy/4 + ic*csy*csy*csz/8] << " ";
				}
			}
			std::cout<<std::endl;
		}
		std::cout<<std::endl;
	}
    return 0;
}
```
### Actual behavior
status: 5
message: could not create a forward pooling primitive descriptor

Thank you for your help.

**Comment by vpirogov** [comment]
@adelecourot, pooling (and all other primitives except convolution and inner product) cannot be created with `memory::format::any` in src). These primitives are optimized for blocked formats, NCHW/NCDHW and NHWC/NDHWC. The example runs correctly when I replace `memory::format::any` with `memory::format::ncdhw` in `pool_src_md`.

As reorders are relatively expensive in comparison to primitives other than pooling and convolution you never want to reorder your data to run these.

**Comment by adelecourot** [comment]
Thanks, it solved the problem!
But I used the simplenet example to write this, and in the code, it is written `memory::format::any`. Why there and not in my code?

**Comment by vpirogov** [comment]
In the example pooling always reuses memory from the previous primitive, which has defined format. `memory::format:any` is used for pooling dst only, not for src.

**Comment by adelecourot** [comment]
Oh ok, thank you for your explanations, it has been very helpful!
