### ISSUE TITLE
A question about jcp.is_oc_scale in jit_avx512_core_u8s8s32x_conv_kernel

### ISSUE THREAD

**Issue by yanan1112** [intel/mkl-dnn#269]
Hi mkldnn team,

By running 'test_convolution_forward_u8s8s32', I noticed jcp.is_oc_scale is always 0, is that mean all oc of convolution output apply a same scale (a float value)?

Is there any methods that we can apply different scales on all oc of convolution output? 

Thanks very much in advance and looking forward to your reply.

**Comment by emfomenk** [comment]
Hi @yanan1112,

Gtests are mostly like a smoke tests for convolutions. The real tests live in [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn).

In particular we test output scale per channel [here](https://github.com/intel/mkl-dnn/blob/master/tests/benchdnn/inputs/test_conv_attrs#L7).
Notice: `oscale=per_oc:2.25`, which means  that scale factor would be unique for each output channel.

**Comment by emfomenk** [comment]
Close due to lack of activity.
Please feel to reopen if you have any further questions.
