### ISSUE TITLE
Tensorflow giving Errors on 3D Data

### ISSUE THREAD

**Issue by AlbertPun** [intel/mkl-dnn#270]
I am training a model to perform volumetric segmentation (3D data). I am training on CPU due to the size of the input data. I am using a anaconda environment with tensorflow-mkl and keras. When I train the model, I get an error.

"tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'data_format' of "NDHWC" is not in the list of allowed values: "NHWC", "NCHW"

How may I resolve this issue so I can train my 3D-Unet with mkl?

**Comment by emfomenk** [comment]
Summon @jbobba

**Comment by jbobba** [comment]
@AlbertPun lets follow up here: https://github.com/tensorflow/tensorflow/issues/20555 since this is not related to MKLDNN

**Comment by emfomenk** [comment]
Thanks a lot, @jbobba!
I am closing the issue then.
