### ISSUE TITLE
Question about the topology execution times

### ISSUE THREAD

**Issue by xmsjshou** [intel/mkl-dnn#271]
I am wondering how the "times" parameter works in the stream execution.
Since it has a huge influence on the running time, what is a suggested value of "times"?

```cpp
for (int j = 0; j < times; ++j) {
    /* Execute the topology */
    stream(stream::kind::eager).submit(net).wait();
}
```

**Comment by emfomenk** [comment]
Hi @xmsjshou,

Times is the amount of times you perform independent inference. For instance you might configure the topology to process one image (batch 1), and then you will have to execute the inference as many **times** as number of images you have (for each run putting new image in the source of the topology).

**Comment by xmsjshou** [comment]
Thank you very much！
