### ISSUE TITLE
Compiler warning in mkldnn.hpp

### ISSUE THREAD

**Issue by ivsrihari** [intel/mkl-dnn#272]
Hi,

I am seeing following performance warning message from mkldnn.hpp when using visual studio 2015 compiler. Can you please fix this issue?

`mkldnn.hpp(707): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
`

In file mkldnn.h, below function returns int
```
int MKLDNN_API mkldnn_memory_primitive_desc_equal(
        const_mkldnn_primitive_desc_t lhs,
        const_mkldnn_primitive_desc_t rhs);
```
In file mkldnn.hpp, below function expects bool to be returned, but gets int.
```        
bool operator==(const primitive_desc &other) const {
            return mkldnn_memory_primitive_desc_equal(get(), other.get());
```

-----------------------------------------------------------------------------

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave 
differently on depending on the compiler and build environment. Include 
the following information to help reproduce the issue:

* Compiler version - Visual Studio C++ 2015

Thanks,
Srihari

**Comment by igorsafo** [comment]
Hi @ivsrihari ,
Thanks for noticing about this issue! We will fix it.

Regards,
Igor
