### ISSUE TITLE
Format for initializing weights and bias ...

### ISSUE THREAD

**Issue by xmsjshou** [intel/mkl-dnn#273]
For example, using the `memory::formar::goihw` which means a 5D weights tensor.
However, only a 1D vector is used to store all the weight values.
What's the order of data in such a vector mapping into the 5D format?

```cpp
... ...
memory::dims conv1_weights_tz = { 16, 32, 1, 48, 16 };
... ...
/* Allocate and fill buffers for weights and bias */
std::vector<float> conv1_weights(std::accumulate(conv1_weights_tz.begin(), 
        conv1_weights_tz.end(), 1, std::multiplies<uint32_t>()));
... ...
```

**Comment by emfomenk** [comment]
This is a typical situation for C/C++ world. Keeping data linearly in memory is more efficient than having a vector of vector of vector...

Let's assume the dimensions are [G, O, I, H, W]. 

Then `goihw` gives you the following order of the axes in memory:
```c++
size_t index = g * O * I * H * W + o * I * H * W + i * H * W + h * W + w;
array[index] // <-- real_value(g, o, i, h, w) 
```

While `hwigo` gives:
```c++
size_t index = h * W * I * G * O + w * I * G * O + i * G * O + g * O + o;
array[index] // <-- real_value(g, o, i, h, w) 
```

**Comment by xmsjshou** [comment]
Thanks for your reply! @emfomenk
