### ISSUE TITLE
how can I compile mkl with tbb

### ISSUE THREAD

**Issue by suhang1994** [intel/mkl-dnn#274]
I think it can be compile with tbb like this 

https://software.intel.com/zh-cn/node/528527

but I dont't find how to compile with tbb

**Comment by emfomenk** [comment]
Hi @suhang1994,

Are you talking about [Intel MKL](https://software.intel.com/en-us/mkl) or [Intel MKL-DNN](https://github.com/intel/mkl-dnn)? The difference between those can be read in #102.

If about former, please refer to [Link Line Adviser](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor) or example (installed with Intel MKL). Also please ask questions related to Intel MKL on the corresponding [forum](https://software.intel.com/en-us/forums/intel-math-kernel-library).

If you are asking about Intel MKL-DNN, we currently do not support TBB. We are looking into how that can potentially be done (at least from inference perspective), but no concrete plans or ETA as of now.

**Comment by suhang1994** [comment]
@emfomenk 

Thanks a lot

 So, It means tensorflow doesn't support mkl with tbb now?

**Comment by emfomenk** [comment]
I don't think so.
Summon @jbobba to confirm this.

**Comment by jbobba** [comment]
Correct.

**Comment by suhang1994** [comment]
ok, I get it
thank you~
