### ISSUE TITLE
[0.15] Convolution yields incorrect results

### ISSUE THREAD

**Issue by Sand3r-** [intel/mkl-dnn#288]
### Environment
* CPU:  Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
* OS version: 16.04.1-Ubuntu SMP
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
* CMake version 3.5.1
* CMake output log
* git hash: fd22379c489de5882488ce45ebf7a5307a29eb37

### Steps to reproduce
1. Download and build paddle-paddle [from sources](http://www.paddlepaddle.org/docs/develop/documentation/fluid/en/build_and_install/build_from_source_en.html)
2. Apply the patch
```
diff --git a/cmake/external/mkldnn.cmake b/cmake/external/mkldnn.cmake
index 20dda35..bdc3704 100644
--- a/cmake/external/mkldnn.cmake
+++ b/cmake/external/mkldnn.cmake
@@ -54,7 +54,7 @@ ExternalProject_Add(
     ${EXTERNAL_PROJECT_LOG_ARGS}
     DEPENDS             ${MKLDNN_DEPENDS}
     GIT_REPOSITORY      "https://github.com/01org/mkl-dnn.git"
-    GIT_TAG             "a29d8487a63afca3d5b8c5bbdbb473cf8ccc6e51"
+    GIT_TAG             "fd22379c489de5882488ce45ebf7a5307a29eb37"
     PREFIX              ${MKLDNN_SOURCES_DIR}
     UPDATE_COMMAND      ""
     CMAKE_ARGS          -DCMAKE_INSTALL_PREFIX=${MKLDNN_INSTALL_DIR}
```
3. 
a. To find information about incorrect convolution results, please run:
```sh
python <paddle_dir>/python/paddle/fluid/tests/unittests/test_conv2d_mkldnn_op.py TestMKLDNN.test_check_output
```
b. For having the framework crash:
```sh
python <paddle_dir>/python/paddle/fluid/tests/unittests/test_conv2d_mkldnn_op.py TestMKLDNNWithStride.test_check_grad
```

### Actual behavior
In the case of the first example (3.a) convolution returns incorrect results.
In the case of the second example (3.b) convolution causes framework to crash, since one of the framework's integrity checks figures out that a memory region has been corrupted.

### Expected behavior
In the case of the first example (3.a) - correct results
In the case of the second example (3.b) - no memory violations + correct results.

### Comments
The hash of the commit which introduced changes that caused the tests to fail: fd22379c489de5882488ce45ebf7a5307a29eb37

I'd be glad to provide further explanations if necessary.

**Comment by emfomenk** [comment]
Hi @Sand3r-,

The commit you are referring to introduced vast changes. If the integration was not done properly this commit might have brought some issues.

For more information, please go through the following [article](https://intel.github.io/mkl-dnn/understanding_memory_formats.html) that explains what assumptions can or cannot be made with new padded layouts (that were introduced by the commit mentioned).

Could you please share a standalone reproducer, that demonstrates the issue? For instance you may run PaddlePaddle with MKLDNN_VERBOSE=2 to gather the convolution, and highlight the one, that gives incorrect results.

**Comment by Sand3r-** [comment]
Thank you so much for the link to the article.
The problem 3.a was caused by tests expecting NCHW format, while MKLDNN returned the block padded format.
Problem 3.b I have managed to solve by querying MKLDNN primitives for demanded buffer sizes, and providing appropriately sized buffers to MKLDNN engine.
