### ISSUE TITLE
Any simple example *with data*? 

### ISSUE THREAD

**Issue by blueberry** [intel/mkl-dnn#295]
Hello,

I'm trying to use MKL-DNN for custom DL code, and I find its API quite well-designed (once I got past the first-contact barrier :) Code examples are also informative enough despite not being numerous, and API having only sparsely documented. Now, the problem is that, when I run an existing example or create my own, the only thing I can be sure is that the computation physically takes place, and that the engine calculates *something*.

 However, I could not find any example, not even the simplest one, that uses specific input, expects specific output, and actually compares the output with the expected result. I am talking about simple unit tests. Take this miniature tensor, run a convolution over it once, and expect this particular miniature tensor as an output. Is there something like this that I am not aware of? It doesn't have to be a part of MKL-DNN project, just some example that is known to be compatible with how MKL-DNN implements these operations.

Can you share the (internal?) unit tests that you use in MKL-DNN development? Or you test it only through TensorFlow and other high-level frameworks that use MKL?

**Comment by shelleygoel** [comment]
Hi blueberry, we have [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn) to test convolutions and gtests to test all primitives. I suggest starting with any test in tests/gtest. Each test has a reference implementation against which the optimized primitives are tested.

For benchdnn look into tests/benchdnn/conv/conv.cpp to see how benchnn tests convolution, reference implementation of convolution is in tests/benchdnn/conv/ref_conv.cpp.

**Comment by blueberry** [comment]
Thank you. I was hoping for a concrete end-to-end numbers, but these tests will certainly help.
