### ISSUE TITLE
Is reorder needed when all formats are "any"?

### ISSUE THREAD

**Issue by blueberry** [intel/mkl-dnn#296]
I'm not sure about one thing about the reorder operation. Suppose that I use MKL-DNN directly instead of through a higher layer framework with its own data formats and specifications. Suppose that I set all internal data formats as `any` so MKL-DNN can choose whatever fits well. Suppose also that I can feed the user data in MKL-DNN's preferred formats (nchw etc.). In that case, will MKL-DNN need to perform reorders for some operations? Do I still need to check for internal layers' src/dst memory format compatibility and perform reorders?

**Comment by blueberry** [comment]
Thank you. Is there any automatic setting or flag to do that, or I should do this as in the examples, by comparing references and then issuing reorder if references do not match?

**Comment by vpirogov** [comment]
Per Intel MKL-DNN design all the reorders are explicit, so this have to be done in the same way as in the examples. You may want to build a layer on top that checks layouts and performs lazy conversions to make things easier.

**Comment by blueberry** [comment]
Thank you.
