### ISSUE TITLE
older binary links (same as 0.14) for v0.15 release?

### ISSUE THREAD

**Issue by oscarbg** [intel/mkl-dnn#297]
In releases page 0.15 seems to point to same binaries as 0.14:
mklml_lnx_2018.0.3.20180406.tgz
mklml_mac_2018.0.3.20180406.tgz
mklml_win_2018.0.3.20180406.zip
Mistake?
thanks..

**Comment by vpirogov** [comment]
No, this is not a mistake. The binaries you are referring to are not Intel MKL-DNN binaries. This is an optional binary component called Intel MKL small libraries that can be used in Intel MKL-DNN builds.

**Comment by oscarbg** [comment]
Ah thanks..
