### ISSUE TITLE
How exactly is stream intended to be used in many forward/backward iterations?

### ISSUE THREAD

**Issue by blueberry** [intel/mkl-dnn#298]
Hello,

Maybe the answer to my question will be obvious. Sorry for that, I've just started exploring the mkl-dnn API. On top of that, I am using C api, but via Java JNI, and not directly. What's more, I'm calling everything interactively from Clojure REPL, so there might be many subtleties where there is zero information online, and I have to discover things by poking.

On to the topic:) 

I've successfully created a simple computation graph and submitted it to the stream. I've checked the memory, and everything has been computed correctly. However, the stream accepts job submissions only until `mkldnn_stream_wait` has been called. After the wait call, each subsequent submission raises a `mkldnn_invalid_arguments` error. I can only do a `mkldnn_stream_rerun` and even that only once. After that, the stream is unusable.

As I understand, the intended use is to submit many primitives to the stream, and only once everything has been submitted, call wait to see the final results. However, I am confused about how this is intended to be used during the network training, as it is generally not possible to decide in advance how many iterations is going to be needed. The stopping criterion may be a fixed number of iterations, but more sophisticated schedules are common, that may rely on reading error values periodically to determine convergence. 

I imagined that it would be possible to do something like this: https://github.com/intel/mkl-dnn/blob/c9d6e8527094aad5562d34a58c44d988d59c5f25/examples/simple_training_net.c#L808:
```c
int n_iter = 1; //number of iterations for training.
    /* Execute the net */
    while (n_iter) {
        /* Forward pass */
        CHECK(mkldnn_stream_submit(stream_fwd, n_fwd, net_fwd, NULL));
        CHECK(mkldnn_stream_wait(stream_fwd, n_fwd, NULL));

        /* Update net_diff_dst */
        // ..........
        /* Backward pass */
        CHECK(mkldnn_stream_submit(stream_bwd, n_bwd, net_bwd, NULL));
        CHECK(mkldnn_stream_wait(stream_bwd, n_bwd, NULL));

        /*... update weights ... */
//.....
        --n_iter;
    }

```
However, this example uses only one iteration. Is this supposed to work as-is with `n_iter` being initialized to more than `1`?

The only thing that comes to my mind is that this example uses two streams, `stream_fwd` and `stream_bwd`, that somehow re-initialize each other (but how?).

**Comment by mgouicem** [comment]
Hi @blueberry. 
You are right this example is wrong (apologies for this). Thanks for the catch.

There are two ways to work with streams:
1) (recommended) is to create, submit, wait and destroy. In this case the stream is just not reused and treated as a temporary object.
2) if you want to reuse the stream, you should use submit for the first run and rerun for the subsequent ones. The code should look like this:
```c++
int n_iter = 10; //number of iterations for training.
/* Execute the net */\
for (int i = 0; i < n_iter; i++) {
    /* Forward pass */
    if (i == 0)
        CHECK(mkldnn_stream_submit(stream_fwd, n_fwd, net_fwd, NULL));
    else
        CHECK(mkldnn_stream_rerun(stream_fwd, NULL));
    CHECK(mkldnn_stream_wait(stream_fwd, n_fwd, NULL));

    /* Update net_diff_dst */
    CHECK(mkldnn_memory_get_data_handle(pool_user_dst_memory, &net_output));
    /*...user updates net_diff_dst using net_output...*/
    // some user defined func update_diff_dst(net_diff_dst, net_output)

    /* Backward pass */
    if(i == 0)
        CHECK(mkldnn_stream_submit(stream_bwd, n_bwd, net_bwd, NULL));
    else
        CHECK(mkldnn_stream_rerun(stream_bwd, NULL));
    CHECK(mkldnn_stream_wait(stream_bwd, n_bwd, NULL));

    /*... update weights ... */
    CHECK(mkldnn_memory_get_data_handle(conv_user_diff_weights_memory,
                                        &net_diff_weights));
    CHECK(mkldnn_memory_get_data_handle(conv_diff_bias_memory,
                                        &net_diff_bias));
    /* ...user updates weights and bias using diff weights and bias...*/
    // some user defined func update_weights(conv_user_weights_memory,
    // conv_bias_memory,
    //      net_diff_weights, net_diff_bias);
}
```

We will update the example accordingly.

**Comment by blueberry** [comment]
Thanks. However, the problem for me was that I mkl-dnn was allowing only a single rerun. Just to make sure before chasing the tail again: this code works for you when you run it?

**Comment by mgouicem** [comment]
Yes it does. Were you running `mkldnn_stream_wait` after the `mkldnn_stream_rerun`?

**Comment by blueberry** [comment]
Honestly, I am no longer sure, since a month passed since that. Now that I have an example that works, I guess it would be much easier to create a working setup. Currently I just submit multiple times. I hope there's some performance gain with rerun vs submit?

**Comment by mgouicem** [comment]
These streams were originally designed for devices other than CPUs.
On CPU, you should not see any noticeable performance difference between reruning an existing stream and submitting a newly created stream.

**Comment by blueberry** [comment]
Thank you for the clarification.
