### ISSUE TITLE
Confusing mkldnn_eltwise_forward_desc_init api in the case of relu

### ISSUE THREAD

**Issue by blueberry** [intel/mkl-dnn#300]
`mkldnn_eltwise_forward_desc_init` has places for `alpha` and `beta` parameters of an elementwise function. In the case of `relu`, however, there is no way to set the parameter `scale`. When relu is added as a post_op, there is an example of how to set scale, but in the examples that show relu as a separate operation, the example only uses `alpha` to set a negative slope, but it is not obvious from the api whether there is a way to set something like `scale`.

I've looked around, but could not find any hints in the reference manual, nor in the code. Is there a feature parity between post_op and separate eltwise operations?

**Comment by blueberry** [comment]
Thank you. That explains it. I do not particularly need scale with relu, I was just confused by examples. It would be great if someone from the MKLDNN could write a brief blog post explaining such broader design ideas around the couple of central building blocks. Just so the consumer of the api know what to expect and where to look for the details :)

**Comment by emfomenk** [comment]
Makes sense. We just recently started a *series* of articles where we try to explain the design decisions made. See the bottom of the [main doc page](http://intel.github.io/mkl-dnn/index.html). So far we have only one topic about (memory formats)[http://intel.github.io/mkl-dnn/understanding_memory_formats.html].

Hopefully the list of articles would grow... :)

**Comment by blueberry** [comment]
Thanks! That was the one I missed, since it is not on the main page, and it is very well camouflaged in the (quite noisy) reference manual page.

Can you please link such articles from the main README.md? This is a kind of doc that I think is very valuable to anyone who is trying to use MKLDNN directly.
