### ISSUE TITLE
Support for Depthwise Separable Convolution 

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#301]
First of all, thanks for your excellent open-source dnn library!

I'm looking for a fast depthwise separable convolution implementation. 
Is this something that's on the roadmap?

thanks

**Comment by emfomenk** [comment]
Hi @zeno40,

Alas we don't have a single depthwise-separable convolution primitive.
However you can easily simulate it via running depthwise convolution followed by the regular 1x1-convolution.

I know our friend team who works on [OpenVINO](https://software.intel.com/en-us/openvino-toolkit) was going to submit a PR with this depthwise-separable convolution as a single primitive, but there is no ETA for this PR.

**Comment by zeno40** [comment]
Thanks for the information.
I will stack a grouped convolution and a regular 1x1 convolution together in the mean-time.

**Comment by zeno40** [comment]
How can I make a depthwise convolution primitive in mkl-dnn? 


thanks

**Comment by emfomenk** [comment]
You have to use regular convolutions with groups (depthwise convolution is a particular case when the number of groups equal to the number of input/output channels).

For example for the depthwise convolution with input `[mb, channels, input_height, input_width]`, kernel size `[kernel_height, kernel_width]` and output `[mb, channel, output_height, output_width]` you need to create an Intel MKL-DNN convolution with the following parameters:
```
src_desc = {{mb, channels, input_height, input_width}, f32, any};
wei_desc = {{ 
    /* groups = */ channels,
    /* oc =  */ 1,  /* ic = */ 1,
    /* kh = */ kernel_height, 
    /* kw = */ kernel_width}, f32, any};
dst_desc = {{mb, channels, output_height, output_width}, f32, any};
// create convolution as usual
```

Not that weights have number of groups equal `channels`, and `oc=ic=1`.

**Comment by zeno40** [comment]
Thanks,
It works even when I hold a fixed nchw data-layout for the src and dst descriptors and using direct convolution. 
Can I also use the winograd convolution primitives for 3x3 depthwise convolution?

**Comment by emfomenk** [comment]
It should work (at least in theory) no matter what layout is. Though I would strongly recommend to allow Intel MKL-DNN to define the most appropriate layout, by passing `mkldnn_any`as a format. In that case the most performant implementation would be chosen.

Winograd as of now does not support depthwise convolution. And there no plans. The thing is that Winograd requires extra data movements compare to the direct algorithm and while it is still beneficial for the compute intensive cases, it would most likely be inefficient for the depthwise case, because those convolutions are mostly memory bandwidth bound.

**Comment by zeno40** [comment]
I use a fixed nchw layout because I also use a Windows port of NNPACK for regular non-strided convolutions with a kernel size equal or below 16x16 (except 1x1).
Is it possible with mkl-dnn to make a 3x3 separable convolution (non-depthwise)?

**Comment by zeno40** [comment]
Sorry for the last (stupid) question. Separable convolution is just a synonym used for a depthwise separable convolution.
