### ISSUE TITLE
MKLDNN RNN training benchmark

### ISSUE THREAD

**Issue by zxb1489479870** [intel/mkl-dnn#303]
Hi, I am writing a RNN traing benchmark, the details is that:
`int layers = 1;`
`int direc = 1;`
`int gates = 4;`
`int num_states =2;`
**For forward:**
the memory descriptors are:
`x_md = memory::desc({ x_tz }, data_t, memory::format::tnc)`, x_tz = {seq_length_max, batch, feature_size};
`y_md = memory::desc({ y_tz }, data_t, mkldnn::memory::format::tnc)`, y_tz = {seq_length_max, batch, direc*feature_size};
`wh_md = memory::desc({ wh_tz }, data_t, memory::format::ldigo)`, wh_tz = {layers, direc, feature_size, gates, feature_size};
`wi_md = memory::desc({ wi_tz }, data_t, memory::format::ldigo)`, wi_tz = {layers, direc, feature_size, gates, feature_size};
`b_md = memory::desc({ b_tz }, data_t, mkldnn::memory::format::ldgo)`, b_tz = {layers, direc, gates, feature_size};
`src_iter_md = memory::desc({ src_iter_tz }, data_t, memory::format::ldsnc)`, src_iter_tz = {layers, direc, num_states, batch, feature_size};
`dst_iter_md = memory::desc({ dst_iter_tz }, data_t, memory::format::ldsnc)`, dst_iter_tz = {layers, direc, num_states, batch, feature_size};
And the memories are: 
x_memory, y_memory, wh_memory,wi_memory, b_memory, src_iter_memory, dst_iter_memory

- So for forward part:
` auto rnn_desc = rnn_forward::desc(prop_kind::forward_training, cell, rnn_direction::unidirectional_left2right, x_md, src_iter_md, wh_md, wi_md, b_md, y_md, dst_iter_md)`,
`auto rnn_pd = rnn_forward::primitive_desc(rnn_desc, cpu_engine);`
`// create workspace memory`
`auto workspace_memory = memory(rnn_pd.workspace_primitive_desc());`
`std::vector<primitive> net_fwd;`
`net_fwd.push_back(rnn_forward(rnn_pd, x_memory, src_iter_memory, wh_memory, wi_memory, b_memory, y_memory, dst_iter_memory,  workspace_memory)); `

**For backward:**
the memory descriptors are:
// the weights format are different from forward weight
 `bwd_wi_md = memory::desc({ bwd_wi_tz }, data_t, memory::format::ldgoi)`, bwd_wh_tz = {layers, direc, gates, feature_size, feature_size}
` bwd_wh_md = memory::desc({ bwd_wh_tz }, data_t, memory::format::ldgoi)`, bwd_wi_tz = {layers, direc, gates, feature_size, feature_size};

`diff_src_md = memory::desc({ x_tz}, data_t, memory::format::tnc); `
`diff_y_md = memory::desc({ y_tz }, data_t, mkldnn::memory::format::tnc);`
`diff_wh_md = memory::desc({ wh_tz }, data_t, memory::format::ldigo);`
`diff_wi_md = memory::desc({ wi_tz }, data_t, memory::format::ldigo);`
`diff_b_md = memory::desc({ b_tz }, data_t, mkldnn::memory::format::ldgo);`
`diff_src_iter_md = memory::desc({ src_iter_tz }, data_t, memory::format::ldsnc);`
`diff_dst_iter_md = memory::desc({ dst_iter_tz }, data_t, memory::format::ldsnc);`

And the memories are: 
bwd_wi_memory, bwd_wh_memory, diff_src_memory, diff_y_memory , diff_wh_memory, diff_wi_memory, diff_b_memory, diff_src_iter_memory, diff_dst_iter_memory

- So for backward part:
`auto bwd_desc = rnn_backward::desc(prop_kind::backward, cell, rnn_direction::unidirectional_left2right, x_md, src_iter_md, bwd_wh_md, bwd_wi_md, b_md, y_md, dst_iter_md, diff_src_md, diff_src_iter_md, diff_wh_md, diff_wi_md, diff_b_md, diff_y_md, diff_dst_iter_md);	`
 `auto bwd_pd = rnn_backward::primitive_desc(bwd_desc, cpu_engine);`
`std::vector<primitive> net_bwd;`
`net_bwd.push_back(rnn_backward(bwd_pd, x_memory, src_iter_memory, bwd_wh_memory, bwd_wi_memory, b_memory, y_memory, dst_iter_memory, diff_src_memory, diff_src_iter_memory, diff_wh_memory, diff_wi_memory, diff_b_memory, diff_y_memory, diff_dst_iter_memory, workspace_memory)); `

**At last:**
`stream(stream::kind::eager).submit(net_fwd).wait();`
`stream(stream::kind::eager).submit(net_bwd).wait();`

when I run the code, it aways has the following error: 
**status: 5 , message: could not create an RNN backward primitive descriptor.**

I have checked the code many times, but I don't know how to solve the problem. I hope you can give me some suggestions. Thanks.
-----------------------------------------------------------------------------

**Comment by zxb1489479870** [comment]
There has a bug according to https://github.com/intel/mkl-dnn/issues/305#issue-352465017, but I still have this error after using the latest master. Thanks.

**Comment by mgouicem** [comment]
Hi @zxb1489479870, the issue is with how you specify the dimensions of the weights on the backward pass.
In MKL-DNN, the dimensions passed to the memory descriptor creation are logical dimensions. For RNN weights, they should always be in ldigo layout. If you use `bwd_wi_tz = bwd_wh_tz = {layers, direc, feature_size, gates, feature_size}`, it should work.

**Comment by zxb1489479870** [comment]
It doesn't work even change the weights format to **ldigo**, I checked the lines https://github.com/intel/mkl-dnn/blob/f51304ad8087c0a3982ac023edd899db9f28baa3/src/cpu/cpu_rnn_pd.hpp#L207 and https://github.com/intel/mkl-dnn/blob/f51304ad8087c0a3982ac023edd899db9f28baa3/src/cpu/cpu_rnn_pd.hpp#L211,  there will set the weights format to **ldgoi**, it makes me confused.

**Comment by mgouicem** [comment]
Hi @zxb1489479870 , sorry my explanation was not clear enough.
In MKL-DNN, the way you specify the dimensions is not related to the datalayout. The dimensions are specified in a *fixed* order (sometimes refered to as logical layout), independantly of the datalayout (sometimes refered to as physical layout).
In the RNN weights case, the logical layout is ldigo and dimensions should be specified in that order. 
So if you want weights in the ldigo physical layout, you would do
<pre>
wi_tz = {layer, dir, feature_size, gates, feature_size}
auto wi_md = memory::desc({ wi_tz }, data_t, <b>memory::format::ldigo</b>);
</pre>
and if you want weights in the ldgoi physical layout, you would use the same dimensions order as follow:
<pre>
wi_tz = {layer, dir, feature_size, gates, feature_size}
auto wi_md = memory::desc({ wi_tz }, data_t, <b>memory::format::ldgoi</b>);
</pre>
As you can see, in both cases wi_tz is exactely the same, only the physical layout changed.

My suggestion in you case will be to do the following:
```
 auto bwd_wh_tz = {layers, direc, feature_size, gates, feature_size};
 auto bwd_wi_tz = {layers, direc, feature_size, gates, feature_size};

 auto bwd_wi_md = memory::desc({ bwd_wi_tz }, data_t, memory::format::ldgoi);
 auto bwd_wh_md = memory::desc({ bwd_wh_tz }, data_t, memory::format::ldgoi);
```

**Comment by zxb1489479870** [comment]
Hi, @mgouicem, It works now, Thanks.
