### ISSUE TITLE
A misspelling in /src/cpu/cpu_rnn_pd.hpp?

### ISSUE THREAD

**Issue by sjtuck** [intel/mkl-dnn#305]
I am tring to write a rnn training example since there is only a rnn inference example. But I am stuck at creating `rnn_backward::desc` and I found a misspelling in [https://github.com/intel/mkl-dnn/blob/master/src/cpu/cpu_rnn_pd.hpp#L230](url). I guess `diff_dst_iter_pd_` should be `dst_iter_pd_`?Thank you!

**Comment by emfomenk** [comment]
Hi @sjtuck,

Yeah, you are right, thanks!

The problem should be already fixed by 304835cb.
Please try the latest master.
