### ISSUE TITLE
Support for slice operation

### ISSUE THREAD

**Issue by safrooze** [intel/mkl-dnn#306]
For implementing a network that uses extensive slice operations (e.g. [Fast Wavenet Generation](https://arxiv.org/abs/1611.09482)), there needs to be constant switch between MKLDNN tensor layout and native framework layout. It would be great to have slice operator as part of MKLDNN to avoid the unnecessary memory copy in such cases.

**Comment by emfomenk** [comment]
Hi @safrooze,

Intel MKL-DNN has a view primitive descriptor that can be used to obtain a submemory from memory. In that case you would not have to do a conversion back to a framework native layout.

Please refer to #69 and #290 for more information.

**Comment by safrooze** [comment]
Thanks.
