### ISSUE TITLE
C++ compilation of rule '//tensorflow/core/kernels:mkl_aggregate_ops' failed

### ISSUE THREAD

**Issue by tonyreina** [intel/mkl-dnn#310]
### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
[bduser@merlin-param01 ~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                112
On-line CPU(s) list:   0-111
Thread(s) per core:    2
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               1000.366
BogoMIPS:              5005.94
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27,56-83
NUMA node1 CPU(s):     28-55,84-111
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke
* OS version (`uname -a`)
[bduser@merlin-param01 ~]$ uname -a
Linux merlin-param01.merlin.cluster.bds 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`gcc --version`)
[bduser@merlin-param01 ~]$ gcc --version
gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

* MKLROOT value (`echo MKLROOT=$MKLROOT`)
[bduser@merlin-param01 ~]$ echo MKLROOT=$MKLROOT
MKLROOT=
* CMake version (`cmake --version`)
[bduser@merlin-param01 ~]$ cmake --version
cmake3 version 3.11.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
* CMake output log
* git hash (`git log -1 --format=%H`)
[bduser@merlin-param01 tensorflow]$ git log -1 --format=%H
88ab8b0bd6ca4dba10a5ed8852e23eacfb0f888e
### Steps to reproduce
Please check that the issue is reproducible with the latest revision on
master. Include all the steps to reproduce the issue. A short C/C++ program
or modified unit tests demonstrating the issue will greatly help
with the investigation.

Trying to build from Source on CentOS 7.5 (SKL 8180). I get the following error when trying to build:

```./tensorflow/core/util/sparse/sparse_tensor.h:65:9: note: 'dims' was declared here
     int dims;
         ^~~~
ERROR: /home/bduser/tensorflow/tensorflow/core/kernels/BUILD:6287:1: C++ compilation of rule '//tensorflow/core/kernels:mkl_aggregate_ops' failed (Exit 1)
In file included from tensorflow/core/kernels/mkl_aggregate_ops.cc:35:0:
./tensorflow/core/util/mkl_util.h: In member function 'void tensorflow::FactoryKeyCreator::Append(tensorflow::StringPiece)':
./tensorflow/core/util/mkl_util.h:2057:19: error: 'class tensorflow::StringPiece' has no member named 'ToString'
     key_.append(s.ToString());
                   ^~~~~~~~
tensorflow/core/kernels/mkl_aggregate_ops.cc: In instantiation of 'void tensorflow::MklAddNOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]':
tensorflow/core/kernels/mkl_aggregate_ops.cc:518:1:   required from here
tensorflow/core/kernels/mkl_aggregate_ops.cc:451:26: warning: 'mkldnn::sum::primitive_desc::primitive_desc(const mkldnn::memory::desc&, std::vector<double>, std::vector<mkldnn::memory::primitive_desc>)' is deprecated [-Wdeprecated-declarations]
       auto sum_pd = sum::primitive_desc(dst.GetUsrMemDesc(), coeff, srcs_pd);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from tensorflow/core/kernels/mkl_aggregate_ops.cc:28:0:
external/mkl_dnn/include/mkldnn.hpp:1117:9: note: declared here
         primitive_desc(const memory::desc &output, std::vector<double> scale,
         ^~~~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 150.759s, Critical Path: 66.94s
INFO: 4647 processes: 4647 local.
FAILED: Build did NOT complete successfully
```
### Actual behavior
Should build.

### Expected behavior
Should build.

**Comment by emfomenk** [comment]
Hi @tonyreina,

I would suggest to file a bug against TensorFlow, rather than Intel MKL-DNN. The bug has nothing to do with the library but is about the integration to TensorFlow.

```
In file included from tensorflow/core/kernels/mkl_aggregate_ops.cc:35:0:
./tensorflow/core/util/mkl_util.h: In member function 'void tensorflow::FactoryKeyCreator::Append(tensorflow::StringPiece)':
./tensorflow/core/util/mkl_util.h:2057:19: error: 'class tensorflow::StringPiece' has no member named 'ToString'
     key_.append(s.ToString());
                   ^~~~~~~~
```

**Comment by tonyreina** [comment]
Many thanks!
