### ISSUE TITLE
How to choose other pooling function in mkldnn?

### ISSUE THREAD

**Issue by zhangkom** [intel/mkl-dnn#311]
Please, would you tell me Where can choose using Nchw_pooling or Jit_uni_pooling or Ref_pooling?

**Comment by vpirogov** [comment]
Intel MKL-DNN chooses which implementation to use automatically based on data layout and parameters of the function. For the most use cases there's no need to choose the implementation. If you want to get specific implementation for performance or validaiton purposes you can use `mkldnn_primitive_desc_iterator` API. Please refer to #137 for more details.
