### ISSUE TITLE
How to build MKL-DNN against libmklml_gnu?

### ISSUE THREAD

**Issue by okapies** [intel/mkl-dnn#312]
I tried to build MKL-DNN in [manylinux](https://github.com/pypa/manylinux), which is CentOS 5 based build environment for [Python wheel](https://www.python.org/dev/peps/pep-0513/), to maximize binary portability. But it requires GNU OpenMP instead of Intel OpenMP at build time because `iomp5` has a reference to `sched_getcpu@GLIBC_2.6` which is not supported in CentOS 5's glibc (version `2.5`).

```
# export LD_LIBRARY_PATH=/usr/local/gcc-4.9.4/lib64:/usr/local/gcc-4.9.4/lib:/usr/local/lib64:/usr/local/lib
# cmake28 -DCMAKE_C_COMPILER=/usr/local/gcc-4.9.4/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/gcc-4.9.4/bin/g++ ..
# make
Linking CXX shared library libmkldnn.so
...
[ 45%] Built target mkldnn
Scanning dependencies of target simple-net-c
[ 45%] Building C object examples/CMakeFiles/simple-net-c.dir/simple_net.c.o
Linking C executable simple-net-c
../../external/mklml_lnx_2019.0.20180710/lib/libiomp5.so: undefined reference to `sched_getcpu@GLIBC_2.6'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/simple-net-c] Error 1
make[1]: *** [examples/CMakeFiles/simple-net-c.dir/all] Error 2
make: *** [all] Error 2
```

I'd like to:

1. Use `gomp` when building MKL-DNN
2. Use `iomp5` at runtime

I digged into CMake files but I can't find an option to enable `mklml_gnu` and `gomp` at build time. Could you please tell me how to do it?

**Comment by vpirogov** [comment]
The build system does not have a knob to build Intel MKL-DNN with libmklml_gnu. Probably the only option as of now is patching the CMake files. I'll consider this to be a feature request. If you decide to go through the exercise of adding the knob yourself we would appreciate a pull request.

You should be able to use libiom5 at runtime with the standard build. The libiomp5 and libgomp are ABI compatible and can be used interchangeably as long as only one is initialized.

**Comment by okapies** [comment]
Thanks! I’ll try it.

**Comment by okapies** [comment]
I think here is another option to remove a tiny dependency to glibc 2.6 from iomp5. It makes easier to bundle MKL-DNN to Python wheel which standardized by [PEP 513](https://www.python.org/dev/peps/pep-0513/). What do you think?
