### ISSUE TITLE
Documentation Request: mklml DLL depends on MSVCR120.dll

### ISSUE THREAD

**Issue by nehaljwani** [intel/mkl-dnn#316]
Hello Intel,

The mklml DLL depends on MSVCR120.dll which comes from Visual Studio 2013 RunTime (which can be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=40784 or from https://repo.anaconda.com/pkgs/main/win-64/vs2013_runtime-12.0.21005-1.tar.bz2 [`conda install vs2013_runtime`] ). Could this information please be documented somewhere? Otherwise users who try to use a library linking to this DLL on a clean slate Windows VM, might feel betrayed :stuck_out_tongue_winking_eye: 

```
dumpbin /dependents C:\Users\nwani\Downloads\mklml_win_2019.0.20180710\lib\mklml.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\nwani\Downloads\mklml_win_2019.0.20180710\lib\mklml.dll

File Type: DLL

  Image has the following dependencies:

    MSVCR120.dll
    KERNEL32.dll
    libiomp5md.dll

  Summary

       E5000 .data
        1000 .data1
       CF000 .pdata
      702000 .rdata
        E000 .reloc
        1000 .rsrc
     6C91000 .text
        1000 .tls
        1000 _RDATA
```

**Comment by nehaljwani** [comment]
This issue has been closed, but I don't see mention of vs2013 runtime at the linked web page: https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2019-system-requirements

**Comment by vpirogov** [comment]
There are multiple ways to build Intel MKL-DNN and each of these will result in different set of runtime dependencies depending on specific components used and their corresponding versions. What you are observing with mklml.dll (an optional component) is just one of the possible scenarios. It seems impractical to list all the possible runtime dependencies.

I added the list of optional components that can be used in Intel MKL-DNN build along with a warning that these may affect runtime dependencies of the library.

**Comment by vpirogov** [comment]
We looked into this issue further and it turns out that this is a defect: Intel MKL small libraries should not have an explicit dependency on MSVS runtime. The defect is reported to Intel MKL team.

**Comment by vpirogov** [comment]
This issue is addressed in [the latest version of Intel MKL small libraries](https://github.com/intel/mkl-dnn/releases/download/v0.18/mklml_win_2019.0.3.20190220.zip).
