### ISSUE TITLE
Tensorflow with MKL Very Slow

### ISSUE THREAD

**Issue by zealthinker** [intel/mkl-dnn#317]
I am trying to reduce the time taken by an LSTM model using MKL. I use Tensorflow 1.10.0. I have give information about configuration I am using below. It will be great, if you can help me improve the speed of my model. Please let me know what more information you need. Thanks a lot!

* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt ida

* OS version (`uname -a`)
Linux ip-172-31-24-72 4.14.67-66.56.amzn1.x86_64 #1 SMP Tue Sep 4 22:03:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Compiler version (`gcc --version`)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

os.environ['OMP_NUM_THREADS'] = '32'
os.environ['KMP_BLOCKTIME'] = '0'
os.environ['KMP_AFFINITY'] = 'granularity=fine,verbose,compact,1,0'
K.set_image_data_format('channels_first')
config = tf.ConfigProto()
config.inter_op_parallelism_threads = 1
config.intra_op_parallelism_threads = 32
session = tf.Session(config=config)
K.set_session(session)

**Comment by mgouicem** [comment]
Hi @zealthinker.
Your performance issue seems to be related to MKL's integration into Tensorflow. I would recommend you to raise your issue to the Tensorflow developpers (https://github.com/tensorflow/tensorflow/issues).

I will close this issue but if you have an exact instance of MKL-DNN primitive that have lower performance than expected, please feel free to open another issue with this instance.

Thanks

**Comment by vpirogov** [comment]
Tagging @agramesh1, who works on Tensorflow enabling.
