### ISSUE TITLE
[RFC] `ARCH_OPT_FLAGS` should be disabled by default

### ISSUE THREAD

**Issue by okapies** [intel/mkl-dnn#321]
MKL-DNN has an optimization option `ARCH_OPT_FLAGS` as [described](https://github.com/intel/mkl-dnn/blob/a147082ce98243af386cc7d6498fb6ab11fb98ee/cmake/options.cmake#L53-L71) below:

```cmake
set(ARCH_OPT_FLAGS "HostOpts" CACHE STRING
    "specifies compiler optimization flags (see below for more information).
    If empty default optimization level would be applied which depends on the
    compiler being used.
    - For Intel(R) C++ Compilers the default option is `-xHOST` which instructs
      the compiler to generate the code for the architecture where building is
      happening. This option would not allow to run the library on older
      architectures.
    - For GNU* Compiler Collection version 5 and newer the default options are
      `-march=native -mtune=native` which behaves similarly to the descriprion
      above.
    - For all other cases there are no special optimizations flags.
    If the library is to be built for generic architecture (e.g. built by a
    Linux distributive maintainer) one may want to specify ARCH_OPT_FLAGS=\"\"
    to not use any host specific instructions")
```

But it's default value cause a problem when we build and distribute MKL-DNN binary in some situation.

For example, GCC 5 generates newer CPU instructions supported by the detected processors *even if* `as` (assembler) in older `binutils` in your machine doesn't support them. Actually I got the following errors in CentOS 6 with manually installed GCC 5.5.

```bash
# make
[  1%] Building CXX object src/CMakeFiles/mkldnn.dir/common/batch_normalization.cpp.o
/tmp/ccs0bO1c.s: Assembler messages:
/tmp/ccs0bO1c.s:211: Error: suffix or operands invalid for `vpsrlq'
/tmp/ccs0bO1c.s:212: Error: suffix or operands invalid for `vpmovsxdq'
/tmp/ccs0bO1c.s:213: Error: no such instruction: `vextracti128 $0x1,%ymm2,%xmm2'
/tmp/ccs0bO1c.s:214: Error: suffix or operands invalid for `vpmuludq'
/tmp/ccs0bO1c.s:215: Error: suffix or operands invalid for `vpsrlq'
/tmp/ccs0bO1c.s:216: Error: suffix or operands invalid for `vpmuludq'
/tmp/ccs0bO1c.s:217: Error: suffix or operands invalid for `vpmovsxdq'
...
```

A similar issue was also reported in [OpenCV project](https://github.com/opencv/opencv/issues/11120).

It also might be a problem especially for building an application using MKL-DNN on virtualization environment such like Travis and CircleCI which run on EC2 or GCE, because we can't know which kind of processor is used in advance. It has a chance to generate a non-portable binary unintentionally and randomly, and it must be hard to debug.

With these reasons in mind, I think `ARCH_OPT_FLAGS` should be disabled by default, or define a reasonable *fixed* default value (e.g. `-mavx` for AVX instructions) by clarifying hardware requirements. What do you think about it?

**Comment by saudet** [comment]
BTW, we can easily use GCC 6 or 7 on CentOS 6 with https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/ or https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/, which should support pretty much all we need on recent architectures.

**Comment by okapies** [comment]
Yes, simply upgrading `binutils` is the solution for the former case. I concern about the case a building environment is different from a running environment.

**Comment by emfomenk** [comment]
Hi @okapies,

Yeah, I would probably agree with that it makes sense to be more robust w.r.t. to the architecture we support when default build settings are chosen. On the other hand we are performance library and use all the possibilities to get the best performance.

So let me talk to the team and come back to you.
But whatever the decision would be, we will definitely have to proper document current behavior. So thanks for noting that issue!

**Comment by rsdubtso** [comment]
Since there is a clear workaround (pass -DOPT_ARCH_FLAGS="") that can be applied during packaging, I'm inclined to close this one as will not fix. (And the binutils situations is clearly an Ubuntu bug...).

**Comment by rsdubtso** [comment]
Leaving this open until we update the README
