### ISSUE TITLE
segfault with 3 output channel convolution

### ISSUE THREAD

**Issue by vikramambrose** [intel/mkl-dnn#323]
mkldnn segfaults when running a convolution with 64 input channels and 3 output channels. I was able to reproduce the segfault in the example/simple_net.c provided as well.

To reproduce the segfault, go to example/simple_net.c and make the following changes;

Src dimension  BATCH, 64, 227, 227
Dst dimension BATCH, 3, 55, 55
Weights dimension 3, 64, 11, 11
bias size 3
Pool dst size to BATCH, 3, 27,27

**Comment by ankalinin** [comment]
Thanks for noting this issue!
I able to reproduce this crash.  I will take a look.

**Comment by tprimak** [comment]
Fixed by [dfbc444da38b17cd39a8d1bd7146854fd0b62cac](https://github.com/intel/mkl-dnn/commit/dfbc444da38b17cd39a8d1bd7146854fd0b62cac)
