### ISSUE TITLE
default-constructed POD issue.

### ISSUE THREAD

**Issue by kruus** [intel/mkl-dnn#324]
Please check my understanding, but calling the default constructor for a 'C' POD type allows a C++11 compiler to do nothing, which I interpret as potentially leaving garbage values (depending on what your compiler decides to do).  This actually happens for one of my compilers, and causes errors arising from `zero_md()` that causes various examples and tests to fail.  On these systems, forcing value initialization by changing the `()` to `{}`, in both `type_helpers.cpp` and `mkldnn.hpp` makes things work smoothly. Empty {} does not trigger the unitialized struct values warning [which I like].  I don't *think* what I'm seeing is a bug in my C++11 compiler.

In some tests, the failure only occurred because of some debug printout, suggesting the use of unitialized struct values is sometimes no problem (for example, intentionally/optionally unused memory regions). So I would also suggest shunting (at least in release versions) the `assert`s in `mkldnn_debug.cpp` to a NOP.  It seems reasonable that official debug print routines should make a good effort to never fail.

There is perhaps an argument for allowing uninitialized values in POD structs, but to check mkl-dnn for correctness under gcc I guess I would have to memset them to garbage to simulate what other compilers seem allowed to do! Uggh.  So many things start going bad. Safer to fully initialize them.

**Comment by rsdubtso** [comment]
@emfomenk, I think `auto x = T();` implies [value initialization](https://en.cppreference.com/w/cpp/language/value_initialization). For PODs this means 
> 1) if T is a class type with no default constructor or with a user-provided or deleted default constructor, the object is default-initialized;

The [default initialization](https://en.cppreference.com/w/cpp/language/default_initialization) documentation says:

> The effects of default initialization are:
> * if T is a non-POD (until C++11) class type, the constructors are considered and subjected to overload resolution against the empty argument list. The constructor selected (which is one of the default constructors) is called to provide the initial value for the new object;
> * if T is an array type, every element of the array is default-initialized;
> * otherwise, nothing is done: the objects with automatic storage duration (and their subobjects) are initialized to indeterminate values.

I think it is the last bullet that applies to `auto x = T(); // T is a POD`. I'm going to try msan on all our tests and see what comes out of it. @kruus : please do let me know if there is a test you want me to try.

**Comment by emfomenk** [comment]
@rsdubtso, I am still not convinced.

For me we are in the case 2) of (since c++11):

> 2) if T is a class type with a default constructor that is neither user-provided nor deleted (that is, it may be a class with an implicitly-defined or defaulted default constructor), the object is zero-initialized and then it is default-initialized if it has a non-trivial default constructor;
	(since C++11)

There is also a **Notes** section on [value initialization](https://en.cppreference.com/w/cpp/language/value_initialization) page you sent, which says:

> Since C++11, value-initializing a class without a user-provided constructor, which has a member of a class type with a user-provided constructor zeroes out the member before calling its constructor:...

It is not directly applicable here, but also allows to conclude that in C++11 `T()` would zero-initialize the POD members.

**Comment by rsdubtso** [comment]
@emfomenk: just to document it: you are right.

@kruus: this has not (completely) fallen through the cracks. I'm running some tests, but they are taking longer than expected.

**Comment by rsdubtso** [comment]
Bumping this issue. @kruus, there are quite a few things in the latest master that I've fixed after enabling Clang sanitizers for MKL-DNN. Can you please check that the issue still persists?

**Comment by kruus** [comment]
Thanks for the discussion. I agree that mkl-dnn code should be left as is.  II conclude it's a compiler issue on my end.  I also ran some tests, and looking at assembler outputs found a case where the same `T()` initialization *was* be zero initialized in `main` as per @emfomenk's comment, but *failed* to be zeroed within a function. Very fishy. So this sighting is a bug report there, not an issue here.

I'm busy using gtests and benchdnn to look at the performance of low-level, hand-coded primitives for the Aurora vector processor lately, so it may be a few weeks before my next upstream merge. I'm liking what I see on master, and every merge seems to get easier (fewer workarounds on my end).
