### ISSUE TITLE
Something has changed in the last commits ?

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#326]
Hi,

I'm using mkl-dnn in my convolution layer for all strided and kernel 1x1 convolutions.
Everything was working 3 days ago. After committing the latest changes in mkl-dnn to my repo (with support for Intel TBB) and rebuilding my code as I always do, all my trained models are working as before except the trained weights are not trained anymore in the sense the model act like an untrained one when testing. Nothing in the non mkl-dnn code  has changed to explain this strange behaviour.
In all the convolutions I use a fixed nchw input/output format and oihw format for the weights.
Is it possible there is something changed in the behaviour of mkl-dnn when using convolutions this way?

thanks

-----------------------------------------------------------------------------

### Environment
* Intel Haswell
* Windows 10 x64
* Visual Studio 2017 
build with openmp and linked with libiomp5md.lib;mklml.lib
excluding vcomp.lib

**Comment by vpirogov** [comment]
TBB support included massive changes related to threading, though the configuration you describe is covered in validation. Could you please run MKL-DNN tests and see whether any fail in your configuration?

**Comment by emfomenk** [comment]
@zeno40,

Could you please dump the cmake output?
Also could you please specify the exact hardware?

**Comment by zeno40** [comment]
cmake output:
CMake Deprecation Warning at CMakeLists.txt:21 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.17763.
CMAKE_BUILD_TYPE is unset, defaulting to Release
Detecting Intel(R) MKL: trying mklml_intel
Intel(R) MKL: include C:/Users/dhaen/Downloads/mkl-dnn/external/mklml_win_2019.0.20180710/include
Intel(R) MKL: lib C:/Users/dhaen/Downloads/mkl-dnn/external/mklml_win_2019.0.20180710/lib/mklml.lib
Intel(R) MKL: OpenMP lib C:/Users/dhaen/Downloads/mkl-dnn/external/mklml_win_2019.0.20180710/lib/libiomp5md.lib
Intel(R) MKL: dll C:/Users/dhaen/Downloads/mkl-dnn/external/mklml_win_2019.0.20180710/lib/mklml.dll
Intel(R) MKL: OpenMP dll C:/Users/dhaen/Downloads/mkl-dnn/external/mklml_win_2019.0.20180710/lib/libiomp5md.dll
VTune profiling environment is unset
Configuring done

Hardware: Intel Haswell Devils canyon
OS: Windows 10/VS2017

**Comment by emfomenk** [comment]
For CPU -- how many cores do you have?

// still cannot reproduce the issue on my side...

**Comment by zeno40** [comment]
A devils Canyon has 4 cores and 8 threads supporting AVX2

build output VS2017:
1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
1>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/src/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/examples/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/gtest/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/benchdnn/CMakeFiles/generate.stamp is up-to-date.
2>------ Rebuild All started: Project: mkldnn_gtest, Configuration: Release x64 ------
3>------ Rebuild All started: Project: mkldnn, Configuration: Release x64 ------
4>------ Skipped Rebuild All: Project: RUN_TESTS, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Rebuild All: Project: doc, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
2>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/gtest/CMakeLists.txt
2>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/gtest/CMakeFiles/generate.stamp is up-to-date.
2>gtest-all.cc
3>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/src/CMakeLists.txt
3>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/src/CMakeFiles/generate.stamp is up-to-date.
3>batch_normalization.cpp
3>convolution.cpp
3>convolution_relu.cpp
3>deconvolution.cpp
3>eltwise.cpp
3>engine.cpp
3>inner_product.cpp
3>lrn.cpp
3>memory.cpp
3>memory_desc_wrapper.cpp
3>mkldnn_debug.cpp
3>pooling.cpp
3>primitive.cpp
3>primitive_attr.cpp
3>primitive_desc.cpp
3>primitive_iterator.cpp
3>query.cpp
3>reorder.cpp
3>rnn.cpp
3>scratchpad.cpp
3>softmax.cpp
3>stream.cpp
3>utils.cpp
3>verbose.cpp
3>cpu_barrier.cpp
3>cpu_batch_normalization_utils.cpp
3>cpu_concat.cpp
3>cpu_engine.cpp
3>cpu_memory.cpp
3>cpu_reducer.cpp
3>cpu_reorder.cpp
3>cpu_sum.cpp
3>gemm.cpp
3>gemm_utils.cpp
3>jit_avx512_common_gemm_f32.cpp
3>jit_avx_gemm_f32.cpp
3>ref_gemm.cpp
3>gemm_convolution.cpp
3>gemm_convolution_utils.cpp
3>gemm_inner_product.cpp
3>gemm_u8s8s32x_convolution.cpp
3>gemm_u8s8s32x_inner_product.cpp
2>mkldnn_gtest.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\gtest\Release\mkldnn_gtest.lib
3>jit_avx2_1x1_conv_kernel_f32.cpp
3>jit_avx2_1x1_convolution.cpp
3>jit_avx2_conv_kernel_f32.cpp
3>jit_avx2_convolution.cpp
3>jit_avx512_common_1x1_conv_kernel.cpp
3>jit_avx512_common_1x1_convolution.cpp
3>jit_avx512_common_conv_kernel.cpp
3>jit_avx512_common_conv_winograd_kernel_f32.cpp
3>jit_avx512_common_convolution.cpp
3>jit_avx512_common_convolution_winograd.cpp
3>jit_avx512_common_lrn.cpp
3>jit_avx512_core_fp32_wino_conv_2x3.cpp
3>jit_avx512_core_fp32_wino_conv_4x3.cpp
3>jit_avx512_core_fp32_wino_conv_4x3_kernel.cpp
3>jit_avx512_core_i8i8_pooling.cpp
3>jit_avx512_core_u8s8s32x_1x1_conv_kernel.cpp
3>jit_avx512_core_u8s8s32x_1x1_convolution.cpp
3>jit_avx512_core_u8s8s32x_conv_kernel.cpp
3>jit_avx512_core_u8s8s32x_convolution.cpp
3>jit_avx512_core_u8s8s32x_wino_convolution.cpp
3>jit_sse42_1x1_conv_kernel_f32.cpp
3>jit_sse42_1x1_convolution.cpp
3>jit_sse42_conv_kernel_f32.cpp
3>jit_sse42_convolution.cpp
3>jit_transpose_src_utils.cpp
3>jit_uni_batch_normalization.cpp
3>jit_uni_dw_conv_kernel_f32.cpp
3>jit_uni_dw_convolution.cpp
3>jit_uni_eltwise.cpp
3>jit_uni_lrn.cpp
3>jit_uni_lrn_kernel_f32.cpp
3>jit_uni_pool_kernel_f32.cpp
3>jit_uni_pooling.cpp
3>jit_uni_reorder.cpp
3>jit_uni_reorder_utils.cpp
3>nchw_pooling.cpp
3>ncsp_batch_normalization.cpp
3>nhwc_pooling.cpp
3>nspc_batch_normalization.cpp
3>ref_batch_normalization.cpp
3>ref_convolution.cpp
3>ref_deconvolution.cpp
3>ref_eltwise.cpp
3>ref_inner_product.cpp
3>ref_lrn.cpp
3>ref_pooling.cpp
3>ref_rnn.cpp
3>ref_softmax.cpp
3>simple_concat.cpp
3>simple_sum.cpp
3>   Creating library C:/Users/dhaen/Downloads/mkl-dnn/build/src/Release/mkldnn.lib and object C:/Users/dhaen/Downloads/mkl-dnn/build/src/Release/mkldnn.exp
3>mkldnn.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\src\Release\mkldnn.dll
6>------ Rebuild All started: Project: test_inner_product_forward, Configuration: Release x64 ------
7>------ Rebuild All started: Project: test_lrn_backward, Configuration: Release x64 ------
8>------ Rebuild All started: Project: test_lrn_forward, Configuration: Release x64 ------
9>------ Rebuild All started: Project: api-c, Configuration: Release x64 ------
10>------ Rebuild All started: Project: benchdnn, Configuration: Release x64 ------
11>------ Rebuild All started: Project: test_convolution_forward_s16s16s32, Configuration: Release x64 ------
12>------ Rebuild All started: Project: test_batch_normalization, Configuration: Release x64 ------
13>------ Rebuild All started: Project: test_memory, Configuration: Release x64 ------
11>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
6>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
6>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
11>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
10>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/benchdnn/CMakeLists.txt
7>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
11>main.cpp
6>main.cpp
7>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
10>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/benchdnn/CMakeFiles/generate.stamp is up-to-date.
6>test_inner_product_forward.cpp
11>test_convolution_forward_s16s16s32.cpp
7>main.cpp
7>test_lrn_backward.cpp
10>benchdnn.cpp
10>bench_bnorm.cpp
10>bnorm_aux.cpp
10>ref_bnorm.cpp
10>bench_conv.cpp
10>bench_deconv.cpp
10>conv_aux.cpp
10>deconv.cpp
8>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
10>ref_conv.cpp
8>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
10>ref_wino.cpp
10>dnn_types.cpp
10>bench_ip.cpp
10>ip.cpp
10>ip_aux.cpp
10>ref_ip.cpp
10>mkldnn_common.cpp
9>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/CMakeLists.txt
10>mkldnn_debug.cpp
10>bench_reorder.cpp
10>reorder.cpp
10>reorder_aux.cpp
10>bench_rnn.cpp
10>ref_rnn.cpp
10>rnn.cpp
10>rnn_aux.cpp
10>self.cpp
8>main.cpp
9>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/CMakeFiles/generate.stamp is up-to-date.
8>test_lrn_forward.cpp
12>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
12>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
13>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
9>api.c
13>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
12>main.cpp
10>bnorm.cpp
13>main.cpp
12>test_batch_normalization.cpp
13>test_memory.cpp
6>test_inner_product_forward.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_inner_product_forward.exe
9>api-c.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\Release\api-c.exe
14>------ Rebuild All started: Project: test_mkldnn_threading, Configuration: Release x64 ------
10>perf_report.cpp
11>test_convolution_forward_s16s16s32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_forward_s16s16s32.exe
14>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
15>------ Rebuild All started: Project: test_pooling_forward, Configuration: Release x64 ------
14>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
14>main.cpp
15>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
14>test_mkldnn_threading.cpp
15>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
10>common.cpp
15>main.cpp
15>test_pooling_forward.cpp
7>test_lrn_backward.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_lrn_backward.exe
16>------ Rebuild All started: Project: test_relu, Configuration: Release x64 ------
17>------ Rebuild All started: Project: test_reorder, Configuration: Release x64 ------
16>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
16>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
17>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
17>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
16>main.cpp
17>main.cpp
16>test_relu.cpp
17>test_reorder.cpp
10>cfg.cpp
8>test_lrn_forward.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_lrn_forward.exe
10>conv.cpp
18>------ Rebuild All started: Project: test_softmax_backward, Configuration: Release x64 ------
18>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
18>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
10>perf_report.cpp
18>main.cpp
18>test_softmax_backward.cpp
14>test_mkldnn_threading.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_mkldnn_threading.exe
19>------ Rebuild All started: Project: test_softmax_forward, Configuration: Release x64 ------
12>test_batch_normalization.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_batch_normalization.exe
19>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
20>------ Rebuild All started: Project: test_concat, Configuration: Release x64 ------
19>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
10>cfg.cpp
20>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
20>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
19>main.cpp
19>test_softmax_forward.cpp
20>main.cpp
20>test_concat.cpp
16>test_relu.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_relu.exe
21>------ Rebuild All started: Project: test_sum, Configuration: Release x64 ------
10>perf_report.cpp
21>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
21>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
21>main.cpp
21>test_sum.cpp
10>cfg.cpp
10>perf_report.cpp
13>test_memory.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_memory.exe
22>------ Rebuild All started: Project: test_convolution_backward_data_f32, Configuration: Release x64 ------
22>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
22>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
15>test_pooling_forward.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_pooling_forward.exe
23>------ Rebuild All started: Project: test_convolution_backward_data_s16s16s32, Configuration: Release x64 ------
17>test_reorder.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_reorder.exe
22>main.cpp
24>------ Rebuild All started: Project: test_convolution_backward_weights_f32, Configuration: Release x64 ------
22>test_convolution_backward_data_f32.cpp
19>test_softmax_forward.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_softmax_forward.exe
24>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
25>------ Rebuild All started: Project: test_convolution_backward_weights_s16s16s32, Configuration: Release x64 ------
24>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
23>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
18>test_softmax_backward.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_softmax_backward.exe
23>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
26>------ Rebuild All started: Project: test_convolution_format_any, Configuration: Release x64 ------
25>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
24>main.cpp
24>test_convolution_backward_weights_f32.cpp
26>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
25>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
26>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
23>main.cpp
23>test_convolution_backward_data_s16s16s32.cpp
25>main.cpp
26>main.cpp
26>test_convolution_format_any.cpp
25>test_convolution_backward_weights_s16s16s32.cpp
20>test_concat.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_concat.exe
27>------ Rebuild All started: Project: test_convolution_forward_f32, Configuration: Release x64 ------
27>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
10>perf_report.cpp
27>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
27>main.cpp
27>test_convolution_forward_f32.cpp
22>test_convolution_backward_data_f32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_backward_data_f32.exe
28>------ Rebuild All started: Project: test_pooling_backward, Configuration: Release x64 ------
21>test_sum.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_sum.exe
29>------ Rebuild All started: Project: test_convolution_forward_u8s8fp, Configuration: Release x64 ------
28>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
25>test_convolution_backward_weights_s16s16s32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_backward_weights_s16s16s32.exe
30>------ Rebuild All started: Project: test_convolution_forward_u8s8s32, Configuration: Release x64 ------
10>bnorm.cpp
28>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
29>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
30>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
29>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
30>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
28>main.cpp
28>test_pooling_backward.cpp
29>main.cpp
30>main.cpp
29>test_convolution_forward_u8s8fp.cpp
30>test_convolution_forward_u8s8s32.cpp
23>test_convolution_backward_data_s16s16s32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_backward_data_s16s16s32.exe
31>------ Rebuild All started: Project: test_convolution_relu_forward_f32, Configuration: Release x64 ------
31>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
31>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
31>main.cpp
31>test_convolution_relu_forward_f32.cpp
24>test_convolution_backward_weights_f32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_backward_weights_f32.exe
32>------ Rebuild All started: Project: test_convolution_relu_forward_neg_slope_f32, Configuration: Release x64 ------
10>common.cpp
32>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
32>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
27>test_convolution_forward_f32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_forward_f32.exe
32>main.cpp
33>------ Rebuild All started: Project: test_convolution_relu_forward_s16s16s32, Configuration: Release x64 ------
32>test_convolution_relu_forward_neg_slope_f32.cpp
26>test_convolution_format_any.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_format_any.exe
34>------ Rebuild All started: Project: test_deconvolution, Configuration: Release x64 ------
29>test_convolution_forward_u8s8fp.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_forward_u8s8fp.exe
35>------ Rebuild All started: Project: test_eltwise, Configuration: Release x64 ------
30>test_convolution_forward_u8s8s32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_forward_u8s8s32.exe
36>------ Rebuild All started: Project: test_gemm, Configuration: Release x64 ------
33>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
34>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
33>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
10>conv.cpp
35>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
34>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
35>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
36>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
36>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
33>main.cpp
34>main.cpp
35>main.cpp
34>test_deconvolution.cpp
33>test_convolution_relu_forward_s16s16s32.cpp
35>test_eltwise.cpp
36>main.cpp
28>test_pooling_backward.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_pooling_backward.exe
36>test_gemm.cpp
37>------ Rebuild All started: Project: test_iface_attr, Configuration: Release x64 ------
10>benchdnn.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\benchdnn\Release\benchdnn.exe
38>------ Rebuild All started: Project: test_iface_pd_iter, Configuration: Release x64 ------
37>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
37>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
38>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
38>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
37>main.cpp
37>test_iface_attr.cpp
36>test_gemm.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_gemm.exe
38>main.cpp
39>------ Rebuild All started: Project: test_inner_product_backward_data, Configuration: Release x64 ------
38>test_iface_pd_iter.cpp
31>test_convolution_relu_forward_f32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_relu_forward_f32.exe
40>------ Rebuild All started: Project: test_inner_product_backward_weights, Configuration: Release x64 ------
39>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
39>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
40>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/tests/gtests/CMakeLists.txt
40>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/tests/gtests/CMakeFiles/generate.stamp is up-to-date.
33>test_convolution_relu_forward_s16s16s32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_relu_forward_s16s16s32.exe
40>main.cpp
40>test_inner_product_backward_weights.cpp
34>test_deconvolution.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_deconvolution.exe
41>------ Skipped Rebuild All: Project: test_benchdnn_bnorm, Configuration: Release x64 ------
41>Project not selected to build for this solution configuration 
42>------ Skipped Rebuild All: Project: test_benchdnn_conv, Configuration: Release x64 ------
42>Project not selected to build for this solution configuration 
43>------ Skipped Rebuild All: Project: test_benchdnn_deconv, Configuration: Release x64 ------
43>Project not selected to build for this solution configuration 
39>main.cpp
44>------ Skipped Rebuild All: Project: test_benchdnn_ip, Configuration: Release x64 ------
44>Project not selected to build for this solution configuration 
39>test_inner_product_backward_data.cpp
45>------ Skipped Rebuild All: Project: test_benchdnn_regression, Configuration: Release x64 ------
45>Project not selected to build for this solution configuration 
46>------ Skipped Rebuild All: Project: test_benchdnn_reorder, Configuration: Release x64 ------
46>Project not selected to build for this solution configuration 
47>------ Skipped Rebuild All: Project: test_benchdnn_rnn, Configuration: Release x64 ------
47>Project not selected to build for this solution configuration 
48>------ Skipped Rebuild All: Project: test_conv, Configuration: Release x64 ------
48>Project not selected to build for this solution configuration 
37>test_iface_attr.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_iface_attr.exe
32>test_convolution_relu_forward_neg_slope_f32.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_convolution_relu_forward_neg_slope_f32.exe
35>test_eltwise.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_eltwise.exe
40>test_inner_product_backward_weights.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_inner_product_backward_weights.exe
38>test_iface_pd_iter.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_iface_pd_iter.exe
39>test_inner_product_backward_data.vcxproj -> C:\Users\dhaen\Downloads\mkl-dnn\build\tests\gtests\Release\test_inner_product_backward_data.exe
49>------ Rebuild All started: Project: ALL_BUILD, Configuration: Release x64 ------
49>Building Custom Rule C:/Users/dhaen/Downloads/mkl-dnn/CMakeLists.txt
49>CMake does not need to re-run because C:/Users/dhaen/Downloads/mkl-dnn/build/CMakeFiles/generate.stamp is up-to-date.
50>------ Skipped Rebuild All: Project: INSTALL, Configuration: Release x64 ------
50>Project not selected to build for this solution configuration 
========== Rebuild All: 39 succeeded, 0 failed, 11 skipped ==========

**Comment by emfomenk** [comment]
:) great, thx for the update!

**Comment by zeno40** [comment]
For your information: the same is happening when compiling mkl-dnn with /permissive- conformance mode and the default C++ Language Standard.
