### ISSUE TITLE
Conversion of memory format `nc` to `oi`

### ISSUE THREAD

**Issue by okdshin** [intel/mkl-dnn#328]
Hi. I would like to implement `Gemm` operator of ONNX by using inner product primitive.
`Gemm` takes two inputs which may not be fixed parameter of model. In other words, their format may be `nc`.
While, inner product primitive takes two inputs. One has `nc` and the other has `oi` (or `io`).
Here is my question.
How should I change the format of the input memory `nc` to `oi`?
I couldn't find any test of reorder primitive which do from `nc` to `oi`.

To do that, can I simply change memory's get_primitive_desc().desc().data.format `nc` to `oi`?
Or, can I make `oi` memory from `nc` memory? They have same dims and share a buffer.

**Comment by vpirogov** [comment]
I would suggest that you use [mkldnn_sgemm](http://intel.github.io/mkl-dnn/group__c__api__blas.html#gaa1095fb139525d51eab45ccadf426ae5) function to implement GEMM operator for ONNX. InnerProduct has different semantics from the general purpose GEMM API and should not be used to replace it.

**Comment by okdshin** [comment]
Thank you @vpirogov ! I didn't know that API.
`mkldnn_sgemm` seems independent from other primitive execution system in MKLDNN.
So I infer, to combinate it with other operator primitives, we have to interrupt primitive execution.
Can we optimize model execution in such a case?

**Comment by vpirogov** [comment]
MKL-DNN is a primitive-based library and it does not optimize model execution, so interrupting the stream should not be a concern. In MKL-DNN programming model the model level optimizations are happening on the application side. Typical approaches are:
1. Changing the data layouts to accomodate vectorization via reorders
2. Invoking fused operation APIs (example: convolution postops)
3. Replacing low-level operations by higher level APIs (example: RNN/LSTM/GRU cells)

**Comment by okdshin** [comment]
I got it. Thank you for your explanation.

**Comment by vpirogov** [comment]
Let us know if you have any other questions or encounter issues!
