### ISSUE TITLE
Very slow deconvolution primitive

### ISSUE THREAD

**Issue by VladX** [intel/mkl-dnn#329]
I'm using deconvolution primitive inside my network. There are only few of them, most of the layers are just regular convolutions.
According to performance measurements, calculation of deconvolution layers take around 97% of the inference time. I wonder, why this happens, since there only few deconv's and there are of the same size as convs (so should perform equally fast).

For example, when I run the full inference, I get this time: `0.34253 s`
When I replace all 4 deconvs with no-op and run inference again I get this time: `0.01172 s`
There are more than 30 convolutional primitives in total, not counting deconvs. Even though, the inference is very fast without the deconv alone.
The performance with deconvolution went down considerably.

This is the output with `MKLDNN_VERBOSE=1`:
This is for convolutional block
```
mkldnn_verbose,exec,convolution,gemm:jit,forward_inference,fsrc:nchw fwei:goihw fbia:undef fdst:nchw,alg:convolution_direct,mb1_g16ic16oc16_ih128oh128kh3sh1dh0ph1_iw96ow96kw3sw1dw0pw1,0.891846
mkldnn_verbose,exec,convolution,gemm:jit,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb1_g1ic16oc16_ih128oh128kh1sh1dh0ph0_iw96ow96kw1sw1dw0pw0,0.13501
```
for deconvolution
```
mkldnn_verbose,exec,deconvolution,ref:any,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:deconvolution_direct,mb1_g1ic32oc16_ih64oh128kh2sh2dh0ph0_iw48ow96kw2sw2dw0pw0,81.366
```
I don't want to attach the full log since it is very huge.

Would like to hear some suggestions on this.

```
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts flush_l1d

Linux desktop 4.18.8-2-MANJARO #1 SMP PREEMPT Sun Sep 16 08:34:49 UTC 2018 x86_64 GNU/Linux

gcc (GCC) 8.2.1 20180831

cmake version 3.12.1
```

**Comment by irinasok** [comment]
Hi,

Current deconvolution implementation will run reference code if created with specified format, for example "mkldnn_nchw" instead of "mkldnn_any". I think that is exactly what happened here, other than that deconvolution and bwd convolution use the same implementation and thus should give the same performance. The reason for such limitation is rooted in MKL-DNN implementation of memory formats and is likely to be fixed in future.
However, for best performance of all MKL-DNN primitives it is advised to create primitives with memory format "any", let primitive to decide which memory format is more performant and call reorders from user's data to memory layout requested by primitive.

**Comment by vpirogov** [comment]
As Irina noted Intel MKL-DNN programming model assumes that the data and weights are explicitly reordered to the format that works best for convolution, deconvolution and inner product primitives. This is implemented via the format:any placeholder.

You can use [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn) to measure performance of convolutions, deconvolutions, batch normalizations and reorders.

**Comment by vpirogov** [comment]
Intel MKL-DNN has a benchmark called [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn) that allows to reliably measure performance of reorders, convolutions, deconvolutions, and batch normalization.

**Comment by vpirogov** [comment]
Feel free to reopen this issue or submit a new one if you have any other questions.

**Comment by duli2012** [comment]
Just out of curiosity, what does "gemm:jit" mean here?

**Comment by duli2012** [comment]
@emfomenk  thanks!

**Comment by sfraczek** [comment]
Hi,
so does MKL-DNN have optimized jitted deconvolution if format::any is specified or not? I couldn't find specific info about it and I have to know if we can use it.

**Comment by emfomenk** [comment]
Deconvolution (fp32) uses corresponding convolution, so as long as `any` is passed the decovolution should pick the best available implementation, which is most of the cases would be jitted. Jitted version would work on `nChw8c` or `nChw16c` data formats.

Unfortunately `MKLDNN_VERBOSE` cannot show whether the implementation is jittted or not, but indirectly you can identify the jitted version by looking at the data format. I ran a simple deconv on AVX2 and got the following:

``` bash
$ ( MKLDNN_VERBOSE=1 ./tests/benchdnn/benchdnn --deconv mb32ic32oc32ih13kh3oh13ph1 )
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nchw out:f32_nChw8c,num:1,32x32x13x13,0.124023
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_goihw out:f32_blocked,num:1,1x32x32x3x3,0.0690918
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nchw out:f32_nChw8c,num:1,32x32x13x13,0.100098
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_x out:f32_x,num:1,32,0.00317383
mkldnn_verbose,exec,deconvolution,ref:any,forward_inference,fsrc:nChw8c fwei:blocked fbia:x fdst:nChw8c,alg:deconvolution_direct,mb32_g1ic32oc32_ih13oh13kh3sh1dh0ph1_iw13ow13kw3sw1dw0pw1,2.87183
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nChw8c out:f32_nchw,num:1,32x32x13x13,0.146973
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nChw8c out:f32_nchw,num:1,32x32x13x13,0.0390625
```

Note that data format is `nChw8c` which is expected for the jitted version.

**Comment by sfraczek** [comment]
Great! I thought it could be this way but I couldn't find a clue. :) Thanks for quick reply! This is good news.
