### ISSUE TITLE
How to import cuDNN GRU weights from training on GPU?

### ISSUE THREAD

**Issue by TFDoe** [intel/mkl-dnn#331]
I am new to MKL-DNN and trying to understand how to import weights (I trained the model with tensorflow on Nvidia GPUs). I have a broad question and a narrow question.

(1) Broad question: would it be possible to link to or provide an example of importing such weights and running an inference?

(2)  I am not able to understand how the weights vector is sized. I am looking at examples/simple_rnn.cpp line 187:

```
    std::vector<float> user_enc_bidir_wei_layer(
            enc_bidir_n_layers * 2 * feature_size * lstm_n_gates * feature_size,
            1.0f);
```

Is `user_enc_bidir_wei_layer` the vector that should hold the weights brought in from training to perform inference? If so, it seems like the size of this vector - if it should hold all the weights for the model - is too small compared to what I see resulting from the weights in Tensorflow's interface to cuDNN GRU. For a GRU one expects to have 3 * (n^2 + n * m + n) parameters per layer with n being the output dimension and m the input dimension. However, in the code (and I realize that is an LSTM example, but the concern is the same) it seems like the vector would have fewer parameters than expected given that formula. What am I missing? I am assuming you are working off the following implementation (based on what I see in this Git issue comment: https://github.com/intel/mkl-dnn/issues/218):

r = sigmoid(W_{ir} * x + b_{ir} + W_{hr} * h + b_{hr})  (Eqn1)
z = sigmoid(W_{iz} * x + b_{iz} + W_{hz} * h + b_{hz}) (Eqn 2)
n = tanh(W_{in} * x + b_{in} +  W_{hn} * (r ◦ h) + b_{hn}))
h' = (1 - z) ◦ n + z ◦ h

except with this modification (https://intel.github.io/mkl-dnn/group__c__api__types__generic.html#gaa27d43cdd1e439cc41a9580d23ce3e97 for mkldnn_gru_linear_before_reset ):
\[ c_t = tanh(W_c*x_t + b_{c_h} + r_t*(U_c*h_{t-1}+b_{c_h})) \]

Incidentally question (3) this documentation indicates that 4 biases are expected even though traditionally this is expressed as 6 biases. Am I right in assuming the equations for r and z above, which I designated Eqn1 and Eqn2, add the distinctly named biases to condense each to one bias so that the entire system uses 4 bias vectors?

Thanks for any help or further information.

**Comment by mgouicem** [comment]
Hi @TFDoe, 
(1) We have no example available unfortunately, but you can export weights from cuDNN, by using the [cudnnGetRNNLinLayerMatrixParams](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnGetRNNLinLayerMatrixParams) function. You can select which weights to export using the `pseudoLayer` and `linLayerID` parameters.
Note that as you export the weights gate by gate, you will have to put those in an MK-DNN memory with layout `ldgoi`.

(2) Each layer has 2 weight matrices and and 1 bias vector. Using your notations, `weights_layer` is of size `m * (n_gates * n)` (linLayerID in {0} for RNN, in {0..3} for lstm, in {0..2} for GRU), `weights_iter` is of size `n* (n_gates * n)` ((linLayerID in {1} for RNN, in {4..7} for lstm, in {3..5} for GRU)). The bias vector is of size `n_gates * n`.
If you sum these 3 sizes, you get the formula you provided `n_gates * (n^2 + n*m + n)`.

Note that we fuse the weights of several layers (even bidirectional). For example, for weights_layer, the total size will be `n_layer * n_directions * m * n_gates * n`.

(3) Yes this is exactly it. We assume that biases that can be summed prior to call the primitive are already summed.

**Comment by TFDoe** [comment]
Thank you @mgouicem for such a fast and complete answer. I think this gives me enough to continue working on this. I will follow-up if I need any clarification.

**Comment by vpirogov** [comment]
Feel free to reopen this issue or submit a new one if you have any other questions.
