### ISSUE TITLE
Sample code for using the post ops API.

### ISSUE THREAD

**Issue by pranavsharma** [intel/mkl-dnn#338]
I'm exploring the fusion of convolution and activation. I came across the [post API](https://intel.github.io/mkl-dnn/group__c__api__attributes__post__ops.html), but didn't find any sample code using it. Is there any same code you can point me to? Thanks!

**Comment by kwiersch** [comment]
The Int8 example uses postOps -- see [simple_net_int8.cpp#L106](https://github.com/intel/mkl-dnn/blob/master/examples/simple_net_int8.cpp#L106). Usage should be the same as for F32.

**Comment by pranavsharma** [comment]
Thanks! Let me give it a shot.

**Comment by kwiersch** [comment]
Closing, but feel free to re-open if you have any further question.
