### ISSUE TITLE
mkldnn vs mkl-dnn

### ISSUE THREAD

**Issue by manuelelucchi** [intel/mkl-dnn#339]
Hello, I have a very stupid question but I don't get it. Why is the code repo mostly c++, with hpp files, different methods signature and more things (e.g RNNs) where the headers you download with the lib from the release are completely different? You don't have mkldnn.h but mkl_dnn.h, no hpp headers, different methods etc. This is a lot confusing. From the intel website I understood that the one in this repo is the new mkl dnn while the one included in the standard mkl package is the old one, then why from the releases I can only download the old one?

Regards and thank you,
Manuele

**Comment by manuelelucchi** [comment]
Oh, now it's a lot clearer, thank you very much. In the Intel website they say that there is a version of MKL that is deprecated, is this referred to the MKL 2017 while 2019 and this one are supported right?

Thank you again
Manuele

**Comment by vpirogov** [comment]
I believe you are referring to [this](https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-whats-deprecated) deprecation notice. This notice is about Intel MKL, not Intel MKL-DNN and it announces deprecation of functionality in Intel MKL. There's no impact from this change to Intel MKL-DNN.

**Comment by vpirogov** [comment]
Closing the thread, please free to reopen if you have any further questions.
