### ISSUE TITLE
Viewing generated assembly 

### ISSUE THREAD

**Issue by masahi** [intel/mkl-dnn#340]
Hi, I am interested in viewing the generated assembly for convolution kernels to study how they work. Is there a way to dump generated code as a text file?

**Comment by igorsafo** [comment]
Hi @masahi.
you can specify MKLDNN_JIT_DUMP=1 before running your application. MKL-DNN will dump a binary file for each jit kernel generated during execution. You can find more details here: https://github.com/intel/mkl-dnn/blob/master/doc/perf_profile.md#dump-jit-kernels

**Comment by masahi** [comment]
Thanks! @igorsafo. Good to know such document exists. I was able to get asm with objdump.
