### ISSUE TITLE
[feature request] call intel-mkl through dlopen/dlsym

### ISSUE THREAD

**Issue by cdluminate** [intel/mkl-dnn#341]
This feature request doesn't need an issue template. Please allow me to delete it.

Some linux distributions have strict license requirement on the packages to be distributed. Specifically, linking a free software package against a non-free software is not prefered for many distributions including Debian. However, if we don't link mkl-dnn against mkl, only sub-optimal performance can be obtained. And if a user want the full performance, he or she has to compile the library again.

To tackle with this problem, it would be better for mkl-dnn to call mkl (or mklml) via dlopen/dlsym (or alike) mechanism. Ideally the feature I requested can be represented by the following pseudo code:

```
if found mklml:
    load and use mklml's symbols such as gemm as the default code branch
elif found mkl:
    load and use <ditto>
elif found any other performance library:
    load and use it
else:
    use mkl-dnn's native implementation.
```

Advantages:

1. Users don't need to compile mkl-dnn again in order to obtain the full performance. What they need to do is to install mkl or mklml to a proper place.
2. Distribution packages, such as Debian/Ubuntu package, can benefit from this mechanism. This mechanism makes full performance for distribution packages possible.

**Comment by cdluminate** [comment]
If this is applicable, Debian/Ubuntu users only need to do `apt install libmkldnn-dev intel-mkl` to gain the full performance without rebuilding anything.

**Comment by rsdubtso** [comment]
MKL-DNN is slowly gaining all functionality it needs to be completely standalone. It already has an `sgemm()` implementation and we are working an removing other dependencies. So I think that eventually this feature won't be necessary. Leaving this open to let others to chime in.

**Comment by vpirogov** [comment]
The feature request makes perfect sense in general. The direction that we are taking with Intel MKL-DNN though is providing full performance without dependency on non-free software (per definition of Free Software Foundation). So the dependency will go away completely in future releases.

**Comment by cdluminate** [comment]
@eLvErDe maybe you will be interested in this.

**Comment by eLvErDe** [comment]
Indeed, thanks for subscribing me

**Comment by cdluminate** [comment]
I wrote a simple test for comparing mkl-dnn's sgemm implementation with MKL's. My intel-mkl version is `2019.0.117`, while that of mkl-dnn is `0.17.1` . The result shows that MKL's sgemm is still 15% faster than mkl-dnn's.

```
~/D/i/i/d/tests ❯❯❯ g++ test-gemm-mkldnn.cc -lpthread -lm -ldl -lmkldnn
~/D/i/i/d/tests ❯❯❯ ./a.out 
(1/100) Elapsed 437.981 ms
(2/100) Elapsed 439.508 ms
(3/100) Elapsed 445.325 ms
(4/100) Elapsed 447.413 ms
(5/100) Elapsed 448.361 ms
~/D/i/i/d/tests ❯❯❯ g++ test-gemm.cc -I/usr/include/mkl -lmkl_rt -ltbb -lpthread -lm -ldl
~/D/i/i/d/tests ❯❯❯ ./a.out 
Sanity Test Error: 0.000000
(1/100) Elapsed 350.310 ms
(2/100) Elapsed 376.913 ms
(3/100) Elapsed 382.146 ms
(4/100) Elapsed 388.547 ms
(5/100) Elapsed 387.438 ms
```

Code can be found here: https://salsa.debian.org/science-team/intel-mkl/tree/master/debian/tests

**Comment by vpirogov** [comment]
Closing this issue as there's no plan for Intel MKL-DNN to continue relying on Intel MKL or other libraries. Current implementation is already self-contained with JIT versions of int8 and fp32 GEMM available.
