### ISSUE TITLE
Vcpkg Release?

### ISSUE THREAD

**Issue by manuelelucchi** [intel/mkl-dnn#347]
Hello everyone
Mkl-dnn is really interesting, but a bit tricky to build and link from scratch. Since it seems you don't create packages for it In release (it installs the old mkl-dnn) it would be awesome a release into the vcpkg system. At least you would have automatic build and link to your project, a better support for Visual Studio and a cross platform package manager

Regards, 
Manuele

**Comment by rsdubtso** [comment]
Hi Manuele,

Can you please elaborate? Have you tried creating a package following the [vcpkg example][https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md]? Does it work or we need to do something on the mkl-dnn side to make it work?

Best,
Roma

**Comment by manuelelucchi** [comment]
Hi Roma, I haven't tried yet but I think I will try tomorrow and I will let you know. Also, a bit off topic, I found this file in the Microsoft CNTK repo (that uses MKL DNN) and I think it could be very useful for Windows users like me that want easily use MKL (I tried it, it works perfectly)
https://github.com/Microsoft/CNTK/blob/master/Tools/devInstall/Windows/buildMklDnnVS17.bat

**Comment by rsdubtso** [comment]
I'm closing this since the discussion moved to to #353 . Feel free to reopen.
