### ISSUE TITLE
Does mkl-dnn not support int8 gemm？？

### ISSUE THREAD

**Issue by LitLeo** [intel/mkl-dnn#357]
Now the mkl-dnn supported int8 primitives are(https://intel.github.io/mkl-dnn/ex_int8_simplenet.html):
convolution
pooling
eltwise
sum
concat
reorder

Why does mkl-dnn not support int8 gemm primitive??  Or was I wrong?

**Comment by emfomenk** [comment]
Hi @LitLeo,

Currently Intel MKL-DNN relies on Intel MKL whenever it needs to run int8 gemm. See [cblas_gemm_s8u8s32](https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemm-1).

We are currently working towards adding this functionality to Intel MKL-DNN out-of-the-box, i.e. with no external dependency to Intel MKL. But that might take some time...

**Comment by LitLeo** [comment]
ok，I know……
Thank you for your reply
