### ISSUE TITLE
About Affinity's performence problem? Thank you

### ISSUE THREAD

**Issue by idealboy** [intel/mkl-dnn#362]
Here's the place for your question, suggestion, a feature request or brief
description of the problem. If you are submitting a defect report please fill
all the sections below. For everything else feel free to remove everything
below the line.

-----------------------------------------------------------------------------

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
Stepping:              2
CPU MHz:               1205.273
BogoMIPS:              4993.18
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47

* OS version (`uname -a`)
Linux yz2-mc-storm479.kscn 3.18.6-2.el7.centos.x86_64 #1 SMP Mon Oct 24 13:01:33 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`gcc --version`)

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

* MKLROOT value (`echo MKLROOT=$MKLROOT`)
* CMake version (`cmake --version`)
* CMake output log
* git hash (`git log -1 --format=%H`)

### Steps to reproduce
Please check that the issue is reproducible with the latest revision on
master. Include all the steps to reproduce the issue. A short C/C++ program
or modified unit tests demonstrating the issue will greatly help
with the investigation.

### Actual behavior

when I use MKLDnn in mxnet-1.3.x with MKLDnn,

I set environment variable: #export KMP_AFFINITY=compact,granularity=fine

I found that, the cpu load is low, and only several cpu are occupied.

When I not the export , then all cpu have a hight load

And I run a mxnet instance in each cpu(with it's cpu id), othe environment variable is such list:

export MXNET_CPU_PRIORITY_NTHREADS=1
export MXNET_CPU_WORKER_NTHREADS=10
export MXNET_SUBGRAPH_BACKEND=MKLDNN
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
export OpenBLAS_NUM_THREADS=1
export CUDA_VISIBLE_DEVICES=0
export MXNET_ENGINE_INFO=0

Thank you very much!

Below is the top indication(when set affinity):

![image](https://user-images.githubusercontent.com/3690601/49573125-37a8c800-f978-11e8-9d1c-dbf302553e2e.png)
1
![image](https://user-images.githubusercontent.com/3690601/49573147-45f6e400-f978-11e8-9b0b-263e87683fa9.png)

Below is the top indication(when not set affinity):

![image](https://user-images.githubusercontent.com/3690601/49573230-7cccfa00-f978-11e8-844a-c55824b68cf1.png)

![image](https://user-images.githubusercontent.com/3690601/49573240-83f40800-f978-11e8-824b-febf2745719d.png)

Is it relevant with mxnet or MKLDnn? I am not sure, thank you for your advision!

### Expected behavior
Describe the behavior you expect.

**Comment by emfomenk** [comment]
?

**Comment by vpirogov** [comment]
This question should probably be addressed to MXNet developers, as it touches on the application behavior. I would recommend to submit a report on MXNet github.

Adding @TaoLv, so that he is aware.

**Comment by TaoLv** [comment]
@idealboy Would you mind raising an issue on [MXNet GitHub](https://github.com/apache/incubator-mxnet/issues)? It would be better if you can attach a simple reproducer there. Thanks.

@vpirogov Can we benefit from affinity settings when run 1 instance on 1 core? Is there any recommended settings for this scenario?

**Comment by vpirogov** [comment]
When running a single thread affinity setting is not necessary. Note though, that in some scenarios two or more instances might get pinned to the same physical core leading to performance degradation.

**Comment by vpirogov** [comment]
Closing the issue as it is specific to MXNet.
