### ISSUE TITLE
Question: dims sequence in NHWC format

### ISSUE THREAD

**Issue by 4pao** [intel/mkl-dnn#366]
As we encountered in framework, they provided dimensions array as it is with nhwc format (permutation expected is 0, 1, 2, 3). But the initial process of MKL-DNN assume a dimension array of nchw format even we specified nhwc format, and permuted it to calculate internal strides array. So is this a permanent design or subject to change in future when real use-case exists.

**Comment by 4pao** [comment]
That's clear, thanks for the explain!

**Comment by 4pao** [comment]
I'm walking through the initialization process when NHWC is provided. The logic format of MKL-DNN is always nchw means, as I understand, strides is always in the sequence of nchw. That's to say:

stride [0] is stride[N], stride[1] is stride[C], stride[2] is stride[H], stride[3] is stride[W]. As we initiate a tensor in NHWC, mkl-dnn do things like:
```
enum {N = 0, C = 1, H = 2, W = 3};

stride[C] = 1
stride[W] = dim[C] * stride[C]
stride[H] = dim[W] * stride[W]
stride[N] = dim[H] * stride[H]
```

That's why you suggest we to specify dims in {N, C, H, W}.

How about the scheme like this, accept dims of user as their provision:
```
enum { N' = 0, H' = 1, W' = 2, C' = 3};

stride[C] = 1
stride[W] = dim[C'] * stride[C]
stride[H] = dim[W'] * stride[W]
stride[N] = dim[H'] * stride[H]
```

More specifically, change like this (or the spirit of it):
```
    for (int d = 1; d < ndims; ++d) {
        const int prev_idx = perm[ndims - d];
        const int curr_idx = perm[ndims - 1 - d];

        strides[curr_idx] = dims[curr_idx] == 0
            ? 1
            -- : strides[prev_idx] * nstl::max(1, dims[prev_idx]); --
            ++: strides[prev_idx] * nstl::max(1, dims[ndims -d]); ++
    }
```

**Comment by 4pao** [comment]
OK, let's focus on this change:

```
    for (int d = 1; d < ndims; ++d) {
        const int prev_idx = perm[ndims - d];
        const int curr_idx = perm[ndims - 1 - d];

        strides[curr_idx] = dims[curr_idx] == 0
            ? 1
            -- : strides[prev_idx] * nstl::max(1, dims[prev_idx]); --
            ++: strides[prev_idx] * nstl::max(1, dims[ndims -d]); ++
    }
```

In this way user can provide a dims with NHWC and memory descriptor still have a logic nchw descriptor.

**Comment by emfomenk** [comment]
So are we just talking about `mkldnn_memory_desc_init(...)` function?
And are you proposing allow users to create memory in the following way:

``` c++
// create nchw data layout
mkldnn_memory_desc_init(&md, 4, {n, c, h, w}, f32, mkldnn_nchw);

// create nhwc data layout (note that logical dims are reordered)
mkldnn_memory_desc_init(&md, 4, {n, h, w, c}, f32, mkldnn_nhwc);

// create chwn data layout (note the logical dims are reordered)
mkldnn_memory_desc_init(&md, 4, {c, h, w, n}, f32, mkldnn_chwn);
```

If so the problem here is broken expectations:
``` c++
dims_t dims = {n, h, w, c};
mkldnn_memory_desc_init(&md, 4, dims, f32, mkldnn_nhwc);

assert(md.dims[1] == dims[1]); // fail, cause md.dims[1] is C, while dims[1] is h
```

**Comment by 4pao** [comment]
OK, it seems MKL-DNN only stored logic form of dims.

**Comment by emfomenk** [comment]
:)

That's actually one of the biggest issue with Intel MKL-DNN design -- the library has to support different frameworks which have different default layouts. While in those frameworks the order of dimensions is implicit and always the same, Intel MKL-DNN has to be somehow abstracted from that.

So we came up with this constant logic dims order. That allows avoiding different mismatches. But it is confusing for the users at the first sight, agree...

Hope it is now clearer to you.

**Comment by 4pao** [comment]
Yes, thanks!
