### ISSUE TITLE
Why Does MKL-DNN v-0.15 creates the libmkldnn.so.0.14.0 ? a

### ISSUE THREAD

**Issue by gautamkmr** [intel/mkl-dnn#368]
Currently installing mkl-dnn v-0.15.0. creates a file  libmkldnn.so.0.14.0
Is there any particular to rename this file like this version?

**Comment by vpirogov** [comment]
This is a mistake. Project version in CMakeLists.txt was not updated for v0.14 release.

**Comment by vpirogov** [comment]
Note, that the latest stable version of the library is v0.17. I would highly recommend to upgrade.

I'm closing the issue as it affects older version of the library and is addressed in v0.16 and above.
