### ISSUE TITLE
stream become slower and slower? when to clear?

### ISSUE THREAD

**Issue by coolbei** [intel/mkl-dnn#370]
I have a question,  stream object has a vector member stream_ which record all the previously executed primitives, but i dont see a clear interface. so after submit many times, the stream become very large and slow:

see the code  
`struct stream_eager_t: public stream_t {
    friend stream_lazy_t;

    virtual status_t submit_impl(size_t begin, size_t end,
            primitive_t **error_prim) {
        for (size_t p_index = begin; p_index < end; ++p_index) {
            primitive_t *p = stream_[p_index];
            const nstl::vector<primitive_at_t> &inputs = p->inputs();

            nstl::vector<event_t *> prereq;

            for (size_t i = 0; i < inputs.size(); ++i) {
                if (inputs[i].primitive->kind() != primitive_kind::memory) {
                    for (size_t j = 0; j < stream_.size(); ++j) {
                        if (stream_[j] == inputs[i].primitive) {
                            prereq.push_back(&deps_[inputs[i].primitive]);
                            break;
                        }
                    }
                }
            }

            status_t status = p->engine()->submit(p, &deps_[p], prereq);
            if (status != status::success) {
                *error_prim = p;
                return status;
            }
        }

        return status::success;
    }`

in this code , the for loop which fullfil the prereq will become slower and slower. and also , the cpu_engine never use prereq. 

so, my questions are:
1. should i clear a stream or use a new stream when the old stream has too many elements?
2. if cpu_engine never use prereq, can i remove the prereq logic?

**Comment by emfomenk** [comment]
Hi @coolbei,

The assumption was that stream will be built once and run multiple times. The typical usage is:
``` c++
mkldnn::stream stream;
stream.submit({primitive1, ..., primtiveN});
stream.submit({yet_another_primtive});
stream.wait(); // until the execution finishes

// .. sometime later
stream.rerun(): // no need to resubmit primitives
stream.wait(); // until the execution finishes

// when ::wait() was called for the first time
// no new primitives can be submitted to the stream, only rerun
stream.submit({one_more_primitive}); // exception
```

So coming back to your questions:
1. I would say so. I've never faced with the issue that there is some degradation cause by a huge stream. However the streams as they are now are almost useless. Most of the frameworks create one stream per primitive. This should work fine -- creating a stream should be relatively cheap operation. In your case I think that would be the best choice. 
2. Prerequisite logic is a common for the entire library. But you are right, CPU engine doesn't use it indeed. You can remove them in your fork of Intel MKL-DNN but that change would not be upstreamable. On the other hand I don't think that prerequisite support brings any performance penalties since they are always empty.

There is also https://github.com/intel/mkl-dnn/issues/298 that discussed streams and might be helpful.

**Comment by coolbei** [comment]
> Hi @coolbei,
> 
> The assumption was that stream will be built once and run multiple times. The typical usage is:
> 
> ```c++
> mkldnn::stream stream;
> stream.submit({primitive1, ..., primtiveN});
> stream.submit({yet_another_primtive});
> stream.wait(); // until the execution finishes
> 
> // .. sometime later
> stream.rerun(): // no need to resubmit primitives
> stream.wait(); // until the execution finishes
> 
> // when ::wait() was called for the first time
> // no new primitives can be submitted to the stream, only rerun
> stream.submit({one_more_primitive}); // exception
> ```
> 
> So coming back to your questions:
> 
> 1. I would say so. I've never faced with the issue that there is some degradation cause by a huge stream. However the streams as they are now are almost useless. Most of the frameworks create one stream per primitive. This should work fine -- creating a stream should be relatively cheap operation. In your case I think that would be the best choice.
> 2. Prerequisite logic is a common for the entire library. But you are right, CPU engine doesn't use it indeed. You can remove them in your fork of Intel MKL-DNN but that change would not be upstreamable. On the other hand I don't think that prerequisite support brings any performance penalties since they are always empty.
> 
> There is also #298 that discussed streams and might be helpful.

thank you very much! This really helps!
Using only one stream by many primities and submit every forward process is the way that intel caffe do. So I guess those guy use it the wrong way.

**Comment by emfomenk** [comment]
> Using only one stream by many primities and submit every forward process is the way that intel caffe do. So I guess those guy use it the wrong way.

Well, I cannot say this is the wrong way to handle streams. There is just no need in submitting as many primitives as possible into one stream.

Since having one stream per primitive is simpler and doesn't hurt performance -- it's preferable.

**Comment by coolbei** [comment]
> > Using only one stream by many primities and submit every forward process is the way that intel caffe do. So I guess those guy use it the wrong way.
> 
> Well, I cannot say this is the wrong way to handle streams. There is just no need in submitting as many primitives as possible into one stream.
> 
> Since having one stream per primitive is simpler and doesn't hurt performance -- it's preferable.

ok, I will try that. Thanks again~
