### ISSUE TITLE
momentum for batch normalization?

### ISSUE THREAD

**Issue by dcslin** [intel/mkl-dnn#371]
Dear team,

Thank you for the work on the awesome project.

Could you please share a hint on how to configure `momentum` for `batch norm`? I had tried to read through the doc, forgive me if missed anything. Much appreciated.

**Comment by emfomenk** [comment]
Hi @dcslin,

Thanks for the warm words!

Alas, Intel MKL-DNN doesn't support running mean/variance, so you would need to implement them yourself...

``` c++
    // mean and var come from Intel MKL-DNN's batch norm
    running_mean[:] = alpha * running_mean[:] + (1 - alpha) * mean[:]
    running_var[:] = alpha * running_var[:] + (1 - alpha) * var[:]
```

Non-so-easy-to-read real world example can be found [here](https://github.com/intel/caffe/blob/master/src/caffe/layers/mkldnn_batch_norm_layer.cpp#L433-L446) (taken from IntelCaffe).

**Comment by dcslin** [comment]
Hi @emfomenk , loud and clear, Thank you for the clarification.
