### ISSUE TITLE
read mkldnn memory

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#378]
New to mkldnn. How can I read mkldnn memory to a vector?  Want to cast this memory to vector<float>.

**Comment by densamoilov** [comment]
Hi @dev2y, MKL-DNN memory provides a member function named get_data_handle() that returns a pointer to internal memory buffer, so you can get this pointer and copy the data.

**Comment by dev2y** [comment]
```
    auto user_src_memory
            = memory({ { { conv1_src_tz }, memory::data_type::f32,
                               memory::format::nchw },
                             cpu_engine },
                    user_src.data());

```
thank you. [Referring ](https://github.com/intel/mkl-dnn/blob/4bdffc2cb1c3d47df9604d35d2c7e5e47a13f1a6/examples/simple_net.cpp#L62)simple_net.cpp, how do I get data back to usr_src?

can you help me with the code snippet please?

**Comment by dev2y** [comment]
Got it. thank you.
