### ISSUE TITLE
Performance issue when fork on linux

### ISSUE THREAD

**Issue by diandianliu** [intel/mkl-dnn#379]
hi
 I have created a libmxnet.so use USE_MKLDNN=1 in config.mk file.
the use time is 290ms per image is faster than before( 3800ms not use MKLDNN).

But I use fork to run the process the time is 1300ms per image the time is too long.

cpu useage:CPUS(32),not set OMP_NUM_THREADS use default
no fork :1600%CPU
fork:100%CPU  ;

 in fork case, when I set OMP_NUM_THREADS more large,the cpu usage is  more large too ,but the speed is not improve.

why the Performance is so slow when use fork?

**Comment by emfomenk** [comment]
Hi @diandianliu,

Seems quite similar to [this](https://stackoverflow.com/questions/15256826/unable-to-set-the-openmp-threads-affinity-in-a-forked-process) StackOverflow thread.

Could you please try resetting the mask in the child process?

``` c++
cpu_set_t cpuset;
CPU_ZERO(&cpuset);
for (int i = 0; i < nthr; ++i) CPU_SET(i, &cpuset);
sched_setaffinity(0, sizeof(cpuset), &cpuset);
```

Alternatively, if you set KMP affinity like `KMP_AFFINITY=granularity=fine,compact`, try omitting it (just to check if this helps).

**Comment by TaoLv** [comment]
Hi @diandianliu Not sure what does "use fork to run the process" mean. But I guess it relates to the discussion here:
https://github.com/apache/incubator-mxnet/pull/13606#discussion_r240914
and 
https://github.com/apache/incubator-mxnet/issues/13593

**Comment by diandianliu** [comment]
> Hi @diandianliu,
> 
> Seems quite similar to [this](https://stackoverflow.com/questions/15256826/unable-to-set-the-openmp-threads-affinity-in-a-forked-process) StackOverflow thread.
> 
> Could you please try resetting the mask in the child process?
> 
> ```c++
> cpu_set_t cpuset;
> CPU_ZERO(&cpuset);
> for (int i = 0; i < nthr; ++i) CPU_SET(i, &cpuset);
> sched_setaffinity(0, sizeof(cpuset), &cpuset);
> ```
> 
> Alternatively, if you set KMP affinity like `KMP_AFFINITY=granularity=fine,compact`, try omitting it (just to check if this helps

thanks ,i find the quest , when use fork , mkl can only use one thread
