### ISSUE TITLE
mkldnn perfomance on linux pc or intel car branch2 board

### ISSUE THREAD

**Issue by arthurhi** [intel/mkl-dnn#395]
hi,
    i run the mkldnn project which is lenet. and now it can runs ok on intel car branch2 demo board. but i am confused the performance.
    the hardware as follows:
    pc    is   intel® core™ i5-6200U cpu @ 2.30GHz 2.40GHz.
    car branch2 is Intel(R) Atom(TM) CPU C3734 @ 1.70GHz  8 core.

   the 10000 mnist lenet samples(28x28) performance as follows
   pc is 1.0-1.2 seconds
   car branch2 is 4.6 seconds.

  i dont know is it ok or something i can do to inhence the performance on car branch2 board?

  my mkldnn cmake config as follows:
  CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_EXAMPLE=OFF -DWITH_TEST=OFF ..

   can you give me some advices? thanks a lot!!!

**Comment by vpirogov** [comment]
I would expect the i5-6200 to be faster than C3734 despite twice as lower number of cores in throughput workloads, like convolutional neural networks. The i5-6200 supports Intel AVX2 instruction set, while C3734 has an Intel SSE4.2.

I would suggest that you collects the logs with MKLDNN_VERBOSE=1 to see how the model is executed exactly and how much time spent in each individual layer and compare the convolutions performance to benchdnn results. It might reveal additional opportunities for optimizations in your application.

**Comment by arthurhi** [comment]
thanks  a lot. you are right! C3734 use sse ,and i5-6200 use AVX2.
