### ISSUE TITLE
question on LRN implementation

### ISSUE THREAD

**Issue by jczaja** [intel/mkl-dnn#396]
I'm investigating numerical diffrences in MKL-DNN LRN vs PaddlePaddle LRN (across channels). 
And in reference LRN of MKL-DNN , sum of squares is divided by size of window:

https://github.com/intel/mkl-dnn/blob/b21f006f657179cc4c70cda927b53de017e63805/src/cpu/ref_lrn.cpp#L110

I do not find this division in original paper. Could you please explain reason for that ?

**Comment by vpirogov** [comment]
We are following [Caffe's definition](http://caffe.berkeleyvision.org/tutorial/layers/lrn.html) for LRN, which normalizes the values by the size of the local region. This matches the Tensorflow definition as well.

I see that the difference in PaddlePaddle definition was pointed in [an issue on PaddlePaddle's Github](https://github.com/PaddlePaddle/Paddle/issues/9094).

**Comment by vpirogov** [comment]
On the second though the issue I referred to seem to e addressed already.

**Comment by jczaja** [comment]
@vpirogov Thanks for answer. In fact PaddlePaddle does follow original equation of LRN , so there is no division by size of window. But This can be workaround by multiplying original alpha param by sizeo of window  eg. alpha' = alpha*n   <=>   alpha\*n / n \* sum^n_i{ai} => alpha  \* sum^n_i{ai}
