### ISSUE TITLE
performance difference between GCC and Intel C++ Compiler

### ISSUE THREAD

**Issue by saicomagic** [intel/mkl-dnn#398]
In the doc i see the recommended compiler of mkldnn is Intel C++ Compiler. I'm wondering how much performance difference it is between GCC and Intel C++ Compiler. Are there any detailed test results of this? Thanks very much!

**Comment by emfomenk** [comment]
Hi @saicomagic,

In most of the cases Intel MKL-DNN generates machine code on its own. That allows the library to have same performance independently from the compiler.

There are some cases when the library would depend on the compiler though. These include:
- OpenMP RT. When Intel Compiler is used or when the library is built with Intel MKL binary blob Intel MKL-DNN uses Intel OpenMP. If GCC is used w/o Intel MKL, GNU OpenMP is used.
- For some primitive flavors we don't have jitted versions. That typically happens for the primitives in the plain formats like `nchw` or `nhwc`. For such situation we typically observe Intel Compiler generates faster code. The difference is bigger compare to older GCC (4.8.3), but typically insignificant for the newer versions of GCC (8.0+). However [the proper](https://github.com/intel/mkl-dnn/blob/master/doc/mainpage.md#performance-considerations) integration of Intel MKL-DNN would avoid such flavors.

I made a quick experiment: `caffe time` for ResNet50 and InceptionV3 topologies in training mode and got the following results on a Skylake server:

 /    | ICC 18.0 | GCC 8.1.0 | GCC 4.8.3
---|---|---|----
Extra compiler flags [**] | -xCORE-AVX512 | -march=skylake-avx512 | n/a
ResNet-50 | 693.2 ms | 694 ms | 690.9 ms
InceptionV3 | 573.5 ms | 573.5 ms | 573.5 ms

[*] All three configurations use Intel MKL 2019 Update 1, and hence rely on Intel OpenMP.
[**] Extra compiler flags are turned on by default for release builds and correspond to the architecture of the system the library is built on. See details [here](https://github.com/intel/mkl-dnn/blob/master/cmake/options.cmake#L97).

As you can see the difference is within the run-to-run variation. It's worth mentioning these topologies are very well optimized in the Intel MKL-DNN, hence the most of the layers used jitted primitives.

**Comment by saicomagic** [comment]
Get it! Thanks very much for your comprehensive explanation! ^_^
