### ISSUE TITLE
Q: Extracting the actually used memory format, when using format::any

### ISSUE THREAD

**Issue by plabus** [intel/mkl-dnn#399]
Using memory::format::any when setting up a primitive descriptor, is there a way to extract the actual layout chosen by the library at runtime? The C++ API seems to provide only a getter for the primitive descriptor of the memory primitive, and I'm not sure how to extract the memory format from that.

**Comment by emfomenk** [comment]
Hi @plabus,

Sure. To do you need to query the memory primitive descriptor you are interested in, get its memory desc, and check the format.

Something like this:

``` c++
    // conv created with any, want to get the format for weights
    auto wei_mpd = memory::primitive_desc(conv_pd.weights_primitive_desc());
    auto wei_md = wei_mpd.desc();
    auto wei_fmt = wei_md.data.format;
```

Please note that the format itself doesn't fully describe the layout, and it's better to use the whole memory desc for such purposes. For example, format doesn't contain any information about padding or initial offset if they are non-trivial.

Also, if the purpose is to get some sense of what is going on, you can use `MKLDNN_VERBOSE=1` environment variable to see what Intel MKL-DNN is actually executing. When run a convolution, the library would print all the formats (for src, wei, bia, and dst).

**Comment by plabus** [comment]
Thanks @emfomenk, this is very helpful!
