### ISSUE TITLE
mkldnn formats

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#400]
Are formats nchw8c and f32_nChw8c same?
I see nchw8c for mkldnn ops but for sum I see the format as f32_nChw8c.

Thank you

**Comment by shelleygoel** [comment]
Yes, they describe the same data layout in memory. Could you please point out exactly where you see these formats?

**Comment by dev2y** [comment]
mkldnn_verbose,exec,sum,simple:any,undef,in:f32_nChw8c out:f32_nChw8c,num:2,1x256x56x56,30.414
mkldnn_verbose,exec,eltwise,jit:avx2,forward_inference,fdata:nChw8c fdiff:undef,alg:eltwise_relu,mb1ic256ih56iw56,0.446756

**Comment by dev2y** [comment]
Thanks. I will close this issue.
