### ISSUE TITLE
Backport CMake Config installation to 0.17.x

### ISSUE THREAD

**Issue by Flamefire** [intel/mkl-dnn#407]
https://github.com/intel/mkl-dnn/pull/358 introduced the CMakeConfig that is installed for consumption by CMake projects. This is very useful for consumers but is not included in any current release.

Can this be backported to a current release please? It is quite hard to use the library as the dependencies are not known (e.g. mkl, openmp, ...) when you only want to use this.

**Comment by nathan-greeneltch-intel** [comment]
copied from related issue [408:](https://github.com/intel/mkl-dnn/issues/408)

> The CMake config in #358 is incomplete: It does not contain the required include paths in the install tree so programs using this fail to compile unless the includes happen to be in a standard location.
> 
> Furthermore it excludes all libraries that are required to link. This is especially fatal for static builds of MKL-DNN.
> 
> However this is a more general problem: As a user what libraries do I need to link against? The readme states that no linking is required for dynamic builds but nothing about static builds. But knowledge from the build process is required:
> 
> * Do I need to use lib/libmklml_gnu.so, lib/libmklml_intel.so or neither?
> * Do I need to use lib/libiomp5.so? Getting this wrong results in undefined behaviour, but how would I know if I didn't build it myself?

**Comment by nathan-greeneltch-intel** [comment]
We have 0.18rc targeted for release today or tomorrow. #358 is included. Will this suffice?

**Comment by Flamefire** [comment]
Unfortunately not due to #408. I opened a MR making it better. Any chance to get that included?

**Comment by Flamefire** [comment]
Well if the new code is released then close this. I wouldn't mix up the 2 issues though.

> We have 0.18rc targeted for release today or tomorrow. #358 is included. Will this suffice?

So technically yes: It does include the config and it is usable IF mkldnn is installed into a system directory whose `include` subfolder is in the default include path, e.g. `/usr/local`.

However I strongly encourage to resolve #408 before the actual release or at least include #409

**Comment by rsdubtso** [comment]
I think it makes sense to backport this to 0.17.x if the effort is low because 0.18 breaks some things and it may take a while until people adapt.

**Comment by vpirogov** [comment]
We decided to promote all the CMake related changes to v0.18 release and not backport to v0.17. Please let me know if you have any concerns with that.

**Comment by vpirogov** [comment]
The changes are now in rls-v0.18 branch and will be a part of the v0.18 release.
