### ISSUE TITLE
Q: Is there a constant memory primitive?

### ISSUE THREAD

**Issue by Flamefire** [intel/mkl-dnn#410]
The memory primitives are created using a void-pointer: `memory(const primitive_desc &adesc, void *ahandle)`

If I have code like this:
```
std::vector<float> foo(const std::vector<float>& input){
  auto engine = ...;
  auto desc = ...;
  auto memory = memory({desc, engine}, input.data);
  // Call some operator and return result from another buffer
}
```

- What happens to my memory?
- Are there any guarantees where memory is not modified?
- Is there any way to tell mkldnn to treat my memory as constant?
- Could/Is/Will a reordering use the input buffer to reorder in-place or would it be advantageous to allow mkldnn  to do this?

**Comment by emfomenk** [comment]
Hi @Flamefire,

The question is partially answered in #387.
In general, the answer is that Intel MKL-DNN doesn't expose the read-only attribute of the memory. However if memory is used as an input, no primitive would write to that memory.

There is one peculiarity though. If memory has non-trivial (zero) padding, the call to memory constructor would write zeros to the padded area. This is done to guarantee the correctness of the algorithms in Intel MKL-DNN. If the `desc` you pass just describes the user's data (e.g. in plain `nchw` / `nhwc` formats) then padding is trivial and no write would ever happen.

Some additional details regarding padding can be found [here](https://intel.github.io/mkl-dnn/understanding_memory_formats.html), section "_What if channels are not multiple of 8 (or 16)?_"

Answering your questions:
> * What happens to my memory?

Memory save the pointer to data. If there is non-trivial padding, the library zeros the padded area as described above. Other than that nothing happens to memory.

> * Are there any guarantees where memory is not modified?

No, the library doesn't provide any special types of memory that would prohibit writing to it.

> * Is there any way to tell mkldnn to treat my memory as constant?

As long as memory is used as input only, no primitive would write to the memory.

> * Could/Is/Will a reordering use the input buffer to reorder in-place or would it be advantageous to allow mkldnn  to do this?

Intel MKL-DNN doesn't support in-place reorders. Reorders are *always* explicit. Most likely the data you attached to the memory is in user's plain format (e.g. `nchw`), but the library typically works with blocked (simd-friendly) layout. So once you create the first convolution with the format `mkldnn_any` the convolution would ask you to reorder the data to the preferable layout (something like `mkldnn_nChw16c`). For that you will create new memory and call reorder from your original memory to the blocked one.

**Comment by Flamefire** [comment]
> There is one peculiarity though. If memory has non-trivial (zero) padding, the call to memory constructor would write zeros to the padded area.

This would be the critical point. Is there any chance to no when this padding is used for sure?   
The link you showed says: `when the number of channels is not multiple of the block size for nChw8c format?`   
Does this mean non-blocked format does not ever have padding and hence is definitely const?

With all this confusion: Wouldn't it be a good idea to propagate the const-ness of memory in the C interface? It seems like it will be very easy to do given that `void*` can be implicitly casted to `const void*` and only a few changes to the C++ templates pass this higher up.   
The gain would be guarantees about what happens to the memory so user code can e.g. rely on being able to reuse input buffers. The function adding the padding would then compile or runtime error if a const memory is passed in and padding is required. If the extension `consider extending our API in future to allow attaching pointers without subsequent initialization with zeros, if user can guarantee the padding is already filled correctly` is implemented this can be reused for an overload working with const memory.

**Comment by vpirogov** [comment]
@emfomenk, do we need a follow up on this one or the way we handle padding makes this point moot?

**Comment by emfomenk** [comment]
The point is valid, but I think implementing it would require quite significant effort and would bring limited value given that our model writes zeros to the padded area when the buffer is first time attached to Intel MKL-DNN memory object. Moreover on GPU the const-ness is described using the properties of cl_mem which doesn't interplay well with the idea of using `const void *`.

I think we should agree that we have such a neglect / limitation in the API and keep going. However we definitely should document the fact that we write to buffer whenever a user attaches it to a memory object.

**Comment by Flamefire** [comment]
>  and would bring limited value given that our model writes zeros to the padded area when the buffer is first time attached to Intel MKL-DNN memory object

And this is a problem. If you get the memory from "outside" you may not be allowed to modify it. This is important when integrating MKL-DNN with other code. Having "const" in the signature would have the (compiler enforced) guarantee (for the user) that this memory is not modified. Instead of writing to the buffer the API could check for correct padding values instead and error out if it isn't.

> Moreover on GPU the const-ness is described using the properties of cl_mem which doesn't interplay well with the idea of using const void *.

This only applies when the user supplies a `cl_mem` object. If the implementation allocates a `cl_mem` it can deduce the flags from the constness of the passed pointer, so this direction works well.

> However we definitely should document the fact that we write to buffer whenever a user attaches it to a memory object.

Yes please enhance the documentation so it is clear when exactly something is written into the users buffer and when it isn't.   
Please also consider the approach of only checking for correct padding. But the API would be much better/more correct if it includes constness: `void doFoo(const_mem input, const_mem bias, mem output)`. A `const_mem' can be created via a function taking a `void*` where it writes padding or from a `const void*` where it only checks padding. Further down there are then guarantees that  `doFoo` does not write to the first 2 buffers. Having this in the signature makes validation much easier.
