### ISSUE TITLE
error when compiling on Windows

### ISSUE THREAD

**Issue by lyemily** [intel/mkl-dnn#411]
hello, I tried to compile the latest version with VS2015 on windows, but many compilation errors occurred such as below, more than 500. Do you have any suggestion about this?

Windows Server 2012 R2
CMake 3.12.4
Visual Studio 2015
............................................................
C:\work\mkl-dnn-master\src\common\format_traits.hpp(114): error C2131: expression did not evaluate to a constant
C:\work\mkl-dnn-master\src\common\format_traits.hpp(48): error C2131: expression did not evaluate to a constant

c:\work\mkl-dnn-master\src\cpu\cpu_convolution_pd.hpp(37): error C2899: typename cannot be used outside a template declaration
c:\work\mkl-dnn-master\src\cpu\jit_avx512_common_convolution_winograd.hpp(88): error C2899: typename cannot be used outside a template declaration
c:\work\mkl-dnn-master\src\cpu\jit_avx512_common_convolution_winograd.hpp(163): error C2899: typename cannot be used outside a template declaration
c:\work\mkl-dnn-master\src\cpu\jit_avx512_common_convolution_winograd.hpp(254): error C2899: typename cannot be used outside a template declaration
c:\work\mkl-dnn-master\src\cpu\jit_avx512_common_convolution_winograd.hpp(353): error C2899: typename cannot be used outside a template declaration

**Comment by rsdubtso** [comment]
Cannot reproduce. Can you please post how you invoke cmake (and potentially msbuild) and its output?

My steps were:

Generate:
``` bat
C:\Users\rsdubtso\work\ml\mkl-dnn\mkl-dnn\build> cmake .. -G "Visual Studio 14 2015 Win64"
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- This is a product build
-- Detecting Intel(R) MKL: trying mklml_intel
-- Detecting Intel(R) MKL: trying mklml_gnu
-- Detecting Intel(R) MKL: trying mklml
-- Detecting Intel(R) MKL: trying mkl_rt
CMake Warning at cmake/MKL.cmake:253 (message):
  Intel(R) MKL not found.  Some performance features may not be available.
  Please run scripts/prepare_mkl.sh to download a minimal set of libraries or
  get a full version from https://software.intel.com/en-us/intel-mkl
Call Stack (most recent call first):
  cmake/OpenMP.cmake:26 (include)
  CMakeLists.txt:69 (include)


-- OpenMP lib: provided by compiler
-- OpenMP dll: provided by compiler
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- VTune profiling environment is unset
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.13.0.windows.1")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/rsdubtso/work/ml/mkl-dnn/mkl-dnn/build
```

Build:
``` bat
C:\Users\rsdubtso\work\ml\mkl-dnn\mkl-dnn\build> cmake --build .
...
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:38.80
```

**Comment by rsdubtso** [comment]
After poking around and help from colleagues I started to strongly suspect that this is a problem with VS version: VS 2015 update 1 did not fully support c++11, hence the errors. I will keep this open for a few days more, and close if there are no new developments.

**Comment by nwpu2fjl** [comment]
@rsdubtso, I use msbuild command-line tool to build from the command line,  listed on the main page but got this error
![image](https://user-images.githubusercontent.com/12624852/55155111-87163c80-5191-11e9-92df-06b4902d9c81.png)
