### ISSUE TITLE
What is the expected matrix format for the gemm_s8x8s32 functions

### ISSUE THREAD

**Issue by XapaJIaMnu** [intel/mkl-dnn#412]
Hey guys,

Unlike traditional mkl BLAS routines, there is no parameter to specify whether the input and the output matrices are row major or column major. I am looking to use the `gemm_s8x8s32` functions as exposed in https://github.com/intel/mkl-dnn/blob/master/include/mkldnn.h#L1813

As far as I saw, there is no mention in the documentation about it. I *think* I can infer the format is ColMajor by inspecting the `check_gemm_input` function ( https://github.com/intel/mkl-dnn/blob/master/src/cpu/gemm/gemm.cpp#L48 ), which seems to expect `lda`, `ldb` and `ldc` to follow the column major values, as specified by the [MKL-BLAS documentation](https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemm). Is this the case with other library functions?

Cheers,

Nick

**Comment by vpirogov** [comment]
@XapaJIaMnu , you are right, mkldnn_*gemm* functions operate on column major format as specified in BLAS documentation. 

All the other functions in the library do not operate directly on user-provided buffers and instead use abstraction called `memory`. This abstraction separates physical data layout (row/col-major and all the complex stuff that comes with 3-4-5-dimensional tensors) from the logical layout. You can find description of semantics for logical dimensions in the documentation for [memory descriptor](http://intel.github.io/mkl-dnn/structmkldnn__memory__desc__t.html).

**Comment by XapaJIaMnu** [comment]
Thank you @vpirogov for the prompt reply! I do believe that it should be specified somewhere in the documentation. Feel free to close the issue.

Cheers,

Nick

**Comment by vpirogov** [comment]
I totally agree with you and took a note to add the information to documentation.
