### ISSUE TITLE
Is  tensorflow-mkl version same as tensorflow?

### ISSUE THREAD

**Issue by BigBigWolf-AI** [intel/mkl-dnn#414]
OS: windows 10
Intel said that if I want to install the mkl version of tensorflow on windows 10, I have to use the command as following:
_conda install tensorflow-mkl_

However, Anaconda said that if I want to install the mkl version of tensorflow, I just need to execute the following command no matter my OS is windows or linux:
_conda install tensorflow_

I just want to know if tensorflow is the same as tensorflow-mkl when I install tensorflow using the _conda install_ command ?

**Comment by nathan-greeneltch-intel** [comment]
please see install guide for more details: https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide

**Comment by nathan-greeneltch-intel** [comment]
on linux, the conda main channel includes mkl accelerations, so "conda install tensorflow" will get the job done. There is a different story on windows or MacOS. Furthermore, installing from intel conda channel usually has newer versions that the conda main channel, because the update cadence is faster.

**Comment by BigBigWolf-AI** [comment]
Thanks for answer my question. As you said, installing from intel conda channel usually has newer versions than the conda main channel. But from the install guide, It said that installing from intel conda channel only support linx and do not support windows (PS: my OS is windows). I want to know is there any way that allow me install the tensorflow(mkl version) from the intel channel on windows except build from source code ?  Thank you!

**Comment by nathan-greeneltch-intel** [comment]
Currently Intel does not post a windows build binary. We are working to update this policy. "conda install tensorflow-mkl" will provide a windows version, but it is created by anaconda's build team, not Intel's.

**Comment by zhangruiskyline** [comment]
Hi, I have a general question, we are using the Java Tensorflow, and want to have MKL-DNN supported in our tensorflow, is there some POM dependency we can directly use to add ? we do not want to build tensorflow from source

**Comment by vpirogov** [comment]
Hi @zhangruiskyline,

Google's Tensorflow distribution has limited oneDNN optimizations enabled in default distribution starting from v1.5. Full optimziations have to be enabled in build time with  `--config=mkl`.

Distribution in Anaconda includes full oneDNN optimizations by default. I do not know whether it has Java API included though. See [here](https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html).

+@agramesh1, @claynerobison

**Comment by zhangruiskyline** [comment]
Thanks, we are not looking at Anaconda python whl, but Java support, it will be good to directly have Jar file that we can fetch via Maven POM dependency. Also I would like to know if we want to get the mkl support in older tensorflow version, like the version we have is tensorflow 1.13.1, how can we approach this without re build everything from scratch

**Comment by zhangruiskyline** [comment]
@nathan-greeneltch-intel , I wonder to know if we want to get oneDNN(mkl) support for tensorflow-1.13.1 version, and for Java platform, is there some Jar file repo(maven pom dependency) we can add? we need to stick to TF 1.13.1 version for some legacy reason

**Comment by vpirogov** [comment]
Let's see what @agramesh1 and @claynerobison have to say about it.

**Comment by zhangruiskyline** [comment]
just ping in this thread, is there any tensorflow with default support on MKL?

**Comment by zhangruiskyline** [comment]
Hi @ashahba , do you have Java Jar mvn repo to include oneAPI/mkl in tensorflow Java implementation?
