### ISSUE TITLE
What mkldnn format to use for best perf?

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#416]
It seems like only convolution primitive converts input `nchw `to output `nchw8c `(for example). Rest of the primitives keep the same input format. If I am using primitives other than conv, how do I get the correct format for the given platform?

**Comment by emfomenk** [comment]
All not-compute-intesive primitives should be created on the layout that is currently used. If the input comes from the convolution, than use it (which is typically blocked, as you mentioned). If the input comes from user's code, then use the user's layout (typically `nchw` or `nhwc`).

The corresponding part in [the documentation](https://github.com/intel/mkl-dnn/blob/master/doc/mainpage.md#performance-considerations).

**Comment by vpirogov** [comment]
Closing as the question seems to be addressed. Please feel free to reopen if you need additional clarifications.
