### ISSUE TITLE
When will mkl-dnn start supporting fp16

### ISSUE THREAD

**Issue by vignesh-irtt** [intel/mkl-dnn#417]
In gpu when inferring tensorflow model with fp16 we got 2x improvement in time compared to fp32, so we tried the same in cpu and it seems tf built with mkldnn doesn't support fp16

**Comment by vpirogov** [comment]
That's correct, Intel MKL-DNN [indeed](http://intel.github.io/mkl-dnn/) does not have fp16 support. The rationale is that current x86 instruction set does not include instructions necessary for fast math with fp16 numbers, so there's no expected performance gain in compute-heavy operations like convolutions or matrix-matrix multiplications.

**Comment by vpirogov** [comment]
IF you are interested in getting better performance with low precision on inference on x86 you might want to look into int8, which Intel MKL-DNN does support.

**Comment by emfomenk** [comment]
Some performance data with int8 data type can be found [here](https://github.com/intel/caffe/wiki/INTEL%C2%AE-OPTIMIZED-CAFFE-PERFORMANCE-AND-CONVERGENCE).

**Comment by vignesh-irtt** [comment]
Can u please help me how to do int8 inference in tensorflow compiled with int8

**Comment by vpirogov** [comment]
I don't have full visibility into support of MKL-DNN features in Tensorflow. I'll let @agramesh1, who is directly involved into the effort to comment on status.

**Comment by agramesh1** [comment]
@vignesh-irtt  The Intel optimized version of Tensorflow now includes support for int8 inference. Currently we only support a small set of models.  You can get the pretrained int8 models and more information on how to run these from here https://github.com/IntelAI/models/releases .  We will be adding more models in future.

**Comment by vignesh-irtt** [comment]
I tried compiling tensorflow from latest source but conv op says **TypeError: Value passed to parameter 'input' has DataType int8 not in list of allowed values: float16, bfloat16, float32, float64**.Where i can download the int8 supported tensorflow wheel.

**Comment by agramesh1** [comment]
@vignesh-irtt  Can you submit an issue here https://github.com/IntelAI/models/issues  indicating which model you are running?

**Comment by vpirogov** [comment]
Closing the issue as the portion related to Intel MKL-DNN was addressed.
