### ISSUE TITLE
can i use it in x86

### ISSUE THREAD

**Issue by caohaitao** [intel/mkl-dnn#418]
when will support intel x86 cpu

**Comment by vpirogov** [comment]
@caohaitao, Intel MKL-DNN supports processors compatible with Intel 64 architecture (64-bit version of x86). We currently do not have plans to introduce support for IA-32 (32-bit version of x86) as the most x86 processors produced in the last 10 years have Intel 64 support. Even if we did IA-32 has two major limitations:
1. The size of memory an application can address is limited to 2 gigabytes.
2. Processors in IA-32 mode have less general purpose and SIMD registers available, that leads to reduced performance in throughput bound operations.

If you have a use case in mind where IA-32 might be required please let me know.

**Comment by caohaitao** [comment]
@vpirogov ,We have thousands of hardware use intel IA-32.we use ncnn to do inference,but too slow,so if openvino can support IA-32,ours algorithm can run faster and help us reduce costs.I think there are some company like us.Thank you very much.

**Comment by vpirogov** [comment]
@caohaitao, what is the instruction set this hardware supports?

**Comment by caohaitao** [comment]
The old hardware use Intel(R) Atom(TM) CPU N2800  1.86GHZ,the new hardware use Intel(R) Celeron(R) CPU  J3160  @ 1.60GHz.Can they support openvino?

**Comment by vpirogov** [comment]
These are relatively new systems:
[Intel(R) Atom(TM) CPU N2800](https://ark.intel.com/content/www/us/en/ark/products/58917/intel-atom-processor-n2800-1m-cache-1-86-ghz.html)
[Intel(R) Celeron(R) CPU J3160](https://ark.intel.com/content/www/us/en/ark/products/91533/intel-celeron-processor-j3160-2m-cache-up-to-2-24-ghz.html)

Both have Intel 64 support and will be able to run Intel MKL-DNN or OpenVINO if the operating system has 64-bit support.

**Comment by caohaitao** [comment]
I will try it,thank you very much.
