### ISSUE TITLE
[Question] packed gemm

### ISSUE THREAD

**Issue by ykim362** [intel/mkl-dnn#422]
Hi @vpirogov ,
Does packed gemm have a dependency on MKL?
Is there any plan to have packed gemm in mkl-dnn?

Thanks!

**Comment by vpirogov** [comment]
Hi @ykim362,

Long time no see) The direction we are taking is to completely remove dependency on Intel MKL. This means we will either add packed gemm API to Intel MKL-DNN or come up with somewhat different solution that allows to achieve the same result.

**Comment by ykim362** [comment]
Yes, long time no see. :)
Thanks for the explanation. The plan seems wonderful. It might be a compelling feature in MKL-DNN!
Would you be able to share the planned or probable timeframe for that?

**Comment by vpirogov** [comment]
We are still figuring out what is the best way to expose the packed functionality in Intel MKL-DNN, so there's no specific timeline for that.

**Comment by ykim362** [comment]
Got it. Thanks, @vpirogov!
