### ISSUE TITLE
memory allocation of output buffer

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#424]
In simple_net.cpp, only memory for output data of last kernel's dst_mem is [allocated](https://github.com/intel/mkl-dnn/blob/002d23b36d96a9150acf57df6a8cfcb89a7debc1/examples/simple_net.cpp#L64). 

I am wondering if mkldnn is allocating and freeing memory for each kernel's output of primitive [vector](https://github.com/intel/mkl-dnn/blob/002d23b36d96a9150acf57df6a8cfcb89a7debc1/examples/simple_net.cpp#L46). For example, `conv1_dst_tz = { batch, 96, 55, 55 }` and how and when the memory of size `product(conv1_dst_tz)` for conv1 output is allocated.

**Comment by emfomenk** [comment]
For `mkldnn::memory` you have two constructors:
1. [`mkldnn:memory(const desc &md, const engine &aengine)`](https://github.com/intel/mkl-dnn/blob/master/include/mkldnn.hpp#L900) which allocates memory on your behalf and free it when the memory object is destroyed.
2. [`memory(const desc &md, const engine &aengine, void *ahandle)`](https://github.com/intel/mkl-dnn/blob/master/include/mkldnn.hpp#L889) that takes the pointer from a user, and doesn't free it or anything.

And here are the two different usages:
1. https://github.com/intel/mkl-dnn/blob/master/examples/simple_net.cpp#L98
2. https://github.com/intel/mkl-dnn/blob/master/examples/simple_net.cpp#L71

**Comment by dev2y** [comment]
Thank you @emfomenk. This helps.

**Comment by vpirogov** [comment]
Sounds like a topic for the developer guide.

**Comment by dev2y** [comment]
I could start without [creating ](https://github.com/intel/mkl-dnn/blob/002d23b36d96a9150acf57df6a8cfcb89a7debc1/examples/simple_net.cpp#L71)user_src_memory from user_src data() and set `user_src_memory` to `user_src.data()` later at kernels loop and  execute in the [end](https://github.com/intel/mkl-dnn/blob/002d23b36d96a9150acf57df6a8cfcb89a7debc1/examples/simple_net.cpp#L718). Right?

**Comment by emfomenk** [comment]
Yes, you can always attach a new pointer to the already created Intel MKL-DNN memory using the [`mkldnn::memory::set_data_handle(void *handle)`](https://github.com/intel/mkl-dnn/blob/master/include/mkldnn.hpp#L929). Of course, you have to do so prior to the actual execution :)

``` c++
     auto mem = memory({{n, c, h, w}, dt::f32, tag::nchw}, eng, nullptr);
     // ...
     float *ptr = ...;
     mem.set_data_handle(ptr);
     // ...
     execute(mem);
```

Note the `nullptr` at the creation line. Without it the memory would allocate internal buffer.

**Comment by dev2y** [comment]
@emfomenk instead of iterating and executing each primitive as implemented in [simple-net.cpp](https://github.com/intel/mkl-dnn/blob/002d23b36d96a9150acf57df6a8cfcb89a7debc1/examples/simple_net.cpp#L721), can I set parameters of all primitives in the vector and execute the entire vector? 
  
`stream->submit(net);`

**Comment by emfomenk** [comment]
No, starting with Intel MKL-DNN v1.0 this becomes impossible.

In the previous version that was possible (see [here](https://github.com/intel/mkl-dnn/blob/v0.18/examples/simple_net.cpp#L800)), but we found this way to be inconvenient for users and especially framework integration teams. So we decided to switch to the more explicit way, where you execute each primitive and pass all its inputs/outputs at that time.

Here is corresponding part of discussion in the [RFC for v1.0](https://github.com/intel/mkl-dnn/tree/rfc-api-changes-v1.0/doc/rfc/api-v1.0#34-passing-stream-and-inputoutput-memories-at-primitive-execution).

**Comment by dev2y** [comment]
I will give this a try.

@emfomenk thank you. I truly appreciate your quick responses.

**Comment by emfomenk** [comment]
You are welcome :)

**Comment by dev2y** [comment]
@emfomenk what is happening [here](https://github.com/intel/mkl-dnn/blob/002d23b36d96a9150acf57df6a8cfcb89a7debc1/examples/simple_net.cpp#L132)? 

Does the following somehow avoid memory allocation for Relu output? Or output is written to conv1_dst_memory from temp buffer after calculation?

```
    net_args.push_back({ { MKLDNN_ARG_SRC, conv1_dst_memory },
            { MKLDNN_ARG_DST, conv1_dst_memory } });

```

**Comment by igorsafo** [comment]
Hi @dev2y ,
ReLU operation supports in-place execution, which allows to avoid additional memory for destination. In this example ReLU takes the same memory for source and destination and doesn't allocate any temp buffers.

**Comment by dev2y** [comment]
@emfomenk 

We are wondering why Convolution is not converting input `nchw` to `nChw8c` in 2nd case.

**Case 1:**
Convolution primitive is created with input format set to `format:nchw` and output to `format:any`.
and we get 
`conv_forward_pd.weights_primitive_desc().desc().data.format` is `f32_Ohwi8o`.
`conv_forward_pd.dst_primitive_desc().desc().data.format` is `nChw8c`

so, this is good.

```
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_oihw out:f32_Ohwi8o,num:1,16x3x3x3,0.00379992
mkldnn_verbose,exec,convolution,jit:avx2,forward_training,fsrc:nchw fwei:Ohwi8o fbia:undef fdst:nChw8c,alg:convolution_direct,mb1_ic3oc16_ih416oh416kh3sh1dh0ph1_iw416ow416kw3sw1dw0pw1,6.1933
```
**Case 2:**
create pool primitive, src format set to `nchw`. It's output is also `nchw`.
set convolution src memory desc to pool's primitive dst desc (block propagation) 
set convolution dst memory desc to `format::any`
but now
get weights format from `conv_forward_pd.weights_primitive_desc().desc().data.format` is `f32_oihw`.
get dst format from `conv_forward_pd.dst_primitive_desc().desc().data.format` is `nchw`.

How do I force Convolution to use nChw8c and f32_Ohwi8o for better performance?
There is perf drop because of this.

```
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_oihw out:f32_oihw,num:1,32x16x3x3,0.0795001
mkldnn_verbose,exec,pooling,nchw_pooling:any,forward_inference,fdata:nchw fws:undef,alg:pooling_max,mb1ic16_ih416oh208kh2sh2ph0_iw416ow208kw2sw2pw0,65.3815
mkldnn_verbose,exec,convolution,gemm:jit,forward_training,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb1_ic16oc32_ih208oh208kh3sh1dh0ph1_iw208ow208kw3sw1dw0pw1,388.003
```

**Comment by dev2y** [comment]
I think we can close this.
