### ISSUE TITLE
mkl-dnn has a performance regression on windows

### ISSUE THREAD

**Issue by yufenglee** [intel/mkl-dnn#425]
MKL-DNN has a regression recently. Previously, MKL-DNN uses libiomp5md.dll as the openmp library on windows, but with the commit With the [commit](https://github.com/intel/mkl-dnn/pull/397), it uses visual studio’s opnemp lib VCOMP140.DLL that is slower, if built with vs.

**Comment by emfomenk** [comment]
Hi @yufenglee,

Could you please post the cmake command you used and its output?

**Comment by nathan-greeneltch-intel** [comment]
@yufenglee also, If you weren't aware, the cmake flag MKLDNN_THREADING can be set to  the following values:  **OMP**, OMP:INTEL, OMP:COMP, TBB .

**Comment by vpirogov** [comment]
Closing due to lack of acitivity. Feel free to reopen with additional data, including CMake logs.
