### ISSUE TITLE
zero padding primitive support

### ISSUE THREAD

**Issue by nhkrishna** [intel/mkl-dnn#433]
Hi,

I am trying to create a custom network using MKLDNN for inference in which one layer uses the asymmetric zero padding(top, bottom, left and right side of an image).
I'm not seeing any explicit padding operation primitive supported by MKLDNN. Is there any way to use the existing primitives to do the zero padding?

Also, i have tried using `pooling_forward` primitive with `pool kernel size as 1x1` and `strides as 1x1` with `padding kind as zero`. But i got output as large negative values instead of the zeros in the padding area. Please find the standalone maxpool layer [zeroPaddingUsingMKLDNN.cpp.txt](https://github.com/intel/mkl-dnn/files/2996571/zeroPaddingUsingMKLDNN.cpp.txt) for simple input to reproduce the issue with the zero padding.

#### Environment used
* MKLDNN version : v0.18
* OS : Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

Thanks,
Hari

**Comment by rsdubtso** [comment]
MKL-DNN does not provide primitives to perform padding. MKL-DNN primitives _assume_ that there are zeroes in the specified padding regions. We call it _logical_ padding as apposed to _physical_ padding which is actually zero data. Logical padding allows you to run 3x3 pooling with 1x1 padding and 5x5 pooling with 2x2 on the same input tensor without having to copy data.

The large negative values in the output of your test are the elements of the output tensor that were initialized to `-FLT_MAX` before computing the max pooling.

Do you have an operation in your network that requires physical padding?

**Comment by Wheest** [comment]
I've had a similar issue, and believe that I can explain.  I'm very new to using the library, so forgive me (and please correct me!) for any errors I make.

So we want to have "asymmetric padding" as you call it.  This can be essential when you want to do 'same' padding for a layer (where the output dimensions of each channel should be identical to the input dimensions, but you want to have free choice of stride, filter size, and dilation).

The configuration for a convolutional layer is performed by passing arguments to `mkldnn::convolution_forward::desc`.  If you look at the [docs for the struct](https://intel.github.io/mkl-dnn/structmkldnn_1_1convolution__forward_1_1desc.html), you will see that it can take three arguments for padding:

- `const memory::dims  	padding_l,` 
- `const memory::dims  	padding_r,`
- `const padding_kind  	apadding_kind`


I'm not sure what `apadding_kind` does, maybe if you want to do padding other than zero?  Zero seems to be the only permitted type though for now, going by the [options in the enum](https://intel.github.io/mkl-dnn/group__cpp__api__enums.html#gaa1ff931b28e0a90473ad5bddd21c60fc).

The other two arguments are what I think we are looking for.  So you should pass two `memory::dims` of size two.

So for example, initialising a convolutional layer as normal (such as in the [SimpleNet example](https://intel.github.io/mkl-dnn/ex_simplenet.html)), but with asymmetric padding:

```
// code here...
memory::dims conv_padding_l = { pad_hl, pad_wl };
memory::dims conv_padding_r = { pad_hr, pad_wr };
// more code here...
    /* create a convolution */
auto conv_desc
    = convolution_forward::desc(prop_kind::forward_inference,
                                convolution_direct, conv_src_md,
                                conv_weights_md, conv_bias_md,
                                conv_dst_md, conv_strides,
                                conv_padding_l, conv_padding_r,
                                padding_kind::zero);
// you guessed it, more code...        
```

For me:

```
pad_hl = top padding
pad_hr = bottom padding
pad_wl = left padding
pad_wr = right padding
```

I'm still doing tests to see if I've got the order of my paddings correct.  But hopefully this helps anyone that comes across this.  [The docs on convolution](https://intel.github.io/mkl-dnn/group__c__api__convolution.html) say "If padding_r is NULL, the padding is supposed to be symmetric.".  

Maybe they could be clarified to better explain `padding_l/padding_r`'s relationship to `top/bottom/left/right`?

**Comment by vpirogov** [comment]
Thanks for detailed explanation, @Wheest. 

Intel MKL-DNN supports tensors with one, two or three spatial dimensions. While the notion of `top` and `bottom` is clear for 2D objects this terminology becomes ambiguous for 3D objects. That's why the terms we use are `left` and `right` padding on certain dimension. 

I guess we should spell out what padding_l and padding_r do in the reference manual somewhere.
