### ISSUE TITLE
failed to create dilated convolution 

### ISSUE THREAD

**Issue by nwpu2fjl** [intel/mkl-dnn#438]
I tried to create dilated convolution on my MacBook Pro (Retina, 15-inch, Mid 2015).
![image](https://user-images.githubusercontent.com/12624852/55055969-ae8cdc80-509f-11e9-9f27-48f3e22091e5.png)
But I got an error!
![image](https://user-images.githubusercontent.com/12624852/55055983-bcdaf880-509f-11e9-9af5-009e729194d4.png)
What should I use dilated convolution?

**Comment by nwpu2fjl** [comment]
Sorry, It's my fault! The error is caused by invalid arguments.
![image](https://user-images.githubusercontent.com/12624852/55057735-fa8e5000-50a4-11e9-905e-1c1964c348ba.png)
It must be that our understanding of the dilated concept is different. In my opinion, the dilated value of no-dilated convolution should be 1, but factly 0 in mkldnn.
If I set the destination dimension(- 1 in my previous concept) by the below formulate, it is right.
dst_dim = (input_dim + 2 * pad - (dilated * (weight_dim - 1) + 1)) / stride + 1.
Am I right?

**Comment by igorsafo** [comment]
Hi @nwpu2fjl  MKL-DNN uses the following formula: dst = (src - ((dilate + 1)*(weights - 1) + 1))/ stride + 1 (https://github.com/intel/mkl-dnn/blob/master/src/common/convolution.cpp#L117), so you can just pass modified dilation to MKL-DNN to match your formula: mkldnn_dilate = dilate - 1

**Comment by nwpu2fjl** [comment]
Thanks for your reply. Right, I have modified my dilation(mkldnn_dilate = my dilation - 1), and got correct result!
