### ISSUE TITLE
Should not default to -Werror builds (even on product builds)

### ISSUE THREAD

**Issue by ezyang** [intel/mkl-dnn#440]
This issue was prompted by a recent CI breakage in PyTorch, which stemmed from the fact that MKL-DNN was configured to build with `-Werror`, and an upgraded of MKL caused MKL-DNN to start failing because there was use of newly deprecated functions that our version of MKL-DNN was using. Our request: do NOT default to `-Werror` builds; only turn on `-Werror` for developer builds of people working on MKL-DNN (and not for downstream users, and not for production builds). `-Werror` is very compiler sensitive and you are needlessly breaking builds for people who just want the thing to build so they can use it. In no way should these warnings break the build.

**Comment by rsdubtso** [comment]
This is an old debate. The errors PyTorch were getting are actually useful. They should not have been using an outdated MKL library with newer MKL-DNN. But I agree that there are situations where a compiler is overly protective (see #432). So I am flagging this as a proper bug.

**Comment by rsdubtso** [comment]
Please use `MKLDNN_WERROR=OFF` cmake build option when including MKL-DNN if you want it to be built without treating warnings as errors. The consensus in the team was that we want to continue building with the default `MKLDNN_WERROR=ON`.
