### ISSUE TITLE
Compilation error on Windows 10

### ISSUE THREAD

**Issue by rameshkunasi** [intel/mkl-dnn#441]
Hi,

I want to install MKL-DNN on windows 10 system. I have install intel parallel studio XE 2019 for intel c++ compiler 19 and followed the command given in "https://github.com/intel/mkl-dnn" to compile intel MKL-DNN. 

**Command** : **mkdir build & cd build && cmake -G "Visual Studio 15 2017 Win64" ..**
**Output**:
-- The C compiler identification is MSVC 19.16.27025.1
-- The CXX compiler identification is MSVC 19.16.27025.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- This is a product build
-- Detecting Intel(R) MKL: trying mklml_intel
-- Detecting Intel(R) MKL: trying mklml_gnu
-- Detecting Intel(R) MKL: trying mklml
-- Intel(R) MKL: include C:/Users/user/Desktop/mkl-dnn/external/mklml_win_2019.0.3.20190220/include
-- Intel(R) MKL: lib C:/Users/user/Desktop/mkl-dnn/external/mklml_win_2019.0.3.20190220/lib/mklml.lib
-- Intel(R) MKL: dll C:/Users/user/Desktop/mkl-dnn/external/mklml_win_2019.0.3.20190220/lib/mklml.dll
-- OpenMP lib: C:/Users/user/Desktop/mkl-dnn/external/mklml_win_2019.0.3.20190220/lib/libiomp5md.lib
-- OpenMP dll: C:/Users/user/Desktop/mkl-dnn/external/mklml_win_2019.0.3.20190220/lib/libiomp5md.lib
-- Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.8.15") found components:  doxygen missing components:  dot
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.20.1.windows.1")
CMake Warning (dev) at cmake/utils.cmake:120 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The plain signature for target_link_libraries has already been used with
  the target "mkldnn".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * cmake/utils.cmake:111 (target_link_libraries)

Call Stack (most recent call first):
  src/CMakeLists.txt:112 (target_link_libraries_install)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/user/Desktop/mkl-dnn/build

**Command**: **cmake -G "Visual Studio 15 2017 Win64" -T "Intel C++ Compiler 19.0" ..**
**Output**:

CMake Error at CMakeLists.txt:55 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 30-03-2019 17:11:17.
    Project "C:\Users\user\Desktop\mkl-dnn\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for Intel C++ Compiler 19.0 (Platform Toolset = 'Intel C++ Compiler 19.0') cannot be found. To build using the Intel C++ Compiler 19.0 build tools, please install Intel C++ Compiler 19.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\user\Desktop\mkl-dnn\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj]
    Done Building Project "C:\Users\user\Desktop\mkl-dnn\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\user\Desktop\mkl-dnn\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj" (default target) (1) ->
    (PlatformPrepareForBuild target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for Intel C++ Compiler 19.0 (Platform Toolset = 'Intel C++ Compiler 19.0') cannot be found. To build using the Intel C++ Compiler 19.0 build tools, please install Intel C++ Compiler 19.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\user\Desktop\mkl-dnn\build\CMakeFiles\3.13.2\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.14

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Users/user/Desktop/mkl-dnn/build/CMakeFiles/CMakeOutput.log".

Can anyone help me to resolve the error?

Thanks

**Comment by rsdubtso** [comment]
This issue is resolved (bf0b946768c3c26a8babd3cb304ab73405e6b0bb) in the mnt-v0 branch, but the fix was not backported to 0.18. I will back-port it as soon as possible.

**Comment by rameshkunasi** [comment]
Hi @rsdubtso ,

Thank you for your reply. I have modified the file "**cmake/utils.cmake**"  with what you have suggested. Even though I am getting same error.

Thanks
K.Ramesh

**Comment by rameshkunasi** [comment]
Hi, 
Now I am getting below error

**-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:55 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:55 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Users/user/Desktop/mkl-dnn/mkl-dnn/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/user/Desktop/mkl-dnn/mkl-dnn/build/CMakeFiles/CMakeError.log".**


Can Anyone help me to resolve this issue

**Comment by rameshkunasi** [comment]
I have resolved the issues. Please close this thread

**Comment by nathan-greeneltch-intel** [comment]
closing per user's request.
