### ISSUE TITLE
simple question about mkldnn::prop_kind::forward_inference

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#450]
When I test my network and using mkldnn::prop_kind::forward_inference in the primitives does mkl-dnn assumes the batch size equals one or can I still use a batch size of 128 for example?

thanks

**Comment by emfomenk** [comment]
Hi @zeno40,

`prop_kind::forward_inference` should be used whenever a user doesn't care about backward pass (for training). There are no assumptions on batch size -- you can use whatever you need. 

In this inference mode Intel MKL-DNN would not store some extra information (such as indeces of max elements in case of max pooling) that is required to compute backward pass, hence might give higher performance than `prop_kind::forward_training`.

**Comment by zeno40** [comment]
Thanks, now I understand!
