### ISSUE TITLE
environment settings for VM

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#453]
Do you have any recommendations to get best performance in VM? We are referring to these settings but these seem to not work in virtual machine. 

https://www.tensorflow.org/guide/performance/overview#tuning_mkl_for_the_best_performance

**Comment by emfomenk** [comment]
Hi @dev2y,

We don't have any specific recommendations for VMs. In general you want to pin threads (`KMP_AFFINITY`) and use as many threads as available.

What is performance difference you observe between VM and the corresponding host? I assume you use the same number of threads in the former and latter.

**Comment by nathan-greeneltch-intel** [comment]
@dev2y In the TF specific case, you should also set the inter/intra_op_parallelism_threads in your python script before launching your session(). You can see an example of this in the image recognition [tutorial](https://github.com/IntelAI/models/blob/master/docs/image_recognition/tensorflow/Tutorial.md) in Intel's AI model zoo.

Also, Intel hosts our own version of the CPU TF performance considerations [here](https://software.intel.com/en-us/articles/maximize-tensorflow-performance-on-cpu-considerations-and-recommendations-for-inference).

**Comment by nathan-greeneltch-intel** [comment]
closing due to >1 week with no response.
