### ISSUE TITLE
Does deconvolution support post_ops? 

### ISSUE THREAD

**Issue by TimingGu** [intel/mkl-dnn#455]
Hi, I tried to add post_ops to deconvolution to fuse "sigmoid"(eltwise_logistic), but it failed, dose deconvolution support post_ops? Thanks!

**Comment by vpirogov** [comment]
Hi @TimingGu,

Great question. Full set of activation functions (arbitrary eltwise and accumulation) is currently supported by convolutions only. Deconvolution does not support postops currently.

Note to self: this should be somewhere in documentation....

**Comment by TimingGu** [comment]
Thank you.
