### ISSUE TITLE
Unable to build latest mkl-dnn on Windows

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#456]
The error when building under VS2019:

Error	LNK2001	unresolved external symbol "int __cdecl mkldnn::impl::cpu::gemm_s8u8s32_jump_to_gemv_s8u8s32<struct mkldnn::impl::cpu::gemm_info_t<float,float,float> >(struct mkldnn::impl::cpu::gemm_info_t<float,float,float> *)" (??$gemm_s8u8s32_jump_to_gemv_s8u8s32@U?$gemm_info_t@MMM@cpu@impl@mkldnn@@@cpu@impl@mkldnn@@YAHPEAU?$gemm_info_t@MMM@012@@Z)	mkldnn	C:\Users\dhaen\Source\Repos\convnet\mkl-dnn\build\src\gemm_driver.obj	1	

In gemm_driver.cpp on line 32:
#include "s8x8s32/gemv.hpp"

this include file contains the problem:
int gemm_s8u8s32_jump_to_gemv_s8u8s32gemm_s8u8s32_jump_to_gemv_s8u8s32(T *args)
function defintion is not found

thanks

**Comment by densamoilov** [comment]
Hi @zeno40, thank you for reporting this issue, I suspect that you reproduced it with VS2019 in Debug mode, because this is the only case I was able to reproduce. We will fix it soon.
