### ISSUE TITLE
mkl-dnn uses -Werror by default

### ISSUE THREAD

**Issue by fenrus75** [intel/mkl-dnn#462]
While it's great to do your developer builds with -Werror... for production builds it's really not ok.

Every time we use -Werror for production builds, the werrorists win.

Don't let the werrorists win.

(And at least if you insist, make sure to test in your CI with the beta/daily builds of all the popular compilers, not just released versions)

**Comment by emfomenk** [comment]
Seems like duplication of #440?

**Comment by rsdubtso** [comment]
It is a duplicate indeed. If you do not use -Werror in your build system, please set `MKLDNN_WERROR=NO` if you are using the master branch, or set `MKLDNN_PRODUCT_BUILD_MODE=OFF` for older branches.

**Comment by ahkok** [comment]
There is not a single documentation line anywhere that documents this issue.

But really, it ought to be the other way around: users (consumers, like clearlinux, and other distros) should not have to delve deep into cmake files to determine how to get their software to build when a new gcc version is released. Developers who already know the code should have no problems knowing the impact of each cmake option.

**Comment by ahkok** [comment]
quote from the other thread is instrumental:

> you are needlessly breaking builds for people who just want the thing to build

**Comment by rsdubtso** [comment]
* We are  working on the docs.. the product is in the beta stage. 1.0 should have better coverage
* We will switch the default behavior

**Comment by ahkok** [comment]
woohoo!

**Comment by rsdubtso** [comment]
The default behavior has been changed in 67c911a50f998bd7821d9b3256013144ef003f6d (master) and 2f1ded189091be81b9ec0097ff1f85e14f31a884 (mnt-v0)
