### ISSUE TITLE
Performance drop on MKL-DNN's Winograd convolution

### ISSUE THREAD

**Issue by huangzhiyuan** [intel/mkl-dnn#466]
I am trying to gather the performance results of MKL-DNN's Winograd convolution with below case, but found performance drop when using Winograd convolution
```
shape = (16,3,1024,1024)
data = mx.symbol.Variable('data')
conv = mx.symbol.Convolution(data, num_filter=64, kernel=(3,3), pad=(1,1))
```
and mkldnn verbose info:
```
mkldnn_verbose,exec,convolution,jit:avx512_common,forward_inference,fsrc:nchw fwei:Ohwi16o fbia:x fdst:nChw16c,alg:convolution_direct,mb16_ic3oc64_ih1024oh1024kh3sh1dh0ph1_iw1024ow1024kw3sw1dw0pw1,85.0
```
Then I tried the Winograd with following command:
```
$ export OMP_NUM_THREADS=28
$ export KMP_AFFINITY=granularity=fine,compact 
$ numactl -l ./tests/benchdnn/benchdnn --conv --mode=CORRnPERF --mb=16 -v5 --dir=FWD_D     --alg=WINO ic3oc64_ih1024oh1024kh3sh1dh0ph1_iw1024ow1024kw3sw1dw0pw1
```
Result are below:
```
run: --dir=FWD_D --alg=wino mb16ic3ih1024oc64oh1024kh3ph1n"wip"
mkldnn implementation: jit_wino_4x3:avx512_core
@@@ [DST] final: diff: err:0, l0(``0.00487211``) l1:(1.18366e+13,1.18366e+13,1.65992e+06,``1.40237e-07``) l2:(4.18686e+08,4.18686e+08,76.1002,``1.81759e-07``) l8:(42751,42751,0.0390625,``9.13721e-07``)
0:PASSED __REPRO: --dir=FWD_D --alg=wino mb16ic3ih1024oc64oh1024kh3ph1n"wip"
perf,"wip",--dir=FWD_D --alg=wino mb16ic3ih1024oc64oh1024kh3ph1n"wip",57.9066,0,259.525,223.125,260.968,221.891
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):259.525 avg(ms):260.968
```
Confused to got the kernel time **85.0ms** origin, while **260.968ms** in Winograd, does this make sense?

**Comment by vpirogov** [comment]
In general using Winograd algorithm does not guarantee better performance in all cases, as it involves transform part, which is memory bound. Intel MKL-DNN has `algorithm::convolution_auto` that uses heuristics to choose the best algorithm for the problem in question.

The problem you show above has few input channels and the Winograd implementation may be suboptimal for this particular situation.

**Comment by vpirogov** [comment]
Closing due to the lack of activity.
