### ISSUE TITLE
error while creating reorder primitive

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#473]
I get `mkldnn_unimplemented error. Could not create reorder primitive` error when I tried to create reorder primitive. Only difference from simple_net implementation is that there is no data in memory during reorder constructor.

```
// create reorder
auto user_src_memory = memory(src_mem_desc, eng, nullptr);
auto dst_memory = memory(conv1_prim_desc.src_desc(), eng, nullptr);
auto pm = reorder(user_src_memory, dst_memory); // exception here

src_memory.set_data_handle(input_data);
dst_memory.set_data_handle(output_buffer); 
pm.execute(stream,
            { { MKLDNN_ARG_FROM, src_memory }, { MKLDNN_ARG_TO, dst_memory } });


```

please advice

**Comment by emfomenk** [comment]
Hi @dev2y,

I tried but failed to reproduce the behavior you observe.

The only guess I have is that the logical description of `src_memory` doesn't match the logical description of `dst_memory`, e.g. `src_memory.dim[0] != dst_memory.dim[0]`. Though, if your example is based on the simple_net example, this is highly unlikely.

Could you please send us the whole reproducer?

**Comment by dev2y** [comment]
@emfomenk I'm following simple_net to implement but I got this error in our code. I will try to get the whole reproducer but before that I will make sure that their logical desc match. thank you.

**Comment by vpirogov** [comment]
Closing due to the lack of activity.
