### ISSUE TITLE
Update on MKLDNN C API RNN

### ISSUE THREAD

**Issue by benjamim93** [intel/mkl-dnn#474]
I am currently working with mkldnn 0.18. It seems that in the latest version **mkldnn_forward_desc_init()** from C API RNN is split into 4 separate methods with specified cell types. 

Could you please tell me since which version the update was applied?
Also, is there any links to document of past versions?

Regards

**Comment by vpirogov** [comment]
This change (along with other incompatible [API changes](https://github.com/intel/mkl-dnn/blob/rfc-api-changes-v1.0/doc/rfc/api-v1.0/README.md)) is targeting v1.0 (currently developed in [master](https://github.com/intel/mkl-dnn/tree/master)). The v0.x releases are maintaining API compatibility and continue development in [mnt-v0](https://github.com/intel/mkl-dnn/tree/mnt-v0).

**Comment by vpirogov** [comment]
Just wanted to give a heads up on one more change in RNN API planned for v1.0. We will separate buffers used to store LSTM cell states and hidden states. The API in v0.x branch (mnt-v0) will not change.

**Comment by benjamim93** [comment]
Thanks for answering.
