### ISSUE TITLE
avx2 convolution pipeline utilization

### ISSUE THREAD

**Issue by hanzz2007** [intel/mkl-dnn#477]
in function `avx2_conv_fwd_kernel_f32::oh_step_unroll_kw` calc `oc_blocks * ur_w * oc_block` outputs in following loops(psueduocode):

```
for jj = 0 to ur_w
  ymm(oc_blocks*ur_w + jj) = load(input)

for  ii = 0 to oc_blocks
  ymm15 = load(weight)  // register conflicts blocking pipeline ? 
  for jj = 0 to ur_w
    vfmaddps(ymm(ii*ur_w + jj) , ymm15,  ymm(oc_blocks*ur_w + jj)
```

when oc_blocks=4, ur_w=3,  the  innermost loop can only do 3 fma ops, while we need at least 10 fma ops to full utilize the pipeline.
the `for  ii = 0 to oc_blocks` loop unroll can not make any help, for `ymm15`  conflicting  occupancy  in each loop iter preventing the pipeline, and register renaming can not help neither， because all 16 ymms are full utilized in this case.

Do I have a correct understanding about this?
btw, sorry for my poor English  ;)

**Comment by hanzz2007** [comment]
Only if the ymms have more corresonding internal registers to make register renaming work, the cpu  pipeline can be full utilized, otherwise the implementation here seems sub-optimal.

**Comment by akharito** [comment]
@hanzz2007 
In x86 CPUs a number of physical registers is more than architectural one. It means that during the execution of code above, the architectural register ymm15 will be mapped on different physical registers to resolve dependencies.

**Comment by vpirogov** [comment]
Closing this one as the question is addressed. Feel free to reopen or submit a new one to continue the discussion.
