### ISSUE TITLE
Is the encoding of vdpbf16ps correct?

### ISSUE THREAD

**Issue by herumi** [intel/mkl-dnn#485]
https://github.com/intel/mkl-dnn/commit/14964626468f44334785875b648f88b6d04c7399#diff-68a71ab0dc80a843565002071a8be491R2019

`vdpbf16ps()` uses `T_W1` but the encoding of vdpbf16ps in [the manual](https://software.intel.com/en-us/download/intel-architecture-instruction-set-extensions-and-future-features-programming-reference) shows `EVEX.128.F3.0F38.W0 52` so I think it should be `T_EW0`.
The latest version of [Xbyak](https://github.com/herumi/xbyak/) supports AVX512_BF16. Does it run well?

**Comment by emfomenk** [comment]
Thanks @herumi for noted this!
We are going to merge the latest changes of xByak to Intel MKL-DNN and see how it goes.
But, yeah, seems you are absolutely right!
