### ISSUE TITLE
code typo in rfc document

### ISSUE THREAD

**Issue by heagoo** [intel/mkl-dnn#490]
A code typo in https://github.com/intel/mkl-dnn/tree/rfc-api-changes-v1.0/doc/rfc/api-v1.0

There are some code like:
// C API
typedef struct {
    int arg; // MKLDNN_ARG_SRC, ...
    mkldnn_memory_t memory;
} mkldnn_exec_arg_t;

mkldnn_status_t mkldnn_primitive_execute(mkldnn_primitive_t prim,
    mkldnn_stream_t stream, int nargs, const mkldnn_exec_arg_t *args);

// C++ API
convolution_forward::execute(mkldnn::stream &stream,
    const std::map<int, mkldnn::memory> &exec_args);
// ... other primitives ...

// example C, convolution forward w/ bias
mkldnn_exec_arg_t conv_exec_args = {
    {MKLDNN_ARG_SRC, src_mem},
    {MKLDNN_ARG_WEIGHTS, weights_mem},
    {MKLDNN_ARG_BIAS, bias_mem},
    {MKLDNN_ARG_DST, dst_mem},
};

The declaration of conv_exec_args should be:
mkldnn_exec_arg_t conv_exec_args[]

**Comment by emfomenk** [comment]
Yeah, that's true. Thanks for catching that, @heagoo! Will fix!

**Comment by emfomenk** [comment]
Closed by 4c3d9a0
