### ISSUE TITLE
How to use avx2 while convolution algorithm is winograd?

### ISSUE THREAD

**Issue by fengyuICT** [intel/mkl-dnn#491]
### Environment
my intel cpu has avx2 instruction but don't have avx512, when I want to use winograd algorithm at git branch 0.18, it reports unimplements. So that's my question: How can I use winograd algorithm when the instruction set don't have avx512?

Thanks.

**Comment by emfomenk** [comment]
Hi @fengyulCT,

Thanks for your question! 

Unfortunately, Intel MKL-DNN doesn't have an implementation of Winograd convolution for avx2 (and below) systems. So at the moment it is impossible. Moreover, we don't have plans to work on it in the nearest future either...

**Comment by fengyuICT** [comment]
Hello @emfomenk ,
Can you explain why Intel MKL-DNN doesn't want to implementation the winograd for avx2. Because I think it's just use short width bit (avx2 can pack 256bit while avx512 can pack 512bit).
Thanks

**Comment by vpirogov** [comment]
This is a priority decision, as our main focus is enabling future architectures. If you are willing to develop the Winograd implementation for Intel AVX2 we would be glad to accept a pull request.

**Comment by fengyuICT** [comment]
Ok, I got it. thanks
