### ISSUE TITLE
F16 and INT8 support

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#493]
Hi,

I have few queries regarding the low precision inference.

In  which release the F16/BF16 support will be added to MKL-DNN? Do we need to have a specific  hardware for checking F16/BF16 support?

Does the INT8 inference runs on AVX2 supported processors or do we need any extra ISA extensions in order to do the INT8 inference?

 Thank you in advance

**Comment by emfomenk** [comment]
Hi @uu-praveeng,

- Initial BF16 appears in v0.20 (you can check the [RC-release](https://github.com/intel/mkl-dnn/releases/tag/v0.20-rc) here) and in master (that will soon become the v1.0). To test BF16 you need processor with Intel AVX512 instruction set -- at least Intel Xeon Scalable aka Skylake server. On these platforms the library would simulate behavior on actual BF16-capable HW which is still not available. Do not expect any performance improvements from BF16 on the current hardware, the only purpose is functional emulation (expect it to be 2x slower than f32).

- F16 works on [GPU ](https://github.com/intel/mkl-dnn#gpu-support) only, which support is available in master.

- To make INT8 work you need Intel AVX512 instruction set. Again Skylake server and newer. Cascade lake will lead to better performance. You can also check [OpenVino toolkit](https://github.com/opencv/dldt). This is a dedicate SW for inference on Intel HW. They have a fork of Intel MKL-DNN that has extended support of INT8 on AVX2 and even SSE4.2. So you can use it on most of the systems.

**Comment by vpirogov** [comment]
There's [a section](http://intel.github.io/mkl-dnn/dev_guide_data_types.html) in the developer guide covering data type support and hardware limitations related to data types.

**Comment by uu-praveeng** [comment]
Thanks for your prompt replies @vpirogov  and @emfomenk.

@emfomenk 
For BF16 inference , You mentioned **Do not expect any performance improvements from BF16 on the current hardware** . 
Does it mean that on hardware which as AVX512 the BF16 support is simulated?
Could you let us know the hardware that support the BF16 and when the Intel is planning to release them?

**Comment by emfomenk** [comment]
Hi @uu-praveeng,

> Does it mean that on hardware which as AVX512 the BF16 support is simulated?

Yes, we use a sequence of instructions of AVX512 to emulate BF16 instructions. See [here](https://github.com/intel/mkl-dnn/blob/9ee78d1b3f121341da09e0728fd0f32de9dece2a/src/cpu/jit_avx512_core_bf16cvt.hpp#L65-L91).

> Could you let us know the hardware that support the BF16 and when the Intel is planning to release them?

That would be Cooper Lake, which is expected around EoY 2019 (see [here](https://newsroom.intel.com/editorials/data-centric-innovation-summit/)).

> Generally the data(inputs,weights) would be in FP32 or FP16 format so inorder to use the bf16 , where the data type conversion from one format to other format happens? Do we have to convert and give bf16 inputs or would you internally handle the conversion?

FP16 is not supposed to be used with BF16. So the activations and weights are expected to be in either FP32 or BF16. Moreover, for the performance reasons the activations are mostly should be in BF16 (in order to use BF16-instructions). The weights can either be always in BF16, or you may want to keep a master copy of the weights in FP32, but always convert them to BF16 before calling convolutions. The latter approach in theory should give slightly better accuracy with minimal performance loss.
Yes, any FP32 <-> BF16 data movements require conversions. Intel MKL-DNN reorders are capable to handle that.

**Comment by uu-praveeng** [comment]
Regarding the INT8 . You have mentioned that INT8 will be supported only if we have the AVX512 ISA support . But we are able to run the simple-net-int8-cpp example on the CPUS which does not have avx512 instruction support .

Am I missing anything here?

FYI Below are my CPU details(using cat /proc/cpuinfo)
model name	: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf

Thank you,
Praveen.

**Comment by emfomenk** [comment]
@uu-praveeng,

Intel MKL-DNN optimizes Int8 computations for AVX512+ systems. On AVX2 and below we have reference or gemm-based implementations (which would perform more or less fine if you build the library with Intel MKL support). But anyways, with the current level of Int8 support on AVX2 and below systems it would be more correct to say that we don't support it.

We are thinking of adding Int8 optimizations for AVX2, and maybe even for SSE4.1 capable system, but we don't have any concrete plans...

**Comment by emfomenk** [comment]
Seems all questions are answered, so closing the issue.
Feel free to reopen or open a new one in case of additional questions.

**Comment by feixuedudiao** [comment]
how can i use the f16 for cpu ,can you give a example for it? i don't find the example to use the f16 in the document.

**Comment by yehudaorel** [comment]
> how can i use the f16 for cpu ,can you give a example for it? i don't find the example to use the f16 in the document.

Hi @feixuedudiao, for any new questions please create a new ticket and include all helpful detail such as specific target cpu, specific primitive/workload of interest.

Thank you!
