### ISSUE TITLE
Question about implicit zero padding

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#495]
Hi,

Does the implicit zero-padding, when the modulo of the number of channels with 8 and/or 16 isn't zero,  happening in all primitives and with all memory formats?

For example a inner product with 10 input/output channels in a plain nc format.

thanks

**Comment by emfomenk** [comment]
Hi @zeno40,

Implicit zero-padding happens only when constructing memory objects. But you are right, primitives are the driver factor for that.

In theory, zero-padding might happen for any memory format. Even with `nc`. But in practice, we only use padding for the blocked formats like `nChw8c`, `nChw16c` for activations, and like `OIhw4i16o4i` for weights.
Moreover, for the blocked formats it is a requirement for padded dims to be multiple of the block size. That is for `nChw8c` and `nChw16c` the padding for dim 1 (`c`) must be multiple of 8 and 16 respectively. For `OIhw4i16o4i` padding for dims 0 (`o`) and dim 1 (`i`) must both be multiple of 16.

> For example a inner product with 10 input/output channels in a plain nc format.

In this case the current implementation would not require any padding.

**Comment by zeno40** [comment]
Does the memory of the biases for primitives like conv or pooling also need zero padding when there's a optimized weight data format used? Or can we safely leave it to the nummer of output channels?

thanks

**Comment by emfomenk** [comment]
Bias is left as is. We decided it would be too much to ask to reorder bias, so we do padding internally. :)

**Comment by zeno40** [comment]
thanks

**Comment by emfomenk** [comment]
You are welcome!

I am closing this issue. Feel free to reopen this one or create a new one if you have any further questions.
