### ISSUE TITLE
Input memory formats supported by various operation primitives

### ISSUE THREAD

**Issue by nhkrishna** [intel/mkl-dnn#496]
Hi,

It was unclear about configuring, input memory primitives of operation primitives with desired memory formats. Because some operation primitives are not supporting memory primitives with particular data formats( such as #251, #459 ..etc). In this cases we are reordering the input data with supported data format and passing it to operation primitive. 
It would be helpful to support operation primitives with all data formats (or) any reference list/Documentation having operation primitives with supported/Unsupported data formats.

Thanks,
Hari

**Comment by emfomenk** [comment]
Hi @nhkrishna,

We recently improved our documentation drastically. In particular for all primitives we added a section `Data Representation` that indicates for what formats the primitive is optimized (in addition to the ones the appears after compute-bound primitives created with memory format `any`). For instance, here is the reference guide to [LRN](https://intel.github.io/mkl-dnn/dev_guide_lrn.html) which mentions that it should work fine for `nchw` and `nhwc` (in addition to `nChw8c`, `nChw16c`, or whatever comes out of the convolution). Also in the very beginning of this document we mention we require 2D spatial tensors.

So I hope the new documentation can reduce the confusion. Please let us if you have any concerns about it.

**Comment by nhkrishna** [comment]
Hi @emfomenk ,

Thanks for your response. I had gone through documentation for convolution and some other operation primitives. Documentation for the convolution operation primitive not mentioning about the nChw8c/nChw16c for input data. Also [sum](https://intel.github.io/mkl-dnn/dev_guide_sum.html) and [concat](https://intel.github.io/mkl-dnn/dev_guide_concat.html) primitives documentation saying **"The concat primitive works with arbitrary data tensors. There is no special meaning associated with any logical dimensions"**. Does it mean these primitives will supports all the data formats?

**Comment by emfomenk** [comment]
Hi @nhkrishna,

`nChw8c` and `nChw16c` are considered as the optimized formats. It doesn't make a lot of sense to list them all since they may change. The assumption is that the primitives must be perform well for the optimized/blocked formats. If this is not the case that is most likely a bug (if not, it must be mentioned in the documentation).

> Does it mean these primitives will supports all the data formats?

Yes, sum and concat support arbitrary formats. Implementation-wise these primitives are based on reorders that, of course, do support arbitrary memory format transformation.

**Comment by nhkrishna** [comment]
Hi @nhkrishna ,

I agree that, we will get better performance by using the optimized/blocked formats. But the problem is, if one of the layer outputs a blocked layout and then it's sub sequent layers may or may not support the same blocked layout. In such scenarios it would be helpful for us to know(using Documentation) the supported blocked layout of each layer, so that we will introduce reorder explicitly in that layer.

**Comment by nhkrishna** [comment]
Is there any update on this?

**Comment by shelleygoel** [comment]
Hi @nhkrishna ,

I recommend also going through [Memory format propagation](https://intel.github.io/mkl-dnn/cpu_memory_format_propagation_cpp.html) if you haven't already.

The principle idea is that each primitive (except Convolution and InnerProduct) should use output data layout of preceeding primitive as it's input memory format. This avoids reorders as much as possible.

**Comment by nhkrishna** [comment]
Hi @shelleygoel ,

Thanks for your response @shelleygoel. Earlier we have used MKLDNN v0.14 where we have faced few issues in using **concat**(In depth dimension) primitive with different input data formats(nchw and nChw8c). And we are not seeing this issue in latest versions(v0.18). Can you confirm on this whether this issue is resolved or not?
We are worried about these kind of issues in future and concerned in knowing supported data formats.

Thanks,
Hari

**Comment by emfomenk** [comment]
Hi @nhkrishna,

I am sorry for delay.

> Can you confirm on this whether this issue is resolved or not?

I can confirm that no matter what the input formats are, the concat should work fine along any dimension. If it does not, it is a bug a we need to fix it (and that seemed to happen between v0.14 and v0.18).

But of course, I cannot guarantee that Intel MKL-DNN is free from bugs. So the recommendation is to follow the programming model, and assume that non-compute-intensive primitive work fine with whatever *optimized* layouts came out of other Intel MKL-DNN primitives.

**Comment by emfomenk** [comment]
Also, in case of bugs we typically add regression tests if they very reported by our users. So if something like that happens, once fixed we will ensure that would not happen again.
