### ISSUE TITLE
How do you disable avx512

### ISSUE THREAD

**Issue by nwpu2fjl** [intel/mkl-dnn#500]
Is there a way to disable avx512 because my project can run on avx2 HW and crash on avx512. And the backtrace is as below:
![企业微信截图_038dedca-a3b1-42d5-8dbe-ed6e3c83be46(1)](https://user-images.githubusercontent.com/12624852/60315210-37196280-9998-11e9-9ef4-ada9899e7a35.png)
Given the above information, I wonder why the same project crash on the avx512 HW. So I want to solve this problem by disabling avx512.
-----------------------------------------------------------------------------

### Environment
HW flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm arat pln pts dtherm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt

HW flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 spec_ctrl intel_stibp

**Comment by vpirogov** [comment]
It seems like a floating point exception is happening when convolution algorithm "auto" is used on Intel AVX512. I cannot reproduce it on my side though. Would you please run the application with an environment variable `MKLDNN_VERBOSE=2` and post the log here?

As a workaround you can do one of the following:
1. Change convolution algorithm to `convolution_direct`
2. Patch [`mayiuse` function in src/cpu/cpu_isa_traits.hpp](https://github.com/intel/mkl-dnn/blob/master/src/cpu/cpu_isa_traits.hpp#L102) to return `false` for the ISA you want to disable.

**Comment by vpirogov** [comment]
Could you also let us know which Intel MKL-DNN version you are using?

**Comment by shelleygoel** [comment]
Also, How many cores are on the system (could you please paste result of `lspcu` or `cat /proc/cpuinfo`? Do you set the number of threads during runtime?

**Comment by nwpu2fjl** [comment]
Sorry for the late reply. I can't reproduce it because I haven't the real environment. The above information comes from the others developer's feedback who use my team's library that uses mkldnn.
Maybe I should compiler mkldnn on target HW instead of my local HW, although they have the same OS.

**Comment by emfomenk** [comment]
Hi @nwpu2fjl,

Our best guess so far is the old version of Intel MKL-DNN. Which version do you use?

Building the library on one system and running it on the other one is perfectly fine as long as the system you run the library is same or better in terms of supported ISA (see [MKLDNN_ARCH_OPT_FLAGS](https://intel.github.io/mkl-dnn/dev_guide_build_options.html)).

**Comment by nwpu2fjl** [comment]
In fact, my version is about one monthly ago. I will pull the newest git and try it and post feedback lately. Thanks all of you.
