### ISSUE TITLE
compiling error while make -j on ubuntu 18.10

### ISSUE THREAD

**Issue by yuqi98** [intel/mkl-dnn#506]
Hi! I'm using ubuntu 18.10 and I have libomp-dev, libtbb-dev installed. I'm having this error during the make -j step. Does anyone know how to fix this?

[ 45%] Building CXX object src/cpu/CMakeFiles/mkldnn_cpu.dir/simple_sum.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/common/CMakeFiles/mkldnn_common.dir/build.make:219: src/common/CMakeFiles/mkldnn_common.dir/memory_zero_pad.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [tests/gtests/gtest/CMakeFiles/mkldnn_gtest.dir/build.make:63: tests/gtests/gtest/CMakeFiles/mkldnn_gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2338: tests/gtests/gtest/CMakeFiles/mkldnn_gtest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:973: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_common_1x1_conv_kernel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:141: src/cpu/CMakeFiles/mkldnn_cpu.dir/cpu_reorder.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:167: src/cpu/CMakeFiles/mkldnn_cpu.dir/gemm/bf16/jit_avx512_core_gemm_bf16bf16f32_kern.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:869: src/cpu/CMakeFiles/mkldnn_cpu.dir/gemm_inner_product.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1077: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_core_bf16_1x1_convolution.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:557: src/cpu/CMakeFiles/mkldnn_cpu.dir/gemm/f32/jit_sse41_kernel_sgemm_kern.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1090: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_core_bf16_conv_kernel.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1558: src/cpu/CMakeFiles/mkldnn_cpu.dir/nspc_batch_normalization.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1519: src/cpu/CMakeFiles/mkldnn_cpu.dir/nchw_pooling.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1363: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_uni_dw_convolution.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1129: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_core_bf16_sum.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:63: src/cpu/CMakeFiles/mkldnn_cpu.dir/bfloat16.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:934: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx2_1x1_convolution.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1259: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_sse41_1x1_conv_kernel_f32.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:947: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx2_conv_kernel_f32.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:115: src/cpu/CMakeFiles/mkldnn_cpu.dir/cpu_engine.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1038: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_common_convolution_winograd.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1142: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_core_f32_wino_conv_2x3.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:882: src/cpu/CMakeFiles/mkldnn_cpu.dir/gemm_inner_product_utils.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1246: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_core_x8s8s32x_deconvolution.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:817: src/cpu/CMakeFiles/mkldnn_cpu.dir/gemm_bf16_convolution.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1376: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_uni_eltwise.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/cpu/CMakeFiles/mkldnn_cpu.dir/build.make:1233: src/cpu/CMakeFiles/mkldnn_cpu.dir/jit_avx512_core_x8s8s32x_convolution.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:184: src/common/CMakeFiles/mkldnn_common.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:239: src/cpu/CMakeFiles/mkldnn_cpu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by emfomenk** [comment]
Hi @yuqi98,

I guess make run too many compilations at the same time and your system might get out of memory.
Could you please try limiting the number of processes spawn by make, say:
``` sh
make -j9
```

As a general rule of thumb -- the number to be passed to make should be `2*cores + 1`. So in the example above I assumed you have 4 cores system.

**Comment by yuqi98** [comment]
Hi Thanks for responding. I tried to compile with make -j 4, and it can compile successfully but when I'm running my program that works fine on my mac, I got mkl-dnn/include/mkldnn.hpp:23:10: fatal error: mkldnn_config.h: No such file or directory. Do you have any idea of why is this?

**Comment by emfomenk** [comment]
`mkldnn_config.h` is generated on the fly. It should be installed along with other Intel MKL-DNN header files if you do `make install`. The typical usecase is:
``` sh
export MKLDNN_ROOT=/path/to/install/mkldnn
cmake -DCMAKE_INSTALL_PREFIX=$MKLDNN_ROOT ..
make -j 4

# build a program:
g++ -std=c++11 x.cpp -I$MKLDNN_ROOT/include $MKLDNN_ROOT/lib64 -lmkldnn
```

Alternatively, if you don't want to install MKL-DNN you might need to add `build/include` directory to the headers search path, since `mkldnn_confiig.h` and `mkldnn_version.h` are being generated there.

```

**Comment by emfomenk** [comment]
Updated the comment above (forgot to add `make install` in the snippet).

**Comment by yuqi98** [comment]
@emfomenk  I think I'm having error because of the administrative privileges during make install. Thank you so much for your help!

**Comment by emfomenk** [comment]
>  I think I'm having error because of the administrative privileges during make install.

Yeah, by default cmake will use /usr/local or something like that. So that's why you might want to use `-DCMAKE_INSTALL_PREFIX` to use user's directory instead of system-wide one.

**Comment by yuqi98** [comment]
@emfomenk  Sorry to bother again, I followed your steps, set my root to MKLDNN_ROOT=~/Desktop/zyq/mkl-dnn/mkldnn,  and it compiles correctly until when I'm running 
g++ -std=c++11 -I mkl-dnn/mkldnn/include/ -I mkl-dnn/mkldnn/lib/ x.cpp -lmkldnn 
it has the error 
/usr/bin/ld: cannot find -lmkldnn

If I ran it like 
g++ -std=c++11 x.cpp -I$MKLDNN_ROOT/include $MKLDNN_ROOT/lib -lmkldnn
it has error 
/usr/bin/ld: cannot find /home/bigcrawl/Desktop/zyq/mkl-dnn/mkldnn/lib: file format not recognized
/usr/bin/ld: cannot find -lmkldnn

**Comment by emfomenk** [comment]
Yeah, sorry there was a typo (forgot `-L`). Here is the fixed command line:
``` sh
g++ -std=c++11 x.cpp -I$MKLDNN_ROOT/include -L$MKLDNN_ROOT/lib64 -lmkldnn # also add -lomp, -fopenmp, or whatever is appropriate for the application itself
```

**Comment by yuqi98** [comment]
I'm still having trouble, it compiles fine with g++ -std=c++11 x.cpp -I$MKLDNN_ROOT/include -L$MKLDNN_ROOT/lib64 -lmkldnn, but have "error while loading shared libraries: libmkldnn.so.0: cannot open shared object file: No such file or directory" while execute the code

**Comment by emfomenk** [comment]
The dynamic linker cannot find `libmkldnn.so` dependency of the application. You can do two things here:
1. Before running application add `$MKLDNN_ROOT/lib64` to the `LD_LIBRARY_PATH` env var:
   ``` sh
   export LD_LIBRARY_PATH=$MKLDNN_ROOT/lib64:$LD_LIBRARY_PATH
   ./a.out
   ```

2. When linking an application add  `$MKLDNN_ROOT/lib64` to rpath so that dynamic linker knows where to locate the library:
    ``` sh
    g++ -std=c++11 x.cpp -I$MKLDNN_ROOT/include -L$MKLDNN_ROOT/lib64 -lmkldnn -Wl,-rpath,$MKLDNN_ROOT/lib64
    ./a.out
    ```

Hope this helps.

**Comment by yuqi98** [comment]
@emfomenk That works for me, thank you so much for your help!
