### ISSUE TITLE
gemm_* files and jit dependency in v1.0 --> file split?

### ISSUE THREAD

**Issue by kruus** [intel/mkl-dnn#519]
Support for some of the postops depends on JIT (ex. eltwise "injector"). This makes perfect sense.   But the file name does not begin with `jit_`.  Should `gemm_inner_product` split in two? For example:

1. current `gemm_inner_product` --> rename as `jit_gemm_inner_product`.
1. new `gemm_inner_product` --> use `extended_sgemm`, *without* JIT.
   - slight adaptation of the historical [non-jit] gemm inner product code (big improvement over `ref_inner_product`),
   - perhaps with same [reduced postops support] as `ref_inner_product`.

The observation may also apply to other layers that now depend on the jit "injector" mechanism (which is a neat design).

**Comment by kruus** [comment]
I guess similar issues also occurred in *older* mkl-dnn versions, just less frequently. It was not much work to provide a non-JIT version of `gemm_convolution`, for example.  But now so many areas of v1.0 are affected by the *"at least sse4.1"* assumption.  It would be nice to know if non-JIT ref impls are off the roadmap, since this is an understandable choice.

**Comment by rsdubtso** [comment]
They are probably on the 'best effort' support now... I don't think we would reject any PRs that make them work correctly, though.

**Comment by rsdubtso** [comment]
Closing. Please feel free to reopen if you have any further question.
