### ISSUE TITLE
Is there any plan to support double(fp64) precision?

### ISSUE THREAD

**Issue by carlushuang** [intel/mkl-dnn#521]
Is there any plan to support double(fp64) precision?

fp64 can have higher tolerance in rms error

**Comment by rsdubtso** [comment]
I am not aware of any plans for fp64. f32 seems to be good enough for many applications.

**Comment by carlushuang** [comment]
> I am not aware of any plans for fp64. f32 seems to be good enough for many applications.

Thanks for your reply. Indeed, I faced with convolution forward precision issue, so I just wonder if can use fp64 to work around. Let me have some time prepare the reproduce code.

**Comment by mirh** [comment]
https://github.com/oneapi-src/oneDNN/commit/d66a9619963cf288d0ea68c45c321b663538217d
https://github.com/oneapi-src/oneDNN/commit/693a2052419fc6ae54c430f6972ad790c378ec2c
This landed in [3.5](https://github.com/oneapi-src/oneDNN/releases/tag/v3.5) I think?
