### ISSUE TITLE
Segmentation fault when running my ip 

### ISSUE THREAD

**Issue by eladdidy** [intel/mkl-dnn#524]
I'm trying to add my FC layer to a model.
batch size is 1
input is flat vector with IC elements
weights is IC*OC matrix
bias is vector with OC elements
results size is same as bias
I get seg fault with executing the primite
can someone assist ?

thanks

elad 
-----------------------------------------------------------------------------

#define N  1
#define IC 3
#define OC 3
void test_FC()
{
    mkldnn_engine_t engine;
    CHECK(mkldnn_engine_create(&engine, mkldnn_cpu, 0));

    mkldnn_dim_t ip_user_src_sizes[2] = { N, IC };
    mkldnn_dim_t ip_user_weights_sizes[2] = { OC, IC };
    mkldnn_dim_t ip_bias_sizes[1] = { OC };
    mkldnn_dim_t ip_user_dst_sizes[2] = { N, OC };

    float net_src[N*IC];
    for(int i=0; i<N*IC;i++)
    	net_src[i] = 1;
    float net_dst[N*OC];
    for(int i=0; i<N*IC;i++)
    	net_dst[i] = 0;
    float W[OC*IC];
    for(int i=0; i<OC*IC;i++)
    	W[i] = 0.2;
    float B[OC];
    for(int i=0; i<OC;i++)
    	B[i] = 0;

    mkldnn_memory_t ip_user_src_memory;
    mkldnn_memory_t ip_user_weights_memory;
    mkldnn_memory_t ip_user_bias_memory;
    mkldnn_memory_t ip_user_dst_memory;

    mkldnn_memory_desc_t src_desc;
    mkldnn_memory_desc_t weights_desc;
    mkldnn_memory_desc_t bias_desc;
    mkldnn_memory_desc_t dst_desc;
    CHECK(mkldnn_memory_desc_init_by_tag(&src_desc, 2, ip_user_src_sizes,mkldnn_f32, mkldnn_nc));
    CHECK(mkldnn_memory_desc_init_by_tag(&weights_desc, 2, ip_user_weights_sizes,mkldnn_f32, mkldnn_oi));
    CHECK(mkldnn_memory_desc_init_by_tag(&bias_desc, 1, ip_bias_sizes,mkldnn_f32, mkldnn_x));
    CHECK(mkldnn_memory_desc_init_by_tag(&dst_desc, 2, ip_user_dst_sizes,mkldnn_f32, mkldnn_cn));

    CHECK(mkldnn_memory_create(&ip_user_src_memory, &src_desc, engine, net_src));
    CHECK(mkldnn_memory_create(&ip_user_weights_memory, &weights_desc, engine, W));
    CHECK(mkldnn_memory_create(&ip_user_bias_memory, &bias_desc, engine, B));
    CHECK(mkldnn_memory_create(&ip_user_dst_memory, &dst_desc, engine, net_dst));

    mkldnn_inner_product_desc_t ip_desc;
    CHECK(mkldnn_inner_product_forward_desc_init(&ip_desc, mkldnn_forward_inference, &src_desc, &weights_desc, &bias_desc, &dst_desc));
    mkldnn_primitive_desc_t ip_pd;
    CHECK(mkldnn_primitive_desc_create(&ip_pd, &ip_desc, NULL, engine, NULL));
    mkldnn_primitive_t ip;
    CHECK(mkldnn_primitive_create(&ip, ip_pd));

    mkldnn_exec_arg_t args[4];
    args[0].arg = MKLDNN_ARG_SRC;
    args[0].memory = ip_user_src_memory;
    args[1].arg = MKLDNN_ARG_WEIGHTS;
    args[2].memory = ip_user_weights_memory;
    args[2].arg = MKLDNN_ARG_BIAS;
    args[2].memory = ip_user_bias_memory;
    args[3].arg = MKLDNN_ARG_DST;
    args[3].memory = ip_user_dst_memory;

    mkldnn_stream_t stream;
    CHECK(mkldnn_stream_create(&stream, engine, mkldnn_stream_default_flags));
    std::cout << "mkldnn_primitive_execute: "<< std::endl;
    CHECK(mkldnn_primitive_execute(ip, stream, 4, args)); -- CRASH INSIDE
    std::cout << "mkldnn_stream_wait: "<< std::endl;
    CHECK(mkldnn_stream_wait(stream));

 //Clear mem objs
}

**Comment by eladdidy** [comment]
GDB shows nothing, However valgrind shows some errors
[valgrind.txt](https://github.com/intel/mkl-dnn/files/3464915/valgrind.txt)

**Comment by emfomenk** [comment]
Hi @eladdity,

Looks like a typo here:

``` cpp
args[1].arg = MKLDNN_ARG_WEIGHTS;
args[2].memory = ip_user_weights_memory;
```

In the second line it should be `args[1].memory...`.

**Comment by eladdidy** [comment]
Thanks
