### ISSUE TITLE
Running several instances of primitive i

### ISSUE THREAD

**Issue by eladdidy** [intel/mkl-dnn#526]
Hi all, 
I want to run several instances of the same primitive with different W/B/M/V params.
Can I exec all primitives at once and let engine handle data flow?
Or I need to exec 1 instance at a time and wait
2.
About IN/OUT buffers, can I resuse memory objects?
For example: I have FC at early stage and another FC in later stage in the net. 
Both  FC are using same primitie object and share IN/OUT memories (W+B different)

3.
Does the execution order as I write It acutally runs or some dependency check is done?

Thanks

Elad

**Comment by rsdubtso** [comment]
1. There are no dependency checks. The execution on the CPU is synchronous and our OpenCL GPU implementation only supports in-order OpenCL queues.

2. One thing to note about reusing primitives is that this (in general) requires using user-specified scratchpads:
    > With explicit scratchpad it is possible to make Intel MKL-DNN primitives stateless and hence thread safe: the same primitive can be executed in multiple independent threads as long as different threads use different scratchpads.

**Comment by eladdidy** [comment]
So there is no problem within the same thread to run the primitive consecutively with different  input/output, right?

Thanks

Elad

**Comment by rsdubtso** [comment]
Since currently CPU primitives are executed synchronously -- yes.

**Comment by rsdubtso** [comment]
Closing. Please feel free to reopen if you have any further question.

**Comment by avinashcpandey** [comment]
Hi,

CPU execution is still synchronous with latest OneDNN version? with OpenMP/ThreadPool

I want to run two different primitive simultaneous on one CPU. For that I am using one or two streams and creating both or one streams with out_of_order flag. Still I see it runs synchronously.

If  synchronous  CPU execution is not supported the what is the use of out_of_order?

**Comment by mgouicem** [comment]
Hi @avinashcpandey, yes CPU execution is synchronous for OMP/TP runtimes.
You can have asynchronous execution on CPU either by using the DPC++ runtime, or by using a separate thread to issue execute calls (e.g. using `std::thread`).

Regarding the out_of_order flag, it is not about concurrency with main thread, but about concurrency of primitive execution within a given stream. In particular DPC++ and OpenCL support out of order queues that do not implicitly synchronize consecutive kernel submissions. Currently, only the DPC++ runtime supports out_of_order streams in oneDNN.
