### ISSUE TITLE
Mixing mkldnn and some external code

### ISSUE THREAD

**Issue by eladdidy** [intel/mkl-dnn#527]
Hi all,
Can I use some IPP/MKL code between 2 consecutive primitives execution?

Thanks

Elad

**Comment by emfomenk** [comment]
Well, as long as the data in the format that can be fed into Intel MKL or Intel IPP (i.e. `nchw`, `nhwc`, etc), no problem with interleaving Intel MKL-DNN primitives with functions from any other libraries.

**Comment by eladdidy** [comment]
Thanks
