### ISSUE TITLE
Question: what is the alpha value when fusing relu into BN by flag 'fuse_norm_relu'

### ISSUE THREAD

**Issue by eladdidy** [intel/mkl-dnn#529]
I'm creating BN with the fuse_norm flag set.
Is it 0?

Thanks

Elad

**Comment by emfomenk** [comment]
Hi @eladdidy,

Yes, that is the only configuration that can be supported by training.
For `alpha != 0` you need to store the source of the relu, which makes fusion inefficient.

**Comment by emfomenk** [comment]
I will update [the documentation](https://intel.github.io/mkl-dnn/dev_guide_batch_normalization.html) to reflect this fact. Thanks for the question!
