### ISSUE TITLE
[QUESTION] [JIT PROFILING] what is stored in CPU registers ?

### ISSUE THREAD

**Issue by abdouskamel** [intel/mkl-dnn#530]
Hello everyone,

I have a question concerning jit profiling.

I dumped the JIT-kernel code of a convolution to a file. I want now to examine it. Here are the first few lines of the dump :

```
       0:	53                   	push   %rbx
       1:	55                   	push   %rbp
       2:	41 54                	push   %r12
       4:	41 55                	push   %r13
       6:	41 56                	push   %r14
       8:	41 57                	push   %r15
       a:	48 8b 07             	mov    (%rdi),%rax
       d:	48 8b 77 08          	mov    0x8(%rdi),%rsi
      11:	48 8b 57 10          	mov    0x10(%rdi),%rdx
      15:	48 8b 5f 18          	mov    0x18(%rdi),%rbx
      19:	48 8b 8f a8 00 00 00 	mov    0xa8(%rdi),%rcx
      20:	44 8b af 10 01 00 00 	mov    0x110(%rdi),%r13d
      27:	4c 8b b7 e0 00 00 00 	mov    0xe0(%rdi),%r14
```

I see that convolution parameters are stored in %rax, %rsi, etc but can't find which one stores the input address, which one stores the weights address and so on. Can anyone help me to find, for example by pointing me the code that calls the convolution kernels ?

Below information about my convolution : 

```
mkldnn_verbose,create,convolution,jit:avx2,forward_inference,src_f32::blocked:aBcd8b:f0 wei_f32::blocked:ABcd8b8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,alg:convolution_direct,mb8_ic32oc32_ih114oh112kh3sh1dh0ph0_iw114ow112kw3sw1dw0pw0,0.338135

mkldnn_verbose,exec,convolution,jit:avx2,forward_inference,src_f32::blocked:aBcd8b:f0 wei_f32::blocked:ABcd8b8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,alg:convolution_direct,mb8_ic32oc32_ih114oh112kh3sh1dh0ph0_iw114ow112kw3sw1dw0pw0,39.7891
```

Thank you.

**Comment by rsdubtso** [comment]
Hi!

Parameters to the convolution are packed in a structure and a pointer to this structure is passed to the kernel. On Linux it is passed in`rdi`. On Windows it is `rcx`. So the bunch of `push` instructions at the top is part of the standard function prologue, and the bunch of `mov` instructions are unpacking the parameters from the structure.

To understand the mapping, please read [the code that unpacks the structure](https://github.com/intel/mkl-dnn/blob/master/src/cpu/jit_avx2_conv_kernel_f32.cpp#L365) and [the register mapping](https://github.com/intel/mkl-dnn/blob/master/src/cpu/jit_avx2_conv_kernel_f32.hpp#L67).

**Comment by abdouskamel** [comment]
Hello @rsdubtso,

Many thanks for the detailed and fast answer, it's exactly what I'm looking for.

Issue closed.
