### ISSUE TITLE
Question: what is the SIMD(AVX**) support status?

### ISSUE THREAD

**Issue by eladdidy** [intel/mkl-dnn#531]
Is there a list of the SIMD optimization level supported for each primitive?
I mainly care about AVX512 code path for inner product.

Thanks

Elad

**Comment by emfomenk** [comment]
The optimizations mentioned on the [main page](https://github.com/intel/mkl-dnn/blob/master/README.md#system-requirements).
Intel MKL-DNN is optimized for avx2 and avx512 for both inference and training, on for sse4.1 and avx for inference.

**Comment by eladdidy** [comment]
Can someone explain how can know the avx* code my model is running?
For eltwise I see 'jit:avx2,forward_inference' but for inner_product I see 'inner_product:gemm'

Hi, I checked the docs and also the logs from execution and I'm a bit confused.
I found commit#[d181eb1](https://github.com/intel/mkl-dnn/commit/d181eb180b3e261428eff586b536c60f5b983a68l) but I can't find it in rls-1.0 code that I have.


Thanks

**Comment by eladdidy** [comment]
Is there a way to force mkldnn using AVX2 on AVX512 machine?

**Comment by emfomenk** [comment]
Hi @eladdidy,

If you built Intel MKL-DNN with external CBLAS library, Intel MKL-DNN will use cblas_sgemm to compute Inner Product. In this case the ISA used is controlled by that particular CBLAS library, not Intel MKL-DNN.
- If the CBLAS library you use is Intel MKL (or Intel MKL-ML), you can set `MKL_VERBOSE` environment variable to `1` to see what architecture the library dispatched. But I am pretty sure it would be the same as what Intel MKL-DNN uses.

**Comment by emfomenk** [comment]
> Is there a way to force mkldnn using AVX2 on AVX512 machine?

Only by recompiling the code. You can manually change the `avx512_*` cases [here](https://github.com/intel/mkl-dnn/blob/v1.0.1/src/cpu/cpu_isa_traits.hpp#L102-L131) to always return false. In this case the library would stop using AVX512.

**Comment by eladdidy** [comment]
O.k 
Thanks

**Comment by vpirogov** [comment]
Glad to help. Let us know if you have any further questions!
