### ISSUE TITLE
Does openvino MKLDNN support 2 CPUs (ex: xeon 6148 x 2)

### ISSUE THREAD

**Issue by fatalfeel** [intel/mkl-dnn#534]
https://www.asus.com/us/Commercial-Servers-Workstations/WS-C621E-SAGE/He...

https://software.intel.com/en-us/articles/intel-and-facebook-collaborate...

If I use 2 xeon 6148 cpus in 2 socket  of one mainboard (asus WS C621E)

Question: 2 cpus are faster than 1 cpu?

**Comment by emfomenk** [comment]
Hi @fatalfeel,

I think this question is better to ask on [OpenVINO](https://github.com/opencv/dldt) forum.
But AFAIK OpenVINO has some optimizations for multi-socket systems.

**Comment by rsdubtso** [comment]
I want to add that MKL-DNN itself does work fine on 2-socket systems and can schedule computations across two sockets. However, there may be cases when it is better to run two independent 'instances' one per socket, and it is OpenVINO that has to set such configuration up.

**Comment by fatalfeel** [comment]
I hope next release can do that well~~~some mainboard can put 4 cpus~~~

**Comment by vpirogov** [comment]
Intel MKL-DNN and OpenVINO do support multi-socket systems. For the best inference results on multi-socket systems we typically recommend running several instances pinned to cores within socket.
