### ISSUE TITLE
[QUESTION] How to use MKLDNN GEMM ?

### ISSUE THREAD

**Issue by abdouskamel** [intel/mkl-dnn#536]
Hello everybody,

I have a code that currently uses cblas_gemm (Intel MKL GEMM) and I want to replace it with MKL-DNN GEMM, as it is surely well optimized for common sizes found in deep neural networks.

The question is how to use the MKL-DNN implementation of GEMM ? I looked in the documentation but only found inner product, but it doesn't fit my needs as I want to use the different parameters of GEMM (alpha, beta, transpose and so on).

Can anyone guide me to find how to call MKL-DNN GEMM ?

Thank you.

**Comment by vpirogov** [comment]
Hi @abdouskamel,

Thank you for your question. Intel MKL-DNN's GEMM functionality is documented in [the API reference](http://intel.github.io/mkl-dnn/group__c__api__blas.html). Few notable differences with `cblas_sgemm`:
* Matrix layout is always assumed to be row-major and cannot be changed.
* Matrix transpositions is controlled using Fortran-style char arguments: 'N' for non-transposed case and 'T' for transposed case.
* `mkldnn_sgemm` returns error as `mkldnn_status_t`, while cblas_sgemm prints errors to the screen.

**Comment by abdouskamel** [comment]
Hello @vpirogov 

Many thanks for your answer, this is exactly what I was looking for.

Another question, if I can. Does this GEMM generates JIT code or can it be called without fear of overhead ?

**Comment by vpirogov** [comment]
GEMM does generate JIT to make sure that the binary has optimal code for the instruction set system support. Code generation happens once through the lifetime of the program. So this should not lead to visible overhead.

We also recently introduces primitive cache support that solves JIT overhead issues for all other primitives. It's available in master and will release in v1.1.

**Comment by abdouskamel** [comment]
Alright, thank you for detailed answers.

Issue closed.
