### ISSUE TITLE
Question: Shuffle for axis=1 group size = 1

### ISSUE THREAD

**Issue by eladdidy** [intel/mkl-dnn#539]
Does it mean anything to do shuffle for 1X512  axis =1, group size =1 ?
I checked the RAM and it looks all value remain in place.

Thanks
Elad

**Comment by emfomenk** [comment]
Hi @eladdidy,

I would say this is expected. Shuffle is essentially a *transposition* within a dimension. If the group size is `1` then you basically shuffle the axis `a` like that:
```a = a x 1   --(shuffle)-->   1 x a```
which is the same axis again.
For more please check the [documentation](https://intel.github.io/mkl-dnn/dev_guide_shuffle.html).

**Comment by vpirogov** [comment]
Feel free to submit a new issue or reopen this one if you have further questions.
