### ISSUE TITLE
"for each for each"

### ISSUE THREAD

**Issue by aaronjohnson** [intel/mkl-dnn#544]
I haven't figured out if this is auto-generated from elsewhere, is this enough or would it be better if I submit a PR.   Thank you.

https://github.com/intel/mkl-dnn/blob/0c4ef141218977084c4927def8027cafdda7c552/dev_guide_basic_concepts.html#L98

**Comment by rsdubtso** [comment]
Thanks for the report! Will fix this soonish.

**Comment by vpirogov** [comment]
This page is from developer guide, which is autogenerated from Markdown files sitting in [doc/](https://github.com/intel/mkl-dnn/tree/master/doc). The rest of the documentation referred to as API reference is autogenerated from Doxygen markup in [include/](https://github.com/intel/mkl-dnn/tree/master/include).

**Comment by aaronjohnson** [comment]
I  created a PR https://github.com/intel/mkl-dnn/pull/545

**Comment by vpirogov** [comment]
Resolved by #545
