### ISSUE TITLE
Q: Why primitive has been executed twice in benchdnn?

### ISSUE THREAD

**Issue by Leslie-Fang** [intel/mkl-dnn#546]
This is not a bug but a question.
It seems in the conv test in benchdnn.
Each primitive has been executed twice(In the if condition and in the measure_perf functions).
Please refer ti this snippet of code
https://github.com/intel/mkl-dnn/blob/286a4c2ec823e986048af7ee688d32b9814e775f/tests/benchdnn/conv/conv.cpp#L624-L670
Why does it design as this?

**Comment by rsdubtso** [comment]
Hi, thanks for the question.

The executions under the `if` conditions are for validating correctness, and the `measure_perf` is solely for performance benchmarking. They are separated mostly for code organization reasons: correctness validation depends on propagation kind and other primitive parameters; performance benchmarking does not.

Hope this helps.

**Comment by Leslie-Fang** [comment]
@rsdubtso  Got you.
Thanks a lot.
