### ISSUE TITLE
How to dump weights from MKLDNN as Ndarray

### ISSUE THREAD

**Issue by shoubhik** [intel/mkl-dnn#553]
Hi,
I have a use case where i need to debug the weights of Convolution layer when quantized by MKLDNN in MXNet [here](https://github.com/apache/incubator-mxnet/blob/master/src/operator/subgraph/mkldnn/mkldnn_conv.cc#L189-L190). The problem I am facing is that the model saved has the original fp32 weights and it is converted to int8 during runtime. When I do try to dump the `cached_weight_`  into a File as NDArray it is computed asynchronously and I get an error saying the weight is unavailable. The code I am using is something like this

```
LOG(INFO) << "Writing cached integer weight file";
      char cwd[200];
      getcwd(cwd, sizeof(cwd));
      std::string current_dir(cwd);
      LOG(INFO) << "The current dir is : " << current_dir;
      LOG(INFO) << "Writing qunatized cached weights to file";
      int num_args = 1;
      std::vector<NDArray> data(num_args);
      std::vector<std::string> names(num_args);
      data[0] = cached_weight_;
      names[0] = op_name;
      std::string cached_weight_file_path = current_dir + "/quantized-conv-weights/" + op_name;
      std::unique_ptr<dmlc::Stream> fo(dmlc::Stream::Create(cached_weight_file_path.c_str(), "w"));
      mxnet::NDArray::Save(fo.get(), data, names);
      LOG(INFO) << "Written weights to " + cached_weight_file_path;
``` 

-----------------------------------------------------------------------------

### Environment
DNNL includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
* OS version (`uname -a`)
* Compiler version (`gcc --version`)
* MKLROOT value (`echo MKLROOT=$MKLROOT`)
* CMake version (`cmake --version`)
* CMake output log
* git hash (`git log -1 --format=%H`)

### Steps to reproduce
Please check that the issue is reproducible with the latest revision on
master. Include all the steps to reproduce the issue. A short C/C++ program
or modified unit tests demonstrating the issue will greatly help
with the investigation.

### Actual behavior
Describe the behavior you see.

### Expected behavior
Describe the behavior you expect.

**Comment by pengzhao-intel** [comment]
@shoubhik thanks for reporting the problem of MXNet.
Could you open an issue in MXNet github and we can help you to resolve the problem?
https://github.com/apache/incubator-mxnet/issues

**Comment by shoubhik** [comment]
Created an issue with mxnet - https://github.com/apache/incubator-mxnet/issues/16177
