### ISSUE TITLE
Issue with the Shipped Libraries of latest release v0.21. MIssing DNNL libraries.

### ISSUE THREAD

**Issue by pranathibl** [intel/mkl-dnn#558]
In the latest release[ v0.21](https://github.com/intel/mkl-dnn/releases/tag/v0.21
), 
We haven't seen any DNNL libraries shipping for 0.21 release.
We are seeing mkl libraries instead of DNNL libraries.
Is DNNL libraries now part of MKL ?

Is any dependency with MKL introduced ?
In the previous [query ](https://github.com/intel/mkl-dnn/issues/503), You mentioned that dependency of MKL was removed with MKLDNN. Does this hold true now ?

Please elaborate on the queries ?

**Comment by rsdubtso** [comment]
1. We do not ship prebuilt MKL-DNN/DNNL libraries
2. Dependency on MKL/MKLML was removed from the 1.x branch, but not the 0.x branch which which was used to build 0.21. Hence, the 0.21 release also contains a new set of MKLML binary libraries.

**Comment by pranathibl** [comment]
Does MKL dependency added/removed intermittently based on requirement.
Why MKL is required for 0.x branch ? 

Are you planning to add MKL dependency even in 1.x branch ?
For which releases the MKLDNN/DNNL libraries are expected to ship ?

**Comment by rsdubtso** [comment]
>Does MKL dependency added/removed intermittently based on requirement. Why MKL is required for 0.x branch ?

Because of GEMM. 

> Are you planning to add MKL dependency even in 1.x branch ?

No. We improved GEMM performance in 1.x and therefore decided to remove dependency on MKL.

> For which releases the MKLDNN/DNNL libraries are expected to ship ?

We are not shipping binary MKLDNN/DNNL libraries for any releases. We are only making source releases on github. Binary packages are available from various distributions and other channels like conda. However, they lag the development significantly, so if you need any recent features it is best to build the library yourself.

**Comment by vpirogov** [comment]
What @rsdubtso said is correct only for v0.x releases (mnt-v0 branch). We do ship pre-built binaries for master starting from v1.0. You can find these in the release section:
* [v1.0](https://github.com/intel/mkl-dnn/releases/tag/v1.0)
* [v1.0.1](https://github.com/intel/mkl-dnn/releases/tag/v1.0.1)
* [v1.0.2](https://github.com/intel/mkl-dnn/releases/tag/v1.0.2)

The next planned release from this branch is v1.1.

**Comment by vpirogov** [comment]
Closing the issue due to lack of activity. Feel free to reopen if you have any further questions.
