### ISSUE TITLE
what int8 average pooling round mode?

### ISSUE THREAD

**Issue by chenqy4933** [intel/mkl-dnn#560]
I use the int8 average include pooling, and compare the result with my own C naive code, some times the error is +-1, I change my naive code with int/int and round away form zero, the results are also not exactly right. I find the source code in mkl-dnn, find _mm_cvtss_si32 , but I also don't know the round mode.

**Comment by vpirogov** [comment]
Hi @chenqy4933,

You can find reference pooling implementation [here](https://github.com/intel/mkl-dnn/blob/master/src/cpu/ref_pooling.cpp#L34). DNNL respects the rounding mode set by MXCSR register. Unless redefined by application the rounding is performed to nearest even integer (NRE).

**Comment by chenqy4933** [comment]
Thanks very much for your answer @vpirogov ，I get it.
