### ISSUE TITLE
need an example using concat primitive in the model 

### ISSUE THREAD

**Issue by lzhengchun** [intel/mkl-dnn#564]
I could not find an example of __concat__ primitive, the documents are not clear as well.

**Comment by vpirogov** [comment]
Hi @lzhengchun, thank you for the question. 

The closest thing to what you are looking for will be [concat gtest](https://github.com/intel/mkl-dnn/blob/master/tests/gtests/test_concat.cpp#L108). If you are running in specific issues with concat we would be glad to look at the code.

**Comment by emfomenk** [comment]
Hi @lzhengchun,

You can also take a look at [simple examples](https://gist.github.com/emfomenk/f2d6f328ce8787406ed9c3b9c657462c) I made some time ago.
Unfortunately, they are based on older Intel MKL-DNN v0.x, while the current version is v1.1. Version 1.x brought some incompatible changes (here is [the transition guide](https://intel.github.io/mkl-dnn/dev_guide_transition_to_v1.html)), but it should be relatively easy to tweak the examples to make them work with the latest version of DNNL / Intel MKL-DNN.

The example was written for #382 issue that you might also find helpful.

**Comment by vpirogov** [comment]
It would be nice to actually have these in the main repo and the developer guide. @louie-tsai, is this something that you may be interested in doing?

**Comment by lzhengchun** [comment]
> Hi @lzhengchun, thank you for the question.
> 
> The closest thing to what you are looking for will be [concat gtest](https://github.com/intel/mkl-dnn/blob/master/tests/gtests/test_concat.cpp#L108). If you are running in specific issues with concat we would be glad to look at the code.

Thanks @vpirogov that gtest is helpful. I have succeeded!
