### ISSUE TITLE
const qualifier in reorder::execute?

### ISSUE THREAD

**Issue by pinzhenx** [intel/mkl-dnn#571]
Wondering if the `src` could be `const` here
```cpp
void reorder::execute(stream astream, memory &src, memory &dst)
```
https://github.com/intel/mkl-dnn/blob/master/include/dnnl.hpp#L1982

**Comment by emfomenk** [comment]
Hi @pinzhenx,

For this particular case it probably could, but there few reasons why this is not done:
1. Unfortunately, when DNNL wraps memory buffer into memory objects it drops the `const` qualifier. In other words, `const memory &src` doesn't defend against writing to the memory buffer.
2. There is more to that. As you know, typical primitive execution happens using the [`map<argument_index, memory>`](https://github.com/intel/mkl-dnn/blob/master/include/dnnl.hpp#L279-L280) (e.g. [see here](https://github.com/intel/mkl-dnn/blob/master/examples/getting_started.cpp#L387-L392)). That was made for the clarity of passing arguments, but this approach prevents from adding const qualifier (even just to designate what memories are constant).

So for uniformity we decided to not add const qualifier to memory altogether. The Read-Only property is tracked internally accordingly to each primitive ([source](https://github.com/intel/mkl-dnn/blob/master/src/common/primitive_exec_types.cpp#L38-L47)):
``` cpp
switch (pd->arg_usage(arg)) { // input (const), output (mutable), or unused (dropped)
    case primitive_desc_t::arg_usage_t::input:
        if (args.count(arg) != 0) return invalid_arguments;
        args[arg] = {mem, true}; // <-- true means read-only
        n_inputs++;
        break;
    case primitive_desc_t::arg_usage_t::output:
        if (args.count(arg) != 0) return invalid_arguments;
        args[arg] = {mem, false}; // <-- false means read-write
        n_outputs++;
        break;
    case primitive_desc_t::arg_usage_t::unused: break;
}
```


The related discussion on const memory in general: #410.

**Comment by pinzhenx** [comment]
Much appreciated! Closing this issue.
