### ISSUE TITLE
Unable to find libiomp5.so when trying to run using the generated MKLDNN (libmkldnn.so) v1.0

### ISSUE THREAD

**Issue by pranathibl** [intel/mkl-dnn#574]
We generated libmkldnn.so using version v1.0. It seems libmkldnn.so was dependent on libiomp5 in each platform.

In Linux, Compiler Used - gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
In Windows - MSVS Compiler
libiomp5 was not found when i try to run the code.

When I try to build MKLDNN for previous versions such as v0.14 (or) v0.18, I was able to get libiomp5 .But I was not able to find any such library in MKLDNN v1.0

Where can I find libiomp5 library?

**Comment by emfomenk** [comment]
Hi @pranathibl,

Intel MKL-DNN v0.x had an option to be built against Intel MKL (which comes with `libiomp5.so` -- Intel OpenMP runtime). If a user chooses to do so, the `make install` command would copy Intel MKL-DNN library, Intel MKL library, and `libiomp5.so`.

Starting with Intel MKL-DNN v1.0 we removed that (optional) dependency on Intel MKL by porting all necessary functions from Intel MKL to Intel MKL-DNN. The OpenMP runtime is assumed to be the compiler's one. So if you built Intel MKL-DNN with GCC, the library would depend on `libgomp.so` and you don't need `libiomp5.so` at all.

Could you please elaborate on why you are looking for `libiomp5.so`?


> Where can I find libiomp5 library?

Just in case, you can find it in Intel MKL small libraries we shipped for Intel MKL-DNN v0.x releases. For instance, [here](https://github.com/intel/mkl-dnn/releases/tag/v0.21):
- mklml_lnx_2019.0.5.20190502.tgz
- mklml_win_2019.0.5.20190502.zip

**Comment by vpirogov** [comment]
Closing as the question seems to be addressed. Feel free to reopen if you have any further questions.
