### ISSUE TITLE
View GEMM kernel

### ISSUE THREAD

**Issue by wweic** [intel/mkl-dnn#578]
Hi,

I'm trying to inspect the GEMM kernel of my simple network following the guide https://intel.github.io/mkl-dnn/perf_profile.html, I can see relu and reorder kernel, but no GEMM. Is it because GEMM kernel wasn't JIT generated so it's not dumped? If so how can I dump the assembly for the GEMM kernel?

If I open jit trace, looks like `gemm` is simply forwarded to blas:
````
mkldnn_verbose,exec,inner_product,gemm:blas,forward_inference,fsrc:nc fwei:oi fbia:x fdst:nc,,mb4096ic64oc16,0.0300293
````

What's the suggested way to enable jit for GEMM then?

**Comment by rsdubtso** [comment]
Hi. Can you please provide *all* the information as per the issue template? The verbose output suggests that you are using 0.x branch.

**Comment by vpirogov** [comment]
@wweic, 

The library v0.x versions had an option to use GEMM from Intel MKL. This is a build time decision and you can see the information that Intel MKL was found in CMake log. If Intel MKL is not available in the build environment the library will use JIT GEMM implementation.

Starting from v1.0 the library always uses JIT GEMM and does not support building with third party BLAS.

Hope this helps.

**Comment by wweic** [comment]
Thanks @vpirogov @rsdubtso ! This is helpful. I'm resolving now.
