### ISSUE TITLE
 Commercial use permissions: MKL-DNN and MKL-ML

### ISSUE THREAD

**Issue by ly5234** [intel/mkl-dnn#579]
Hi,
Excuse me.
Does MKL-DNN library have commercial use permissions? Does MKL-ML have permissions?

Thank you!
Yue

**Comment by rsdubtso** [comment]
**I am not a lawyer and this is not a legal advice.**

DNNL (new name for MKL-DNN) is licensed under Apache 2 license which is OSI-approved. As per the OSI website, software licensed under OSI-approved licenses [can be used commercially](https://opensource.org/faq#commercial).

While mklml is under a proprietary license, the terms of the license do not prevent commercial use. The license poses the following requirements:
```
Use and Redistribution.  You may use and redistribute the software (the
"Software"), without modification, provided the following conditions are met:

* Redistributions must reproduce the above copyright notice and the following
  terms of use in the Software and in the documentation and/or other materials 
  provided with the distribution.                                              
* Neither the name of Intel nor the names of its suppliers may be used to
  endorse or promote products derived from this Software without specific prior
  written permission.                                                          
* No reverse engineering, decompilation, or disassembly of this Software is
  permitted.
```

**Comment by ly5234** [comment]
@rsdubtso Thanks your reply.
MKL-ML is a subset of MKL, right ?
So, is MKL-ML a necessary part of DNNL? Or does the DNNL library depend on Intel MKL-ML？

Thanks again.
Yue

**Comment by rsdubtso** [comment]
Hi @ly5234. Yes. MKLML is a subset of MKL. As of 1.1 DNNL is intended to be used standalone and does not require MKLML.

**Comment by ly5234** [comment]
@rsdubtso 
Ok, I got it.
Thank you.
