### ISSUE TITLE
Still requires omp.h when USE_OPENMP=OFF

### ISSUE THREAD

**Issue by yurivict** [intel/mkl-dnn#581]
```
In file included from /wrkdirs/usr/ports/math/mkl-dnn/work/mkl-dnn-1.1-rc-177-gf32e21b48/src/cpu/jit_uni_batch_normalization.cpp:20:
/wrkdirs/usr/ports/math/mkl-dnn/work/mkl-dnn-1.1-rc-177-gf32e21b48/src/common/dnnl_thread.hpp:42:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
```

1.1-rc-177-gf32e21b48
FreeBSD 12

**Comment by rsdubtso** [comment]
Can you please provide full build instructions as per the issue template? There is no `USE_OPENMP=OFF` build-time option for DNNL. If this is related to ideep, please file the bug with them.

**Comment by vpirogov** [comment]
@yurivict,

DNNL requires either OpenMP or TBB runtime and headers at build time. Choice of the runtime is managed with [build options](http://intel.github.io/mkl-dnn/dev_guide_build_options.html). If you are not building DNNL directly please report the issue downstream.
