### ISSUE TITLE
feature request: Permute/Transpose of a mem desc

### ISSUE THREAD

**Issue by pinzhenx** [intel/mkl-dnn#593]
This functionality is expected to have the same usage as `submemory` or `reshape` to create a 'permuted view' that can be directly attached to an old buffer **without actually reordering** the underlying data.

E.g.
```
abcd --> permute({1, 0, 2, 3}) --> bacd
ABcd16a16b --> transpose(0, 1) --> BAcd16b16a
```

I have come up with the following implementation that works perfectly on plain and blocking formats.
So how to make it more robust and will DNNL support this functionality in a later release?

```cpp
struct desc {
  desc permute(const dims &perms) const {
    // ... some checks here

    desc new_desc{};
    auto ndims = data.ndims;
    new_desc.data.ndims = data.ndims;
    new_desc.data.data_type = data.data_type;
    new_desc.data.format_kind = data.format_kind;
    new_desc.data.offset0 = data.offset0;

    // permute dims, padded_dims, padded_offsets, strides
    auto& new_dims = new_desc.data.dims;
    auto& old_dims = data.dims;
    auto& new_stride = new_desc.data.format_desc.blocking.strides;
    auto& old_stride = data.format_desc.blocking.strides;
    auto& new_paddim = new_desc.data.padded_dims;
    auto& old_paddim = data.padded_dims;
    auto& new_padoff = new_desc.data.padded_offsets;
    auto& old_padoff = data.padded_offsets;
    for (int i = 0; i < ndims; i++) {
      new_dims[i] = old_dims[perms[i]];
      new_stride[i] = old_stride[perms[i]];
      new_paddim[i] = old_paddim[perms[i]];
      new_padoff[i] = old_padoff[perms[i]];
    }

    // permute blocking
    auto inner_nblks = data.format_desc.blocking.inner_nblks;
    new_desc.data.format_desc.blocking.inner_nblks = inner_nblks;
    auto& old_inner_idxs = data.format_desc.blocking.inner_idxs;
    auto& new_inner_idxs = new_desc.data.format_desc.blocking.inner_idxs;
    auto& old_inner_blks = data.format_desc.blocking.inner_blks;
    auto& new_inner_blks = new_desc.data.format_desc.blocking.inner_blks;
    for (int i = 0; i < inner_nblks; i++) {
      new_inner_idxs[i] = perms[old_inner_idxs[i]];
      new_inner_blks[i] = old_inner_blks[i];
    }

    return new_desc;
  }
}
```

**Comment by emfomenk** [comment]
Hi @pinzhenx,

The function itself looks good to me, meaning that it indeed makes a logical axis permutation leaving the raw data untouched. Not every memory format can be re-thought like that, but the implementation works fine for the blocked-memory, which covers 99% of the cases in DNNL.
We actually use this implementation in deconvolution [1]. 

The biggest issue with this function however is that even if it succeeds, most likely there would be no primitives that support the resulting *permuted* memory format. The only exceptions I can think of are:
- Plain memory formats, in which case the *permuted* memory is again a plain memory format, but with different strides; So we might have some optimized primitives for that.
- Reorder, where we have very generic code generator that should handle arbitrary memory formats.

So, could you please elaborate more on what kind of problem you are trying to solve with this function?

---

[1] 

We have similar implementation in [`ref_deconvolution.hpp`](https://github.com/intel/mkl-dnn/blob/f3c3e02b0d93e8cab9f10a3ad951916c09fe87a7/src/cpu/ref_deconvolution.hpp) that uses convolution underneath: see [this](https://github.com/intel/mkl-dnn/blob/f3c3e02b0d93e8cab9f10a3ad951916c09fe87a7/src/cpu/ref_deconvolution.hpp#L98-L104) and [this](https://github.com/intel/mkl-dnn/blob/f3c3e02b0d93e8cab9f10a3ad951916c09fe87a7/src/cpu/ref_deconvolution.hpp#L52-L58). Essentially, the same code as what you wrote, but for a very particular permutation: `o <-> i`.

**Comment by pinzhenx** [comment]
Hi @emfomenk 
It's a coincidence that I came across this problem when I was also dealing with deconv to transpose `o <-> i`, because mkldnn didn't have `giodhw` yet ...
And for general purpose, I think it's useful for implementing `Transpose` and `Permute` in various frameworks.
