### ISSUE TITLE
MAC openmp issue

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#595]
Hi,
I  tried to do cmake for  mkldnn-1.0.4 and found that openmp is not found on MAC clang compiler  and hence mkldnn library is built without any openmp optimizations.

Is this expected behavior? If yes, is there anyway we could enable openmp optimizatios during cmake for mkldnn build on MAC .

I have attached the cmake log for your reference [log3.txt](https://github.com/intel/mkl-dnn/files/3846626/log3.txt)

It will be helpful to receive any suggestions regarding this. 

Thank you,
Praveen.

**Comment by sakulish** [comment]
Hi @uu-praveeng, AppleClang do not have pre-built OpenMP bits. Please try workaround from #591
