### ISSUE TITLE
questions about examples/cpu-cnn-inference-f32-cpp

### ISSUE THREAD

**Issue by tianyi93** [intel/mkl-dnn#597]
Hi, 

I am comparing the performance result using ```examples/cpu-cnn-inference-f32-cpp``` under different  OpenMP implementation as our group has developed an implementation of OpenMP called hpxMP and looking for different benchmarks to compare the performance.

Is it possible to change the problem size of the cpu-cnn-inference-f32-cpp, thanks.

**Comment by emfomenk** [comment]
Hi @tianyi93,

`examples/cpu-cnn-inference-f32-cpp` is not designed to be a performance benchmark. The sole purpose of it to show the programming model of DNNL.
I would strongly recommend you to test performance with [`benchdnn`](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn#benchdnn). It has already sets that we use to track performance: https://github.com/intel/mkl-dnn/blob/master/tests/benchdnn/inputs/conv/set_perf_cpu_all_mb

``` sh
$ export OMP_NUM_THREADS=....
$ export KMP_AFFINITY=... # or other OMP-related setting
$ # run forward f32 convolutions from different sets
$ numactl -l ./benchdnn --conv --mode=PERF --cfg=f32 --dir=FWD_D --batch=inputs/conv/set_perf_cpu_all_mb
```

**Comment by tianyi93** [comment]
@emfomenk  Thank you, I will try this out!

**Comment by emfomenk** [comment]
Close for now, please feel free to reopen or open a new issue if you have more questions or concerns.
