### ISSUE TITLE
Fix License

### ISSUE THREAD

**Issue by samskalicky** [intel/mkl-dnn#603]
# Summary
License copyright incorrect. Need actual copyright line for MKLDNN

# URLs
https://github.com/intel/mkl-dnn/blob/a0a87d662edeef38d01db4ac5dd25f59a1f0881f/LICENSE#L189

**Comment by samskalicky** [comment]
Heres an example with the copyright line:
https://github.com/dmlc/ps-lite/blob/60b826e4422fee0df00b892c66ffffea11e5da3f/LICENSE

**Comment by vpirogov** [comment]
Hi @samskalicky,

Thank you for the report. The part of text you are pointing to is an appendix to Apache v2 license explaining how to apply the license to source code. The license does not require this text to be altered in the LICENSE file. See Apache Spark project as [an example](https://github.com/apache/spark/blob/master/LICENSE#L189).

We include copyright line into each individual source file in the repository. See [here](https://github.com/intel/mkl-dnn/blob/master/include/dnnl.hpp#L2).

Please let me know if I'm missing anything.

**Comment by ChaiBapchya** [comment]
https://github.com/intel/mkl-dnn/blob/52c3052df8ec1d5b8b45cb6c350a952840eabd42/src/cpu/xbyak/COPYRIGHT

What type of license is this?

**Comment by TaoLv** [comment]
@ChaiBapchya It should be BSD-3, see here: https://github.com/intel/mkl-dnn/blob/master/LICENSE#L208

**Comment by TaoLv** [comment]
It's already included into the BSD-3 section of MXNet root LICENSE file: https://github.com/apache/incubator-mxnet/blob/master/LICENSE#L311

**Comment by samskalicky** [comment]
Thanks @vpirogov @TaoLv the problem with not having a copyright notice in the license file is that it makes it hard for consumers of the project to give the correct attribution. Not only do downstream projects have to check the license type, but they typically attribute the copyright for the project too. So having copyrights in individual files is fine, but having a single copyright statement for the whole project greatly eases the work of creation attributions like this one in MXNet:
https://github.com/apache/incubator-mxnet/blob/master/LICENSE#L249-L252

**Comment by vpirogov** [comment]
@samskalicky, thank you for clarifications. I agree that having copyright notice included into the license file will be helpful to downstream projects. I'll add this information.

**Comment by vpirogov** [comment]
Resolved by 88d4573ed5a13f69be27d7b97b43bddb8057c196
