### ISSUE TITLE
Document missing for c_api_types

### ISSUE THREAD

**Issue by LeicongLi** [intel/mkl-dnn#604]
# Summary
Currently, the documentation for c_api_types_arguments is missing.
I am having difficulties to identify the right parameters to perform an execution (e.g. whats the differences between DNNL_ARC_SRC_ITER and DNNL_ARC_SRC_ITER_C?), and I guess this might be a common issue for other users as well.
May I request a detailed documentation for it.
Thanks.

http://intel.github.io/mkl-dnn/group__c__api__types__arguments.html

```
/// @addtogroup c_api_types_arguments Argument indices
/// @{

#define DNNL_ARG_SRC_0 1
#define DNNL_ARG_SRC DNNL_ARG_SRC_0
#define DNNL_ARG_SRC_LAYER DNNL_ARG_SRC_0
#define DNNL_ARG_FROM DNNL_ARG_SRC_0

#define DNNL_ARG_SRC_1 2
#define DNNL_ARG_SRC_ITER DNNL_ARG_SRC_1

#define DNNL_ARG_SRC_2 3
#define DNNL_ARG_SRC_ITER_C DNNL_ARG_SRC_2
```
Include a short summary of the issue or request. Sections below provide
guidance on what factors are considered important for a documentation
issue.

# URLs
http://intel.github.io/mkl-dnn/group__c__api__types__arguments.html

# Additional details
Provide detailed description of the expected changes in documentation
and suggestions you have.

**Comment by rsdubtso** [comment]
Thanks for the report. I am already working on it. Should soon (~1w) be available in master.

**Comment by LeicongLi** [comment]
Thanks for the immediate respond.

**Comment by rsdubtso** [comment]
The documentation should now be available [here](https://intel.github.io/mkl-dnn/group__dnnl__api__primitives__common.html#ga53dc83e64489cd69bd82c1c2025eb5bd). Please let me know if this works for you.

**Comment by LeicongLi** [comment]
Hi@rsdubtso, thanks for the update.
After reading this doc, I might still need some help.

e.g. I would like to perform a Sum operation, which summing up a collection of tensors.
Input - a collection of tensors with same shape and data type.
Output - a single tensor of the same shape and type.
Which one should I use for input, DNNL_ARG_SRC or DNNL_ARG_SRC_ITER?

May I get an example of how to use it?

**Comment by rsdubtso** [comment]
Unfortunately, this part of the documentation is still missing. I'm reopening the issue so that we can track this. 

As for the example, the only readily available code I found is in the tests:
https://github.com/intel/mkl-dnn/blob/95d7487b51305c83a326b7dea0a2910fb4c85606/tests/gtests/test_sum.cpp#L217-L222

**Comment by vpirogov** [comment]
Developer guide pages for primitives were extended with a section called 'Execution arguments', that maps indices to argument names. See [convolution](http://intel.github.io/mkl-dnn/dev_guide_convolution.html) for example.
