### ISSUE TITLE
mkldnn library build options

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#605]
Hi,

Is there a way we could disable the AVX512 implementation during library build .
We want to include only AVX2 implementations as part of library, so that even when we execute a network on AVX512 machines it would use the AVX2 implementations.

Reason for this query is, currently we are seeing asseritons for depth concat layers  on AVX512 machines , when data formats are combination of nchw and nchw16c. 

It would be good to provide this option. Let us know if this option is already present.

Thank you,
Praveen.

**Comment by rsdubtso** [comment]
Hi Praveen,

Unfortunately there is no such option now. The only thing you can do is manually edit `src/cpu/cpu_engine.cpp` and comment-out or delete lines that refer to AVX512 implementations.

Can you please share the testcases where you are hitting the asserts?

**Comment by emfomenk** [comment]
Maybe a minor addition to @rsdubtso's answer: you also need to comment out [all avx512 cases](https://github.com/intel/mkl-dnn/blob/1c2e8e90c944b5db97bc66afa11e620e433f9ef9/src/cpu/cpu_isa_traits.hpp#L106-L121) in `src/cpu/cpu_isa_traits.hpp`. See the patch below.

But as @rsdubtso mentioned, it would be much better to understand what causes the problem now, since the same issue might arise in AVX2 path too (but maybe under different circumstances)... So, please feel free to file a bug with a way to reproduce it (we can start at least with the VERBOSE).

---

``` patch
diff --git a/src/cpu/cpu_isa_traits.hpp b/src/cpu/cpu_isa_traits.hpp
index 417e03f56..2f429b6bc 100644
--- a/src/cpu/cpu_isa_traits.hpp
+++ b/src/cpu/cpu_isa_traits.hpp
@@ -96,35 +96,37 @@ namespace {

 static Xbyak::util::Cpu cpu;
 static inline bool mayiuse(const cpu_isa_t cpu_isa) {
     using namespace Xbyak::util;

     switch (cpu_isa) {
         case sse41: return cpu.has(Cpu::tSSE41);
         case avx: return cpu.has(Cpu::tAVX);
         case avx2: return cpu.has(Cpu::tAVX2);
+#if 0
         case avx512_common: return cpu.has(Cpu::tAVX512F);
         case avx512_core:
             return true && cpu.has(Cpu::tAVX512F) && cpu.has(Cpu::tAVX512BW)
                     && cpu.has(Cpu::tAVX512VL) && cpu.has(Cpu::tAVX512DQ);
         case avx512_core_vnni:
             return true && cpu.has(Cpu::tAVX512F) && cpu.has(Cpu::tAVX512BW)
                     && cpu.has(Cpu::tAVX512VL) && cpu.has(Cpu::tAVX512DQ)
                     && cpu.has(Cpu::tAVX512_VNNI);
         case avx512_mic:
             return true && cpu.has(Cpu::tAVX512F) && cpu.has(Cpu::tAVX512CD)
                     && cpu.has(Cpu::tAVX512ER) && cpu.has(Cpu::tAVX512PF);
         case avx512_mic_4ops:
             return true && mayiuse(avx512_mic) && cpu.has(Cpu::tAVX512_4FMAPS)
                     && cpu.has(Cpu::tAVX512_4VNNIW);
         case avx512_core_bf16:
             return true && mayiuse(avx512_core_vnni)
                     && cpu.has(Cpu::tAVX512_BF16);
+#endif
         case isa_any: return true;
     }
     return false;
 }

 inline bool isa_has_bf16(cpu_isa_t isa) {
     return isa == avx512_core_bf16;
 }

```

**Comment by uu-praveeng** [comment]
Hi @emfomenk @rsdubtso ,

Thanks for the update.

We have created a custom network which has the input -> conv -> depth-concat
1. input dimensions - 1,3,64,64(n,c,h,w) which would be input to both conv and depth-concat. Its data format is configured as nchw
2.  conv output dimension  is 1,8,64,64 (n,c,h,w) . On AVX512 machines this is getting converted to output data format of nChw16c(with extra 8 padded channels). 
3. output memory primitive of depth concat is configured to 1,11,64,64 with format as **any**. We are seeing asserts **"could not create a concat primitive descriptor"**.

Let us know if dimension configuration of depth concat output memory  is error prone?
If yes , Could you suggest how to handle it.
Does the output dimension configuration of depth concat needs to 1,11,64,64 or 1,19,64,64?

Any help  you can provide is highly appreciated.

Thank you,
Praveen.

**Comment by emfomenk** [comment]
Hi @uu-praveeng,

What Intel MKL-DNN / DNNL version do you use?
We recently fixed exactly the problem you faced (related commits are: 7f1933661, c3809af1a, and 37c2f67ac).

The fix appeared in [DNNL v1.1](https://github.com/intel/mkl-dnn/releases/tag/v1.1.1) and also available in the latest master.
Could you please try using one these releases?

**Comment by uu-praveeng** [comment]
Hi @emfomenk ,

We are using the MKLDNN v1.0 . We will check and get back to you on this using latest version.
Meanwhile could you confirm how the configuration of output memory should be. 

I assume it to be 1,11,64,64?

Thank you,
Praveen.

**Comment by emfomenk** [comment]
> I assume it to be 1,11,64,64?

Sure, the output memory should have 11 channels, as you *logically* concatenate a tensor with 3 and 8 channels. The memory formats should not affect the logical operations :)

If concat is clever enough (even though I don't think it is) to use the blocked `nChw16c` memory format for the output, the padded channels would become 16 (as 11 rounded up to the block size). However this should be transparent to a user.

**Comment by vpirogov** [comment]
Environment variable and a function call to control dispatcher were added in 3fedfc69e4c9b6d8455ba4eb91b7277cb157de14. See documentation [here](http://intel.github.io/mkl-dnn/dev_guide_cpu_dispatcher_control.html).

If you still see an issue with concat behavior please provide a reproducer.
