### ISSUE TITLE
BN & Reorder performance regression

### ISSUE THREAD

**Issue by pinzhenx** [intel/mkl-dnn#610]
nChw16c
```
DNNL 1.1.1
perf,cpu,"wip",--bnorm --dir=FWD_I --tag=aBcd16b --flags=GS mb1ic2048ih7n"wip",0.0722656,0.0931788
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):0.0722656 avg(ms):0.0931788

MKLDNN 0.20.5 
perf,"wip",FWD_I,GS,f32,nChw16c,1,2048,1,7,7,0.0625,0.0305176,0.0421735
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):0.0305176 avg(ms):0.042173
```

nchw
```
DNNL 1.1.1
perf,cpu,"wip",--bnorm --dir=FWD_I --flags=GS mb1ic2048ih7n"wip",0.0424805,0.062501
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):0.0424805 avg(ms):0.062501

MKLDNN 0.20.5 
perf,"wip",FWD_I,GS,f32,nchw,1,2048,1,7,7,0.0625,0.0229492,0.0305618
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):0.0229492 avg(ms):0.0305618
```

**Comment by emfomenk** [comment]
More insights please :)

- How did you run benchdnn?
- What is the system (I guess it's Skylake, but home cores used, etc)?
- What compiler and OpenMP RT did you use?
   - Was Intel MKL-DNN v0.20.5 built with GCC but Intel OpenMP RT? If so, could you please re-run DNNL v1.1 with `LD_PRELOAD=libiomp5.so` just to confirm the difference doesn't come from the different libraries.

**Comment by pinzhenx** [comment]
Hi @emfomenk 

I previously force mkldnn built with GOMP. The following results were all using IOMP.

```
Skylake 8180
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 

export OMP_NUM_THREADS=56
export KMP_AFFINITY=granularity=fine,compact,1,0
```

```
DNNL
$ DNNL_VERBOSE=0 ./benchdnn --bnorm --dir=FWD_I --tag=aBcd16b --flags=GS --mode=p mb1ic2048ih7iw7
perf,cpu,"wip",--bnorm --dir=FWD_I --tag=aBcd16b --flags=GS mb1ic2048ih7n"wip",0.0493164,0.054051
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):0.0493164 avg(ms):0.054051

MKLDNN
$ MKLDNN_VERBOSE=0 ./benchdnn --bnorm --dir=FWD_I --fmt=nChw16c --flags=GS --mode=p mb1ic2048ih7iw7
perf,"wip",FWD_I,GS,f32,nChw16c,1,2048,1,7,7,0.0625,0.00952148,0.0112343
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):0.00952148 avg(ms):0.0112343
```

**Comment by emfomenk** [comment]
Thanks!

The picture is nice and clear, though not pleasant... :confused:
Will take a look into that! Thanks for the report!

**Comment by pinzhenx** [comment]
I also noticed that the performance of Reorder is much worse than before if src has same format as dst, no matter what format or size they are.

Here's an example:

```
DNNL
$ ./benchdnn --reorder --sdt=f32 --sdt=f32 --stag=nChw16c --dtag=nChw16c --mode=p 1x320x7x7

MKLDNN
$ ./benchdnn --reorder --idt=f32 --odt=f32 --ifmt=nChw16c --ofmt=nChw16c --mode=p 1x320x7x7
```


threads | dnnl (avg ms) | mkldnn (avg ms)
-- | -- | --
1 | 0.0853134 | 0.00334179
2 | 0.0467896 | 0.00326999
3 | 0.0335625 | 0.00280365
4 | 0.0263149 | 0.00256752
5 | 0.0218227 | 0.00229523
6 | 0.0192559 | 0.00230699
7 | 0.0169212 | 0.00240872
8 | 0.0167018 | 0.002212
9 | 0.0147134 | 0.00238238
10 | 0.0142527 | 0.00239831
11 | 0.0136945 | 0.0022774
12 | 0.012458 | 0.00250865
13 | 0.0117519 | 0.00233977
14 | 0.011507 | 0.00230867
15 | 0.0111178 | 0.00249798
16 | 0.0107166 | 0.00247868

**Comment by rsdubtso** [comment]
Hi @pinzhenx,

I am having troubles reproducing batchnorm or reorder results on my system. Can you please provide exact cmake command and output for both versions?

**Comment by pinzhenx** [comment]
Hi @rsdubtso 

It's no longer a problem after I built it with `-DCMAKE_BUILD_TYPE=Release`. Kinda weird though.

Thanks for your help. Closing it.

**Comment by rsdubtso** [comment]
Yeah, there is another reported issue about  inconsistent build system behavior when CMAKE_BUILD_TYPE is unset. A fix will soon be (or is already) promoted to master.
