### ISSUE TITLE
Windows debug build with ninja generator fails

### ISSUE THREAD

**Issue by nafest** [intel/mkl-dnn#612]
# Summary
The Windows debug build with ninja as generator fails. Probably because of the change in https://github.com/intel/mkl-dnn/commit/4e484f17d334ddf7f064fa48abf27c0d61042840 as the /bigobj flag isn't set for cpu_engine.cpp.

As a consequence I have the following build error:

`src\cpu\cpu_engine.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj`

# Version
Problem occurs with https://github.com/intel/mkl-dnn/commit/d9452ba4c34dc5654cad38b68c81fb7c8e3f6122

# Environment
Build on Windows x64 with VS2017

# Steps to reproduce
Configure the debug build with any other Generator than Visual Studio. E.g. with `-G Ninja` and build.

# Observed behavior
`src\cpu\cpu_engine.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj`

# Expected behavior
The build should work without problems.

**Comment by rsdubtso** [comment]
JFYI: should be fixed as soon as the fix is promoted from the internal repo.
