### ISSUE TITLE
How to perform Sum operation on non-consecutive tensors?

### ISSUE THREAD

**Issue by LeicongLi** [intel/mkl-dnn#614]
I would like to perform a Sum operation to sum up the results from previous operations. However the API provided to create Sum primitive descriptor requires the memory descriptors to be a consecutive array, and this seems unpleasant to use in some case.
I am wondering is there a work around to sum non-consecutive memory descriptors of data.

template makeOperator() {
  make src memory_desc
  make src memory object
  make dst memory desc
  make dst memory object
  make operator desc
  make operator primitive
  execute
  return dst memory object
} 

The template above would break if I would like to perform Sum on the results from multiple makeOperators, since we have to create the dst memory descs in advance as an array.
I would like to preserve the structure of this template, it makes each operators being independent from each other.

```
dnnl_status_t DNNL_API 

dnnl_sum_primitive_desc_create (dnnl_primitive_desc_t *sum_primitive_desc, 

const dnnl_memory_desc_t *dst_desc, int n, const float *scales, 

const dnnl_memory_desc_t *src_descs, const_dnnl_primitive_attr_t attr,

 dnnl_engine_t engine)

```

**Comment by dzarukin** [comment]
Hi @LeicongLi, thank you for the question.

In case two or more results should be summed, operation assumes it's given two or more sources. In the template you provided there's only one source and one destination. In such case, if this is a desire, no sum but copy will happen. I don't see any other way how to sum two sources without giving both of them to the library. The library asks for consecutive sources memory descriptors to be able to get the information correctly from both of them. In case there're just two sources, it's possible to use our 'binary' primitive which can do sum as well. It has a different interface (no consecutive sources memory descriptors restriction), but still there're two sources any way, not one.

If I missed something from your question, please provide more details on what you want to do and what do you expect from the library.

Thanks.

**Comment by LeicongLi** [comment]
Hi @dzarukin , thanks for the reply.

My question is I would like to sum over an array arry[n].
DNNL provides two APIs
1. sum(int*) which requires the data is consecutive.
2. sum(int a, int b) which does not require consecutive data
I am going to try the Binary approach, calling function sum multiple times.

Is there an example showing how to create a Binary primitive?

1. binary_desc_init(&binary_desc, src0_md, src1_md, dst_md)
2. How to create the Binary primitive desc? (calling primitive_desc_create(&binary_pd, binary_desc, attr, hing_forward)? I am not sure)
3. How to create Binary primitive? (primitive_create(&primitive, binary_pd)?)

I wish there could be an example for each operators..

**Comment by dzarukin** [comment]
Hi @LeicongLi,
Just we are on the same page:
>sum(int*) which requires the data is consecutive.
It doesn't require the data to be consecutive, only memory descriptors for those memories. Actual data is assigned per each index individually like:
```
args.set(DNNL_ARG_MULTIPLE_SRC + index, srcs[index]);
```
where srcs[index] each is an individual pointer to a piece of data.
But to create a primitive descriptor, user needs to pass a vector of memory descriptors which are consecutive in memory. If you have memory descriptors allocated separately, it's possible to allocate a new array and copy previously allocated mds into a new array or simply assign pointers to them, depending on what code is doing. If this approach is still inappropriate for you, then, probably binary primitive would help.

For C API benchdnn is a good source of ideas: https://github.com/intel/mkl-dnn/blob/master/tests/benchdnn/binary/binary.cpp (doit() and init_pd() functions).

```
binary_desc_init(&binary_desc, alg, src0_md, src1_md, dst_md);
primitive_desc_create(&binary_pd, binary_desc, attr, engine, NULL); // no backward prop kind, hint is not needed.
primitive_create(&primitive, binary_pd);
```

If this doesn't help much, don't hesitate to ask me.
Thanks.

**Comment by LeicongLi** [comment]
Thanks!
