### ISSUE TITLE
Enhance supported hardware definition in the doc

### ISSUE THREAD

**Issue by WilliamTambellini** [intel/mkl-dnn#618]
# Summary
In the sentence 
"DNNL supports systems based on Intel 64 architecture or compatible processors."
would it be possible to add a link to a formal definition of "Intel 64 architecture" ?
I have found that link :  
https://www.intel.com/content/www/us/en/architecture-and-technology/microarchitecture/intel-64-architecture-general.html
but a formal standard scientific publication would be very welcomed.
More precisely, does "Intel 64 architecture" strictly imply the "x86-64" standard architecture :  
https://en.wikipedia.org/wiki/X86-64
?
Kind
W.

# URLs
https://github.com/intel/mkl-dnn

# Additional details
Adding details and/or link to a clear definition of "Intel 64 architecture".

**Comment by vpirogov** [comment]
The documentation refers to Intel 64 architecture as defined in [Intel® 64 and IA-32 Architectures Software Developer Manuals](https://software.intel.com/en-us/articles/intel-sdm). Does this link help?

For most practical applications this is the same as x86-64, though there are some differences in behavior.

**Comment by WilliamTambellini** [comment]
Tks @vpirogov. 
This link helped but the question seems now to be if DNNL commits to run on any x86-64 CPUs or not.
The question is perhaps sensitive but I have to ask : as today, DNNL seems to work on some "non-Intel" x86-64 CPUs (at least the current AMD64 CPUs) but I need to know if such support (x86-64) will continue in the future or not. 
Kind regards
Ref:
https://en.wikipedia.org/wiki/X86-64#Differences_between_AMD64_and_Intel_64

**Comment by vpirogov** [comment]
Hi @WilliamTambellini, the phrasing "Intel64 and compatible processors" in the documentation indicates that the library supports non-Intel processors that implement compatible instruction set architecture, including AMD CPUs. Differences indicated in the wiki article are irrelevant for most of the software, including DNNL. We consider support for compatible processors important for the library adoption and there are now plans to change this.

**Comment by vpirogov** [comment]
Is this clear enough or you think the wording in the documentation should be further extended?

**Comment by WilliamTambellini** [comment]
Tks very much, your reply is clear enough. I would just prefer for that kind of statement to appear in the doc but it s up to you.
