### ISSUE TITLE
Dilated Convolution with NCHW format

### ISSUE THREAD

**Issue by LeicongLi** [intel/mkl-dnn#621]
Greetings!

I am using Dilated Convolution of DNNL 1.1.
My input is 4 dimension and with the format of NCHW.
I set the dilation as an Int array of length 2, e.g. int[2]{2, 2}, dilation value of 1.

The result I got from DIFF_SRC is unexpected, it seems it has done dilation for the first dimension, N.

the (n, ., ., .) has the same result as calculated by BLAS api.
the (n + 1, ., . ,.) is a zero-filled tensor, which I think it has been applied dilation, skipped.    

May I ask how to disable the dilation on the N dimension if the input is a batch.

Thanks.

**Comment by rsdubtso** [comment]
Can you please provide a dnnl/mkl-dnn version including hash, and a reproducer?

**Comment by vpirogov** [comment]
Closing as there's not enough data to investigate. Feel free to reopen with additional information.
