### ISSUE TITLE
submemory_desc() and reshape() documentation and/or sample

### ISSUE THREAD

**Issue by zulma46** [intel/mkl-dnn#622]
Hi,

I'm trying to channelwise split-up a tensor, wich is in 99% of the cases in a blocked nChw8c or nChw16c format, in two equal parts to serve as the source of two depthwise convolutions. 
I know i have to use the submemory_desc() with the desired dimensions and offsets but I don't how to 
correctly create the memory and I don't find enough documentation or good sample on how to accomplish this in a efficient manner.

thanks

**Comment by emfomenk** [comment]
Hi @zulma46,

Submemory allows you to describe a sub-part of a memory. Submemory doesn't do any data copy or move -- it is solely a view of a bigger memory. BTW, in Intel MKL-DNN v0.x submemory was exactly called `view`.

Rough sketch of what should be done is:
``` cpp
// a big memory, that contains two slices
memory::desc input_md({n, c, h, w}, data_type, ...); // md for memory desc
memory input(input_md, ...);

// create submemory descriptors for the slices
memory::desc slice1_md = input_md.submemory({n, c/2, h, w}, offset={0,   0, 0, 0});
memory::desc slice2_md = input_md.submemory({n, c/2, h, w}, offset={0, c/2, 0, 0});

// conv for slice 1
memory::desc conv1_src_any_md({n, c/2, h, w}, data_type, memory::format_tag::any);
convolution_forward::desc conv1_d(conv1_src_any_md, ...);
convolution_forward::primitive_desc conv1_pd(conv1_d, engine);
memory::desc conv1_src_md = conv1_pd.src_desc(); // query what convolution wants

memory conv1_src = input; // in case the reorder is not required
                          // conv1_src would be simply the original (big) input
if (conv1_src_md != slice1_md) { // check, if reorder is required (most likely it is)
  conv1_src =memory(conv1_src_md, engine); // allocate buffer for conv1_src
  // emit reorder between the slice of the input and conv1_src
}
```

Please also check #306 and #69.

> I don't find enough documentation or good sample on how to accomplish this in a efficient manner.

Yeah. We have plans to add some tutorials for submemory, but haven't done that yet :(

**Comment by zulma46** [comment]
Thanks a lot! 
Now it all make sense to me.
