### ISSUE TITLE
libmkldnn.so depend on libgomp.so or libiomp5.so

### ISSUE THREAD

**Issue by zhiqiu** [intel/mkl-dnn#625]
As described in README, libmkldnn.so depends on libgomp.so when compiled with GCC, and depends on libiomp5.so when compiled with Intel C/C++ Compiler.

Runtime configuration | Compiler | Dependency
-- | -- | --
DNNL_CPU_RUNTIME=OMP | GCC | GNU OpenMP runtime (libgomp.so)
DNNL_CPU_RUNTIME=OMP | Intel C/C++ Compiler | Intel OpenMP runtime (libiomp5.so)
DNNL_CPU_RUNTIME=OMP | Clang | Intel OpenMP runtime (libiomp5.so)
DNNL_CPU_RUNTIME=TBB | any | Threading Building Blocks (libtbb.so)
DNNL_GPU_RUNTIME=OCL | any | OpenCL runtime (libOpenCL.so)

But  libgomp.so is compiled with `STATIC_TLS` and libiomp5.so is not. So it will encounter 

> ImportError：dlopen：cannot load any more object with static TLS
when  using several DSOs with `STATIC_TLS`.

So, I wonder if there is any way to make libmkldnn.so depend on  libiomp5.so when compiled with GCC?

In addition, as far as I know, in commit aef88b, libmkldnn.so uses libiomp5.so if provided.

**Comment by emfomenk** [comment]
Hi @zhiqiu,

> So, I wonder if there is any way to make libmkldnn.so depend on libiomp5.so when compiled with GCC?

Unfortunately, no.
Currently, we assume that users either use gcc with GNU OpenMP RT, or icc with Intel OpenMP RT.

In v0.x, as you mentioned, we had a special path that allows substituting `libgomp` with `libiomp5` at link time. See [1] below.
The idea is that we need to drop `-fopenmp` flag at link time and replace it with explicit `-liomp5`.
However, this wasn't a reliable solution -- we haven't found how to reliably forbid cmake to pass `-fopemp` flag at link time (while having it at compilation), so for some versions of cmake we still get `libmkldnn` with dependency on both `libgomp` and `libiomp5`.



---

[1] `cmake/OpenMP.cmake`

``` cmake
macro(forbid_link_compiler_omp_rt)
    if (NOT WIN32)
        set_if(OpenMP_C_FOUND
            CMAKE_C_CREATE_SHARED_LIBRARY_FORBIDDEN_FLAGS
            "${OpenMP_C_FLAGS}") # this doesn't work reliably
        set_if(OpenMP_CXX_FOUND
            CMAKE_CXX_CREATE_SHARED_LIBRARY_FORBIDDEN_FLAGS
            "${OpenMP_CXX_FLAGS}")
        if (NOT APPLE)
            # one more attempt to get rid of libgomp.so
            append(CMAKE_SHARED_LINKER_FLAGS "-Wl,--as-needed") 
        endif()
    endif()
endmacro()
```

**Comment by vpirogov** [comment]
Closing as there's currently no reliable way to support this.
