### ISSUE TITLE
MacOS TBB build depends on libiomp5.dylib?

### ISSUE THREAD

**Issue by andoma** [intel/mkl-dnn#626]
Not sure if I misunderstand the docs or not, but as I read it the TBB version should **not** depend on libiomp5?

### iomp version

Depends on `libiomp5.dylib` as expected
````
$ otool -L mkldnn_mac_1.0.4_cpu_iomp/lib/libmkldnn.1.dylib
mkldnn_mac_1.0.4_cpu_iomp/lib/libmkldnn.1.dylib:
	libmkldnn.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
````

### TBB version

Depends on both `libiomp5.dylib` and `libtbb.dylib`?

````
$ otool -L mkldnn_mac_1.0.4_cpu_tbb/lib/libmkldnn.1.dylib
mkldnn_mac_1.0.4_cpu_tbb/lib/libmkldnn.1.dylib:
	libmkldnn.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
````

Briefly checked the 1.1 -versions and they  have the same dependencies.

**Comment by rsdubtso** [comment]
Hi @andoma, thanks for the report. I also see that there is a dependency, but there don't seem to be any symbols that refer to the OpenMP library. This looks like a bug in our build system. I'm guessing that we attempt to enable `#pragma omp simd` while trying to avoid having a full OpenMP dependency, but it seems like it does not work.

**Comment by rsdubtso** [comment]
A fix has been merged into our internal repo and will be promoted soon and will apply to the DNNL v1.2 release. Please let me know if you need it to be backported to 1.1.

**Comment by andoma** [comment]
@rsdubtso Thanks, I'm just starting to use DNNL so any version is fine for me.
