### ISSUE TITLE
the default constructor of "dnnl::isa_compat_info" cannot be referenced

### ISSUE THREAD

**Issue by jinz2014** [intel/mkl-dnn#629]
I am building the library using the latest parallel studio xe, and got the following error:
Thanks for your instruction.
 
[ 47%] Building CXX object tests/gtests/CMakeFiles/test_isa_mask.dir/test_isa_mask.cpp.o
/usr/include/c++/7.4.0/tuple(1652): error: the default constructor of "dnnl::isa_compat_info" cannot be referenced -- it is a deleted function
          second(std::forward<_Args2>(std::get<_Indexes2>(__tuple2))...)
                ^
          detected during:

 which icc
/opt/intel/compilers_and_libraries_2020.0.166/linux/bin/intel64/icc
 which icpc
/opt/intel/compilers_and_libraries_2020.0.166/linux/bin/intel64/icpc

**Comment by rsdubtso** [comment]
Hi @jinz2014. Thanks for the report. A fix for this bug is waiting for promotion from the internal repo which should happen within a couple of days as a part of the v1.2 preview.

**Comment by rsdubtso** [comment]
FWIW, the fix is straightforward:
```diff
diff --git a/tests/gtests/test_isa_mask.cpp b/tests/gtests/test_isa_mask.cpp
index 6f18d652f..21e9ca719 100644
--- a/tests/gtests/test_isa_mask.cpp
+++ b/tests/gtests/test_isa_mask.cpp
@@ -31,7 +31,7 @@ const std::set<cpu_isa_t> cpu_isa_all = {sse41, avx, avx2, avx512_mic,

 struct isa_compat_info {
     cpu_isa_t this_isa;
-    const std::set<cpu_isa_t> cpu_isa_compatible;
+    std::set<cpu_isa_t> cpu_isa_compatible;
 };

 // This mostly duplicates isa_traits, but the idea is to *not* rely on that
```
