### ISSUE TITLE
check that VNNI instructions are used

### ISSUE THREAD

**Issue by jinz2014** [intel/mkl-dnn#630]
HI 

Can you please explain how to verify that VNNI instructions are used when running an int8 matrix multiply on a CPU that supports it ?  I can think of looking at the assembly code. It is better to ask for recommendation for specific instructions.  

Thanks

**Comment by rsdubtso** [comment]
Hi @jinz2014 . Can you please clarify what you mean by `verify`? If you don't need programmatic verification, then you can just look at the output after enabling the [verbose mode](https://intel.github.io/mkl-dnn/dev_guide_verbose.html) or, if you need more details, [look at the disassembly of the JIT-generated kernels](https://intel.github.io/mkl-dnn/dev_guide_inspecting_jit.html).

**Comment by jinz2014** [comment]
Could you explain how a user can do programmatic verification ?  
The verbose mode does not show any verbose information for the int8 GEMM on a CPU.  Is that expected ?

**Comment by jinz2014** [comment]
-rw-rw-r-- 1 cc cc  57234 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.10.bin
-rw-rw-r-- 1 cc cc  59266 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.11.bin
-rw-rw-r-- 1 cc cc  53986 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.12.bin
-rw-rw-r-- 1 cc cc  55970 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.13.bin
-rw-rw-r-- 1 cc cc  55378 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.14.bin
-rw-rw-r-- 1 cc cc  57346 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.15.bin
-rw-rw-r-- 1 cc cc  55794 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.8.bin
-rw-rw-r-- 1 cc cc  57730 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemm_s8u8s32_kern.9.bin
-rw-rw-r-- 1 cc cc  16848 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemv_s8x8s32_kern.16.bin
-rw-rw-r-- 1 cc cc  11728 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemv_s8x8s32_kern.17.bin
-rw-rw-r-- 1 cc cc  11728 Jan 11 01:08 dnnl_dump_jit_avx512_core_gemv_s8x8s32_kern.18.bin
-rw-rw-r-- 1 cc cc   2650 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_an_kern.0.bin
-rw-rw-r-- 1 cc cc   9990 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_at_kern.4.bin
-rw-rw-r-- 1 cc cc   1822 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_bn_kern.1.bin
-rw-rw-r-- 1 cc cc   1446 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_bt_kern.5.bin
-rw-rw-r-- 1 cc cc   4622 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_sum_an_kern.2.bin
-rw-rw-r-- 1 cc cc  13838 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_sum_at_kern.6.bin
-rw-rw-r-- 1 cc cc   3010 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_sum_bn_kern.3.bin
-rw-rw-r-- 1 cc cc   2118 Jan 11 01:08 dnnl_dump_jit_avx512_core_u8_copy_sum_bt_kern.7.bin

It is not clear why quite a few gemm kernels are generated..

**Comment by rsdubtso** [comment]
This is because GEMM kernels are pre-generated once and because GEMM consists of multiple JIT-ed parts. Also, `DNNL_VERBOSE` only works for DNNL primitives, but not for GEMMs. Also, I don't see any programmatic way to verify that GEMMs execute VNNI. Can you please explain what you are trying to achieve?

**Comment by jinz2014** [comment]
Could you recommend a way to verify that VNNI instructions are used on a
CPU that supports them ?  Does a user need to look at every JIT-ed part of
GEMM for VNNI instructions ?

Thanks

**Comment by rsdubtso** [comment]
What I've described previously is a way to check if any VNNI instructions have been *generated*. To do that you need to inspect the generated kernels. Alternatively, you may modify DNNL (probably the Xbyak part) to your liking to extract this information easier.

If you want to know whether VNNI instructions would be *executed* for a particular workload, you may run your application under an [Intel SDE](https://software.intel.com/en-us/articles/intel-software-development-emulator) and collect instruction histograms.

If you describe the original problem you are trying to solve, maybe I would be able to provide some saner solutions.

**Comment by jinz2014** [comment]
Thanks again for your suggestions!
