### ISSUE TITLE
Floating point exception with unit test "test_convolution_forward_u8s8fp"

### ISSUE THREAD

**Issue by jzha136** [intel/mkl-dnn#637]
# Summary
make test failed for several unit tests.

# Version
rls-v1.0 883133c3b97d27fc6eb976b2cea2a25252f0d911

# Environment

* CPU make and model 
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
* OS version (`uname -a`)
Linux iZ8vbi18phbt0xgofpsvomZ 3.10.0-327.ali2012.alios7.x86_64 #1 SMP Mon Oct 9 14:09:14 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`gcc --version`)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
* CMake version (`cmake --version`)
cmake version 3.14.3
* CMake output log
-- GPU support is disabled
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jingwei.zhang/src/mkl-dnn/build_rls-v1.0
# Steps to reproduce
./tests/gtests/test_convolution_forward_u8s8fp

# Observed behavior
Note: Google Test filter = *:-*_GPU*
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from Forward_SimpleSmall_Blocked_Attributes_CPU/convolution_test
[ RUN      ] Forward_SimpleSmall_Blocked_Attributes_CPU/convolution_test.TestConvolution/0
Floating point exception (core dumped)
# Expected behavior
Test to pass

GDB result:
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7695483 in Xbyak::util::Cpu::getNumCores (this=0x7ffff7dcf540 <_ZN6mkldnn4impl3cpu12_GLOBAL__N_1L3cpuE>, level=Xbyak::util::CoreLevel)
    at /home/jingwei.zhang/src/mkl-dnn/src/cpu/xbyak/xbyak_util.h:253
253			case CoreLevel: return numCores_[level - 1] / numCores_[SmtLevel - 1];

=> 0x00007ffff77babc8 <+1816>:	divl   0x614bbe(%rip)        # 0x7ffff7dcf78c <_ZN6mkldnn4impl3cpu12_GLOBAL__N_1L3cpuE+12>

**Comment by jzha136** [comment]
Test passed on latest master branch.

**Comment by vpirogov** [comment]
@jzha136, thank you for verifying with the latest master. Are you ok to proceed with using the latest master or you need a v1.0.x patch release?

**Comment by vpirogov** [comment]
Assuming that backport is not needed. Please let me know if that's not the case.
