### ISSUE TITLE
Support for Intel NNP

### ISSUE THREAD

**Issue by WilliamTambellini** [intel/mkl-dnn#640]
Hello
Would it be possible to have some early estimations whether DNNL will support the NNP processors (at least the Inference one) : 
https://www.intel.ai/nervana-nnp
From that page, the only supported devices today are CPU and GPU :
https://intel.github.io/mkl-dnn/dev_guide_data_types.html
Ref:
https://www.intel.ai/wp-content/themes/ai/inc/nnp-react-apps/images/interactive/nnpi/scene8B.jpg

**Comment by vpirogov** [comment]
Hi @WilliamTambellini,

[OpenVINO toolkit](https://software.intel.com/en-us/openvino-toolkit) will be the primary software tool to enable NNP-I hardware. We are evaluating feasibility of having NNP-I enabled with DNNL, there's no plan in place though at this point.

**Comment by WilliamTambellini** [comment]
Thank you @vpirogov 
I m skeptical that openvino ("Develop Multiplatform Computer Vision Solutions") is an appropriate technology to run NLP (Natural Language Processing) NN models.
That's unfortunate. 
Thanks anyway. 
Refs:
https://fortune.com/2020/01/20/natural-language-processing-business/
https://en.wikipedia.org/wiki/Natural_language_processing

**Comment by vpirogov** [comment]
Thank you for the feedback. I'll bring this to the attention to NNP-I developers.

I would like to note that the inference engine component of OpenVINO has the scope beyond computer vision and supports language models, including [GNMT](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_GNMT_From_Tensorflow.html) and [BERT](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_BERT_From_Tensorflow.html).

**Comment by WilliamTambellini** [comment]
Thank you for the links, interesting. 
I see though that OpenVINO seems more : 
- a "model runner", not a low level NN library like DNNL 
- mainly for inference
so the advantages of DNNL remain (training, flexibility, ...).
Up to you to close that ticket but to try to move forward at least a little : are you aware of any documentation about the NNP low level API ?
Kind
W.

**Comment by vpirogov** [comment]
@WilliamTambellini,

you are right, inference engine is a model deployment tool and it does not support training. At this point NNP-I is not released and no public documentation is available on the API.

**Comment by vpirogov** [comment]
With [recent changes](https://www.forbes.com/sites/moorinsights/2020/01/31/intel-lays-out-strategy-for-ai-its-habana) to Intel AI roadmap the NNP support question is moot.

**Comment by WilliamTambellini** [comment]
Thanks. I m still confused when discovering today's article : 
https://www.intel.ai/intel-nervana-nnp-i-shows-best-in-class-throughput-on-bert-nlp-model/#gs.vrhgbx
but let's keep that ticket close till NNP-I comes to end user market.
