### ISSUE TITLE
a question on the int8 inference example

### ISSUE THREAD

**Issue by masahi** [intel/mkl-dnn#641]
Hi, I have a question regarding the usage of scale parameters in [cnn_inference_int8.cpp example](https://github.com/intel/mkl-dnn/blob/master/examples/cnn_inference_int8.cpp). What is the purpose of "channel-wise scaling factors for convolution" below?
https://github.com/intel/mkl-dnn/blob/master/examples/cnn_inference_int8.cpp#L76-L80

I understand other scale related parameters. From the size of "conv_scales" vector I'm assuming it is used in some way for output scaling. I'm wondering what it is different from [dst_scales](https://github.com/intel/mkl-dnn/blob/master/examples/cnn_inference_int8.cpp#L74) that you already have there.

**Comment by TaoLv** [comment]
See the `Per-Channel Scaling` section on https://intel.github.io/mkl-dnn/dev_guide_attributes_quantization.html.

**Comment by masahi** [comment]
got it, it is ```output_scale(oc)```. 

Thanks.
