### ISSUE TITLE
does DNNL support Intel GPU for pytorch?

### ISSUE THREAD

**Issue by alex-111-gh** [intel/mkl-dnn#642]
Hi, according to the main readme DNNL support "CPU and GPU" for the following packages, including Pytorch. Is it real for GPU? How to make pytorch use Intel GPU as compute backend?

**Comment by vpirogov** [comment]
Hi @alex-111-gh, 

While DNNL supports both CPUs and GPUs some enabling work is required on the application side to take advantage of GPUs. To my best knowledge Pytorch is not enabled for Intel integrated GPUs at this moment. I would suggest addressing the question on Pytorch enabling plans to Pytorch developers.

**Comment by vpirogov** [comment]
Feel free to reopen if you have any further questions.
