### ISSUE TITLE
Feature request: dnnl sgemm batch

### ISSUE THREAD

**Issue by WilliamTambellini** [intel/mkl-dnn#644]
# Summary
The gemm blas api today only offer 2d gemm. 
https://intel.github.io/mkl-dnn/group__dnnl__api__blas.html#ga75ee119765bdac249200fda42c0617f8
This feature proposes to add (single precision) support for batched gemm:
https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemm-batch
https://software.intel.com/en-us/articles/introducing-batch-gemm-operations
"The sgemm_batch routines perform a series of matrix-matrix operations with general matrices. They are similar to the sgemm routine counterparts, but the sgemm_batch routines perform matrix-matrix operations with groups of matrices, processing a number of groups at once. The groups contain matrices with the same parameters."

# Problem statement
No batched gemm. Workarounds could be to call multiple sgemm in a for loop or using a innerproduct prim without bias (tbc).

# Preferred solution
dnnl_status_t DNNL_API dnnl_sgemm_batch(...)

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

With DNNL v1.2 which will be released soon we introduced [MatMul primitive](https://intel.github.io/mkl-dnn/dev_guide_matmul.html). It supports 2d (aka gemm) and 3d (aka batched gemm) cases. It has a little bit less convenient API than `sgemm_batch()` which is a pure function, but the benefits are that it can be used on both CPU and GPU, it supports more data types and fusion with activation functions.

Would this work for you?

**Comment by WilliamTambellini** [comment]
Hi @emfomenk  
Cool, I was probably looking at the 1.1 doc so did nt know about that new primitive. That should work for me. Tks.

**Comment by emfomenk** [comment]
Thanks for confirmation, @WilliamTambellini!

I forgot to mention one important difference between `sgemm_batch()` and MatMul. The later expects that the batch matrices can be represented as 3d tensor. For instance for matrices A the 3d tensor will be `[batch, m, k]`.
This is a bit stricter requirement than what `sgemm_batch()` has:
- the matrices within a batch must have the same shape, e.g. same `[m, k]` for matrices A; and
- the matrices have regular offset one from another, while `sgemm_batch()` could take a `batch` number of pointers for matrices A.

Does this work for you too?

Finally, an important performance disclaimer. In DNNL v1.2 MatMul is optimized for 2D cases only (i.e. no batch or batch = 1). The real batched case will fall back to the reference code. We will fix that in the one of the next releases. So if you find the functionality useful please let us know and we will try to pull the optimization in earlier.

**Comment by yao-matrix** [comment]
@emfomenk , @vpirogov 
Hi, Evarist,
I came across this discussion while I am seeking batch gemm options in DNNL for transformer model. And it seems in transformer multi-head attention, we meet the difference issues you mentioned above.
The question is as below:
![image](https://user-images.githubusercontent.com/7245027/80061563-345dae80-8564-11ea-87b0-11cf3b64c96c.png)

We want to map this problem to a batched matmul with bsx3 matmuls(MKN=5x36x1), but since their is a 3 in the middle of M and N, we cannot use DNNL API to fit this usage.

Do you have any plan on such case support? Thx

**Comment by emfomenk** [comment]
Hi @yao-matrix,

No, at the moment we don't.
Essentially, this is a batched-batched matmul (2 batch dimensions instead of 1).

```
A: bs x 5 x 3 x 36  | B1 x M x B2 x K
B: bs x 1 x 3 x 36  | B1 x N x B2 x K
------------------
C: bs x 3 x 5 x  1
```

But it should be possible to call batched matmul trice:

```
for i = 0 .. 3:
    A: bs x 5 x (i) x 36
    B: bs x 1 x (i) x 36
    --------------------
    C: bs x 5 x (i) x  1
```

**Comment by yao-matrix** [comment]
@emfomenk Yes, we call call batch gemm trice and see the performance btw MKL batched gemm and MKL-DNN batched gemm, and see how things going.
Do you have some estimation on the performance difference btw these 2 options, if you think the performance will be similar, I think it will be a good thing, :).

**Comment by ahuizxc** [comment]
@emfomenk  Hi Evarist, I just tested the method as you mentioned to achieve our batch matmul, and the result was not good :( .

The performance of bf16 even worse than fp32, and both of them worse than mkl fp32 MklCblasGemmBatch

I modified the examples/primitives/matmul.cpp. Here is my test code 
```
#include <algorithm>
#include <cmath>
#include <iostream>
#include <string>
#include <vector>

#include "dnnl.hpp"
#include "example_utils.hpp"
#include "bfloat16.hpp"
using namespace dnnl;

using tag = memory::format_tag;
using dt = memory::data_type;
using bfloat16_t = dnnl::impl::bfloat16_t;

#define TEST_BF16

void matmul_example(dnnl::engine::kind engine_kind) {

    // Create execution dnnl::engine.
    dnnl::engine engine(engine_kind, 0);

    // Create dnnl::stream.
    dnnl::stream engine_stream(engine);

    // Tensor dimensions.
    const memory::dim MB = 1023, // batch size
            M = 150, K = 36, N = 1;
    const int head_number = 3;

    // Source (src), weights, bias, and destination (dst) tensors dimensions.
    memory::dims src_dims = {MB, M, K};
    memory::dims weights_dims = {MB, K, N};
    // memory::dims bias_dims = {1, 1, N};
    memory::dims dst_dims = {MB, M, N};

    // Allocate buffers.
    std::vector<float> src_data_f32(product(src_dims)*head_number);
    std::vector<float> weights_data_f32(product(weights_dims)*head_number);
    std::vector<float> dst_data_f32(product(dst_dims)*head_number);
    
    std::vector<bfloat16_t> src_data(product(src_dims)*head_number);
    std::vector<bfloat16_t> weights_data(product(weights_dims)*head_number);

    std::vector<bfloat16_t> dst_data(product(dst_dims)*head_number);

    // Initialize src, weights, bias.
    std::generate(src_data_f32.begin(), src_data_f32.end(), []() {
        static int i = 0;
        return float(i++ / 10.f);
    });
    std::generate(weights_data_f32.begin(), weights_data_f32.end(), []() {
        static int i = 0;
        return float(i++ * 2.f);
    });

    // convert to bfloat16
    cvt_float_to_bfloat16(src_data.data(), src_data_f32.data(), product(src_dims)*head_number);
    cvt_float_to_bfloat16(weights_data.data(), weights_data_f32.data(), product(weights_dims)*head_number);

    // Create memory descriptors and memory objects for src, weights, bias, and
    // dst.

#ifdef TEST_BF16
    auto test_dt = dt::bf16;
#else
    auto test_dt = dt::f32;
#endif

    auto src_md = memory::desc(src_dims, test_dt, {K*head_number*M, K*head_number, 1});
    auto weights_md = memory::desc(weights_dims, test_dt, {K*N*head_number, 1, K*head_number});

#if 0
    auto src_md = memory::desc(src_dims, test_dt, tag::abc);
    auto weights_md = memory::desc(weights_dims, test_dt, tag::abc);
#endif

    auto dst_md = memory::desc(dst_dims, test_dt, {M*N, N, 1});

    // auto src_mem = memory(src_md, engine);
    // auto weights_mem = memory(weights_md, engine);
    // auto dst_mem = memory(dst_md, engine);


    // Create operation descriptor
    auto matmul_d = matmul::desc(src_md, weights_md, dst_md);


    // Create primitive descriptor.
    auto matmul_pd = matmul::primitive_desc(matmul_d, engine);

    // Create the primitive.
    auto matmul_prim = matmul(matmul_pd);

    // Primitive arguments.
    // Write data to memory object's handles.
    for (int j=0; j<50;j++) {
        
    for (int i=0; i<head_number; i++) {
        std::unordered_map<int, memory> matmul_args;
        #ifdef TEST_BF16
            auto src_mem = memory(src_md, engine, src_data.data()+K*i);
            auto weights_mem = memory(weights_md, engine, weights_data.data() + K*i);
            auto dst_mem = memory(dst_md, engine, dst_data.data()+MB*M*N*i);
        #else
            auto src_mem = memory(src_md, engine, src_data_f32.data()+K*i);
            auto weights_mem = memory(weights_md, engine, weights_data_f32.data() + K*i);
            auto dst_mem = memory(dst_md, engine, dst_data_f32.data()+MB*M*N*i);
        #endif
        matmul_args.insert({DNNL_ARG_SRC, src_mem});
        matmul_args.insert({DNNL_ARG_WEIGHTS, weights_mem});
        matmul_args.insert({DNNL_ARG_DST, dst_mem});

        // Primitive execution: matrix multiplication with ReLU.
        matmul_prim.execute(engine_stream, matmul_args);

        // Wait for the computation to finalize.
        engine_stream.wait();

        // Read data from memory object's handle.
        // read_from_dnnl_memory(dst_data.data()+MB*M*N*i, dst_mem);
    }
    }
}

int main(int argc, char **argv) {
    return handle_example_errors(matmul_example, parse_engine_kind(argc, argv));
}

```
bf16 result:
```bash
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.00781
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12305
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12207
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12598
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12109
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12891
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12305
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.125
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.01392
```

fp32 result:
```bash
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.00781
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12305
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12207
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12598
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12109
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12891
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.12305
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.125
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_bf16::blocked:abc:f0 wei_bf16::blocked:acb:f0 dst_bf16::blocked:abc:f0,,,b1023m150n1k36,4.01392
```

**Comment by emfomenk** [comment]
Hi @ahuizxc,

Unfortunately, batched matmul is not yet well optimized in the library. We only have naive parallelization over batch now. So make sure your version of oneDNN contains 04b63b6f63800616581033f34f225e79258baf55 commit, i.e. the version >= 1.3.
