### ISSUE TITLE
avx2 s8s8 convolution kernel precision loss

### ISSUE THREAD

**Issue by ych622** [intel/mkl-dnn#645]
Hi, 

I noticed that in int8 convolution kernel, when the input is signed, it imposes a scaling factor of 0.5 on weights. What is the reason behind this? The weights will actually be quantized to -63 to 63, I'm concerned that the precision loss will be greater than that if the weights are not additionally scaled. 

Thanks,
Yuankai

**Comment by emfomenk** [comment]
Hi @ych622,

This is very good question! Please check [Int8 Computation Aspects](https://intel.github.io/mkl-dnn/dev_guide_int8_computations.html) in [the reference manual](https://intel.github.io/mkl-dnn/index.html). More precisely, towards the end of the section *"2. Inputs of the same type: s8"*. But I definitely recommend to go through the whole article.

Consider `avx2` as `avx512` on Skylake (Intel Xeon Scalable processor x1xx series). The former has absolutely the same issue as the latter one.

---
P.S. we need to update the article to include `avx2`...`
