### ISSUE TITLE
Is this a typo error of name conventions?

### ISSUE THREAD

**Issue by Leslie-Fang** [intel/mkl-dnn#648]
# Summary
In the name conventions, there are 2 kernel(filter) height, width and depth in dh and kh.
https://github.com/intel/mkl-dnn/blame/master/doc/naming_conventions.md#L60

# URLs
https://github.com/intel/mkl-dnn/blame/master/doc/naming_conventions.md#L60

# Additional details
Is dd, dh, dw the parameters for dilated Convolution?

**Comment by emfomenk** [comment]
Hi @Leslie-Fang.

You are absolutely right. The line should be:
```
dd, dh, dw                               | kernel (filter) dilation for depth, height, and width
```

Will fix that. Thanks!

**Comment by Leslie-Fang** [comment]
Thanks
