### ISSUE TITLE
Difference between mkl-dnn and intel mkl full library

### ISSUE THREAD

**Issue by fesun** [intel/mkl-dnn#652]
Hi, what's the difference between this repo and the mkl full library.(https://software.intel.com/en-us/mkl) Now our system is using Eigen with intel mkl enabled(https://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html), will there any additional performance benefit if we change code and switch to mkl-dnn?
Also I read the documents and found mkl-dnn team did a lot of work to integrate mkl-dnn to popular deep learning frameworks like TensorFlow, my question is since TensorFlow is using Eigen, so why writing lots of mkl specified operators instead of linking Eigen with mkl to speedup?

**Comment by rsdubtso** [comment]
Hi @fesun, thanks for the question.

MKL and DNNL/MKL-DNN target different functional domain. MKL is the traditional HPC (BLAS, LAPACK, FFTs, vector ops, etc.), and DNNL is the CNNs, RNNs, etc. Additionally, TensorFlow implements substantial part of the kernels (like convolution) on top of Eigen, but not by calling Eigen directly. This means that DNNL typically outperforms TF on top of MKL-enabled Eigen.

**Comment by fesun** [comment]
Thanks @rsdubtso !
The accuracy loss of 8bits quantization for our model is too large for our model and we are using 16bits, is there any plan to support int16/uint16 gemm in DNNL?
Also mkldnn_gemm_bf16bf16f32 converts bfloat16 to float32 if the hardware doesn't support bfloat16 computation directly? So bfloat16 only save memory bandwidth and not too much performance benefit compared to float32?

**Comment by rsdubtso** [comment]
> The accuracy loss of 8bits quantization for our model is too large for our model and we are using 16bits, is there any plan to support int16/uint16 gemm in DNNL?

We did not have enough requests for this, so there're no plans at the moment. It would be useful to know which operations you are interested in.

> Also mkldnn_gemm_bf16bf16f32 converts bfloat16 to float32 if the hardware doesn't support bfloat16 computation directly? So bfloat16 only save memory bandwidth and not too much performance benefit compared to float32?

The bfloat16 operations are generally not expected to be faster than float32 on machines without bfloat16 ISA. They are provided so that it is possible to validate functionality / accuracy on future Intel CPUs.

**Comment by fesun** [comment]
matmul(for example m=100 k=4000 n=1024, not small ones) and activation functions like relu selu tanh etc.
Thanks for your response. @rsdubtso
