### ISSUE TITLE
Questions about Resampling primitive

### ISSUE THREAD

**Issue by lisa0314** [intel/mkl-dnn#653]
For resize_blinear algorithm,  [tensorflow](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/image/resize_bilinear) defines:
>align_corners: An optional bool. Defaults to False. If true, the centers of the 4 corner pixels of the input and output tensors are aligned, preserving the values at the corner pixels.

I wonder whether the [resampling](http://intel.github.io/mkl-dnn/dev_guide_resampling.html) support align_corner when using Bilinear algorithm.

**Comment by vpirogov** [comment]
Resampling primitive behaves in the same way as [Tensorflow 2.0's resize](https://www.tensorflow.org/api_docs/python/tf/image/resize) implementation. This implementation does preserve the image corners similar to TF 1.x with `align_corners=True`, but interpolation result will be different. Looking at the docs TF 2.0 behavior matches TF 1.x with `align_corners=True` and `half_pixel_centers=True`.

**Comment by lisa0314** [comment]
@vpirogov I got it! Thanks for your explanation.
