### ISSUE TITLE
Ops supported by MKL and MKL-DNN

### ISSUE THREAD

**Issue by whatdhack** [intel/mkl-dnn#659]
Looking for  info and examples of the the following.

1.  In Tensorflow/Keras (1.15) , occasionally  see op MklMul ( vs just Mul ).  Looked into Tensorflow source  and only see reference to https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/kernels/cwise_op_mul_1.cc .   Where is the op MklMul  located ? 

2.  Is there  a  release note etc where a comprehensive list of supported ops ( for Tensorflow or Pytorch) can be found ? 

3. Is there a example of custom op for Tensorflow ?

**Comment by vpirogov** [comment]
Hi @whatdhack,

You can find the list of operations supported by DNNL in _Primitives_ section of the [developer guide](http://intel.github.io/mkl-dnn/). The library supports elementwise multiplication via [binary](http://intel.github.io/mkl-dnn/dev_guide_binary.html) primitive, but I do not know whether Tensorflow is using this functionality or how MklMul might be implemented in Tensorflow.

Framework integration is out of scope for this project. You'll likely to get better support for Tensorflow and Pytorch related questions from these projects maintainers.

**Comment by vpirogov** [comment]
Closing for now. Feel free to reopen or submit a new one if you have any further questions.
