### ISSUE TITLE
how to get the matrix A memory size,when using cblas_gemm_pack   or using cblas_sgemm_alloc

### ISSUE THREAD

**Issue by victorygogogo** [intel/mkl-dnn#660]
float* aptr = cblas_sgemm_alloc(CblasAMatrix,m,n,k)
how to get the memory size when using cblas_sgemm_alloc ?

**Comment by victorygogogo** [comment]
I found cblas_sgemm_pack_get_size is very big, 
how to get the only packed Amatrix memory size ?

**Comment by mgouicem** [comment]
Hi @victorygogogo ,
First, note that `cblas_sgemm_alloc` is deprecated, so you should use `cblas_sgemm_pack_get_size` and allocate the buffer yourself.
Second, the `cblas_sgemm_pack_get_size` returns only the size of the matrix you specified in argument (see https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemm-pack-get-size-cblas-gemm-pack-get-size). So if you did:
`cblas_sgemm_pack_get_size(CblasAMatrix, m, n, k)`
then you get only the size to pack the A matrix. 
This buffer can be large as extra memory is required to guarantee data alignment, pad data and write metadata. @aaraujom can comment more on that.

**Comment by aaraujom** [comment]
Hi @victorygogogo - Mourad is correct. The internal format needs to be larger such we can store metadata and pad data for better performance. Probably a better place to ask questions related to Intel Math Kernel Library are on their [forums](https://software.intel.com/en-us/forums/intel-math-kernel-library/).

**Comment by rsdubtso** [comment]
Closing as out-of-scope for DNNL. Please follow the link to the MKL forums in the @aaraujom's reply.

**Comment by victorygogogo** [comment]
@mgouicem  @rsdubtso   thanks.
