### ISSUE TITLE
macOS  compilation with openmp 

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#661]
Hi,

Since the native clang compiler in macOS does not support the openmp . I have installed the openmp using brew . I am facing issues when I tried to build the mkldnn using the installed openmp.

Below snapshot contains steps I have followed for installation of brew,cmake,openmp and mkldnn
![image](https://user-images.githubusercontent.com/25972734/75979974-a4a66700-5f07-11ea-916f-723be1f8565b.png)

Though cmake command was able to find the openmp, I was getting linking error since the openmp library was not linked.
Below are the snapshots for build and link errors
![cmakebuild1](https://user-images.githubusercontent.com/25972734/75981048-ac670b00-5f09-11ea-9282-9b8800a8a9ec.png)

![Error](https://user-images.githubusercontent.com/25972734/75980383-5ba2e280-5f08-11ea-810e-abdd6e852b9a.png)

To build the mkldnn library using openmp , I have changed the OpenMP.cmake to include the omp library as shown below. 
![cmakeChange](https://user-images.githubusercontent.com/25972734/75980681-fd2a3400-5f08-11ea-81ef-4f58b9021283.png)

With this change I was able to successfully build and test it.
Could you add this change as part of mkldnn repo ? 
If not, Is there any mechanism to avail this kind of build option (native clang + openmp ) for mkldnn. 

Thank you,
Praveen,

**Comment by rsdubtso** [comment]
Hi @uu-praveeng, does the solution from https://github.com/intel/mkl-dnn/issues/591 work for you?

**Comment by uu-praveeng** [comment]
Hi @rsdubtso ,

I am not aware of "spack-based Clang" . Hence I did not try out that solution.
I want to try out a solution using native clang + 3rd party openmp.

Thank you,
Praveen.

**Comment by rsdubtso** [comment]
The solution there works for me with brew Openmp and stock apple provided clang. Can you please try it?

**Comment by uu-praveeng** [comment]
Thanks @rsdubtso for quick response. It worked cheers!!!

**Comment by uu-praveeng** [comment]
Hi @rsdubtso 

I have a follow up question on this
1. When I used the command that was provided in solution
`/usr/local/bin/cmake .. -DOpenMP_CXX_FLAGS="-Xclang -fopenmp -I/usr/local/Cellar/libomp/9.0.1/include" -DOpenMP_C_FLAGS="-Xclang -fopenmp -I/usr/local/Cellar/libomp/9.0.1/include" -DOpenMP_CXX_LIB_NAMES=libomp  -DOpenMP_C_LIB_NAMES=libomp -DOpenMP_libomp_LIBRARY=/usr/local/Cellar/libomp/9.0.1/lib/libomp.dylib -DCMAKE_SHARED_LINKER_FLAGS="-L/usr/local/Cellar/libomp/9.0.1/lib -lomp -Wl,-rpath,/usr/local/Cellar/libomp/9.0.1/lib" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON `


`otool- L libmkldnn.dylib ` has dependency on /usr/local/Cellar/libomp/9.0.1/lib/libomp.dylib 
I have moved the mkldnn,omp libraries to a different PC(which doesnot have libomp installed) and I tried to run sample application which uses mkldnn library. It throws error showing dependency of libiomp.dylib.

Is this hard binding of path expected in mac PC?

Thank you,
Praveen.

**Comment by rsdubtso** [comment]
Yes, this behavior is expected.

I think [this document](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling) provides at least some explanation. You may also want to read [this](https://blog.krzyzanowskim.com/2018/12/05/rpath-what/).

You may need to use `install_name_tool` to adjust the RPATH; `otool -l` will print the current RPATH entries.

Closing as not directly DNNL related :)
