### ISSUE TITLE
mkl-dnn version vs tensorflow version

### ISSUE THREAD

**Issue by ratan** [intel/mkl-dnn#667]
I want to git clone and build mkl-dnn (dnnl) and tensorflow from source.
Is there any guideline which mkl-dnn version works best with which version of tensorflow?
E.g. with Tensorflow branch v2.0 which branch of mkl-dnn to use for best performance?
with Tensorflow branch 1.15 which branch of mkl-dn to use for best performance?
Is there any guidelines?

**Comment by vpirogov** [comment]
@ratan,

In general we recommend using the latest stable version of DNNL for the best performance. Note, that major library versions 0.x and 1.x are note API compatible and moving from v0.x to v1.x requires code changes. As of today the latest stable versions are [v0.21.4](https://github.com/intel/mkl-dnn/releases/tag/v0.21.4) and [v1.2.1](https://github.com/intel/mkl-dnn/releases/tag/v1.2.1).

Tensorflow v1.15 [builds with v0.20.6](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/workspace.bzl#L142) by default and you may try upgrade the library version to v0.21.4. 

Tensorflow v2.2 [builds with v0.21.3](https://github.com/tensorflow/tensorflow/blob/r2.2/tensorflow/workspace.bzl#L171), which is one patch short of the latest version. It has an option to build with v1.2, but support for v1.x did not reach production maturity yet.

Hope this helps,
Vadim

**Comment by ratan** [comment]
Thanks @vpirogov for the detailed reply. 
I have few more questions, it will be great if you if you may answer them:

1. Tensorflow v1.15 builds with v0.20.6 by default.
I checked out TF 1.15 branch, see following details in **third_party/mkl_dnn/mkldnn.BUILD**
template_rule(
    name = "mkldnn_version_h",
    src = "include/mkldnn_version.h.in",
    out = "include/mkldnn_version.h",
    substitutions = {
        "@MKLDNN_VERSION_MAJOR@": "0",
        "@MKLDNN_VERSION_MINOR@": "20",
        "@MKLDNN_VERSION_PATCH@": "3",
        "@MKLDNN_VERSION_HASH@": "N/A",
    },
)
Which indicates version 0.20.3

In the file **bazel-out/host/bin/external/mkl_dnn/include/mkldnn_version.h**
/* Major version of MKL-DNN */
#define MKLDNN_VERSION_MAJOR 0

/* Minor version of MKL-DNN */
#define MKLDNN_VERSION_MINOR 20

/* Patch version of MKL-DNN */
#define MKLDNN_VERSION_PATCH 3

Are they correct place to find out which version of mkl-dnn was used to build Tensorflow?

2. So latest Tensorflow builds (v2.2) uses the 0.x version of mkl-dnn and not 1.x version. If someone wants to build Tensorflow v2.2 with 1.x version of mkl-dnn (which has API changes) what optional flags is required to build Tensorflow ? I hope user doesn't require to do some code changes in Tensorflow to build it with 1.x version of mkl-dnn.

3. Latest stable version of Tensorflow uses 0.x version of mkl-dnn. Will this be default behaviour? Or there is any plan to integrate Tensorflow with 1.x version of mkl-dnn in future?

**Comment by vpirogov** [comment]
The v0.20.3 looks incorrect, as actual package TF downloads is v0.20.6. TF uses it's own bazel-based build system to build it's dependencies, including DNNL. As part of build process it generates `mkldnn_version.h` file and puts version information there. Actual version of the library that TF builds is included into bazel configuration [here](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/workspace.bzl#L142).

Transition of Tensorflow to DNNL v1.x should happen in one of future releases. I'm not directly involved into Tensorflow development though and do not have full picture of the plans. 

@nhasabni, @bhavani-subramanian could you please help with question related to TF transition to DNNL v1.x?

**Comment by bhavani-subramanian** [comment]
@ratan The latest version of TF uses DNNL v1.2 by default [(PR)](https://github.com/tensorflow/tensorflow/pull/37106) i.e. when compiling using `--config=mkl`, DNNL v1.2 will be downloaded. To use v0.x, you need to build with `--config=mkl_open_source_only`.

Hope this helps!

**Comment by ratan** [comment]
Thanks @bhavani-subramanian @vpirogov It was really helpful.
